set_property SRC_FILE_INFO {cfile:c:/Vulcan/Design_Tool/Board_Demo/VC707/vc707_pcie_x8_gen2_ex/imports/xilinx_pcie_7x_ep_x8g2_VC707.xdc rfile:../../../imports/xilinx_pcie_7x_ep_x8g2_VC707.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AV35 [get_ports sys_rst_n]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AM39 [get_ports led_0]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AN39 [get_ports led_1]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AR37 [get_ports led_2]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AT37 [get_ports led_3]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y5 [get_cells refclk_ibuf]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type DRC -id {REQP-1840} -scope -internal -user "pcie_7x" -tags "1167258" -desc "DRC expects synchronous pins to be provided to BRAM inputs. Since synchronization is present one stage before, it is safe to ignore" -objects [get_cells -hier -filter {NAME =~ {*/inst/inst/pr_loader_i/*.WIDE_PRIM18.ram}}]
