# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/hdmi_output/hdmi_output.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/design_1_v_proc_ss_0_0.xci
# IP: The module: 'design_1_v_proc_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Vulcan/Design_Tool/Board_Demo/VC707/hdmi_output/hdmi_output.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_d92b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b || ORIG_REF_NAME==bd_d92b} -quiet] -quiet

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/hdmi_output/hdmi_output.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_0/bd_d92b_csc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_csc_0 || ORIG_REF_NAME==bd_d92b_csc_0} -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/hdmi_output/hdmi_output.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_d92b_ooc.xdc

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/hdmi_output/hdmi_output.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/design_1_v_proc_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_proc_ss_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/hdmi_output/hdmi_output.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/design_1_v_proc_ss_0_0.xci
# IP: The module: 'design_1_v_proc_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Vulcan/Design_Tool/Board_Demo/VC707/hdmi_output/hdmi_output.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_d92b.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b || ORIG_REF_NAME==bd_d92b} -quiet] -quiet

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/hdmi_output/hdmi_output.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_0/bd_d92b_csc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_csc_0 || ORIG_REF_NAME==bd_d92b_csc_0} -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/hdmi_output/hdmi_output.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_d92b_ooc.xdc

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/hdmi_output/hdmi_output.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/design_1_v_proc_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_proc_ss_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
