# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.cache/wt [current_project]
set_property parent.project_path C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
read_ip C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2.xci
set_property used_in_implementation false [get_files -all c:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/ip/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2-PCIE_X1Y0.xdc]
set_property used_in_implementation false [get_files -all c:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/ip/vc707_pcie_x8_gen2/synth/vc707_pcie_x8_gen2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2.dcp]
set_property is_locked true [get_files C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2.xci]

read_verilog -library xil_defaultlib {
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/EP_MEM.v
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/PIO_EP_MEM_ACCESS.v
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/PIO_RX_ENGINE.v
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/PIO_TX_ENGINE.v
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/PIO_EP.v
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/PIO_TO_CTRL.v
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/PIO.v
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/support/vc707_pcie_x8_gen2_pipe_clock.v
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/pcie_app_7x.v
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/support/vc707_pcie_x8_gen2_support.v
  C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/sources_1/imports/vc707_pcie_x8_gen2/example_design/xilinx_pcie_2_1_ep_7x.v
}
read_xdc C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x8g2_VC707.xdc
set_property used_in_implementation false [get_files C:/vc707_pcie/vc707_pcie_x8_gen2_example/vc707_pcie_x8_gen2_example.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x8g2_VC707.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top xilinx_pcie_2_1_ep_7x -part xc7vx485tffg1761-2
write_checkpoint -noxdef xilinx_pcie_2_1_ep_7x.dcp
catch { report_utilization -file xilinx_pcie_2_1_ep_7x_utilization_synth.rpt -pb xilinx_pcie_2_1_ep_7x_utilization_synth.pb }
