# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.srcs/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0.xci
# IP: The module: 'versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/ip_0/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0_gtreset.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0_gtreset || ORIG_REF_NAME==versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0_gtreset} -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/ip_0/synth/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0_gtreset_ooc.xdc

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/synth/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.srcs/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0.xci
# IP: The module: 'versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/ip_0/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0_gtreset.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0_gtreset || ORIG_REF_NAME==versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0_gtreset} -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/ip_0/synth/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0_gtreset_ooc.xdc

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/synth/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
