# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Vivado/versal_ibert.xdc

# Block Designs: bd/versal_ibert/versal_ibert.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert || ORIG_REF_NAME==versal_ibert} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_versal_cips_0_0/versal_ibert_versal_cips_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_versal_cips_0_0 || ORIG_REF_NAME==versal_ibert_versal_cips_0_0} -quiet] -quiet

# Block Designs: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_versal_cips_0_0/bd_0/bd_dcee.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dcee || ORIG_REF_NAME==bd_dcee} -quiet] -quiet

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_versal_cips_0_0/bd_0/ip/ip_0/bd_dcee_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dcee_pspmc_0_0 || ORIG_REF_NAME==bd_dcee_pspmc_0_0} -quiet] -quiet

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_versal_cips_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X0Y12_0/versal_ibert_bridge_refclkGTYP_REFCLK_X0Y12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bridge_refclkGTYP_REFCLK_X0Y12_0 || ORIG_REF_NAME==versal_ibert_bridge_refclkGTYP_REFCLK_X0Y12_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_gt_quad_base_0/versal_ibert_gt_quad_base_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_gt_quad_base_0 || ORIG_REF_NAME==versal_ibert_gt_quad_base_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_0/versal_ibert_bufg_gt_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_1_0/versal_ibert_bufg_gt_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_1_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_1_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_urlp_0/versal_ibert_urlp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_urlp_0 || ORIG_REF_NAME==versal_ibert_urlp_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlcp_0/versal_ibert_xlcp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlcp_0 || ORIG_REF_NAME==versal_ibert_xlcp_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_util_ds_buf_0/versal_ibert_util_ds_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_util_ds_buf_0 || ORIG_REF_NAME==versal_ibert_util_ds_buf_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0 || ORIG_REF_NAME==versal_ibert_bridge_refclkGTYP_REFCLK_X1Y0_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_gt_quad_base_1_0/versal_ibert_gt_quad_base_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_gt_quad_base_1_0 || ORIG_REF_NAME==versal_ibert_gt_quad_base_1_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_2_0/versal_ibert_bufg_gt_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_2_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_2_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_3_0/versal_ibert_bufg_gt_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_3_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_3_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_urlp_1_0/versal_ibert_urlp_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_urlp_1_0 || ORIG_REF_NAME==versal_ibert_urlp_1_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlcp_1_0/versal_ibert_xlcp_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlcp_1_0 || ORIG_REF_NAME==versal_ibert_xlcp_1_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_util_ds_buf_1_0/versal_ibert_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_util_ds_buf_1_0 || ORIG_REF_NAME==versal_ibert_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y2_0/versal_ibert_bridge_refclkGTYP_REFCLK_X1Y2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bridge_refclkGTYP_REFCLK_X1Y2_0 || ORIG_REF_NAME==versal_ibert_bridge_refclkGTYP_REFCLK_X1Y2_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_gt_quad_base_2_0/versal_ibert_gt_quad_base_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_gt_quad_base_2_0 || ORIG_REF_NAME==versal_ibert_gt_quad_base_2_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_4_0/versal_ibert_bufg_gt_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_4_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_4_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_5_0/versal_ibert_bufg_gt_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_5_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_5_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_urlp_2_0/versal_ibert_urlp_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_urlp_2_0 || ORIG_REF_NAME==versal_ibert_urlp_2_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlcp_2_0/versal_ibert_xlcp_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlcp_2_0 || ORIG_REF_NAME==versal_ibert_xlcp_2_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_util_ds_buf_2_0/versal_ibert_util_ds_buf_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_util_ds_buf_2_0 || ORIG_REF_NAME==versal_ibert_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bridge_refclkGTM_REFCLK_X0Y0_0/versal_ibert_bridge_refclkGTM_REFCLK_X0Y0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bridge_refclkGTM_REFCLK_X0Y0_0 || ORIG_REF_NAME==versal_ibert_bridge_refclkGTM_REFCLK_X0Y0_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_gt_quad_base_3_0/versal_ibert_gt_quad_base_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_gt_quad_base_3_0 || ORIG_REF_NAME==versal_ibert_gt_quad_base_3_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_6_0/versal_ibert_bufg_gt_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_6_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_6_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_7_0/versal_ibert_bufg_gt_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_7_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_7_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_urlp_3_0/versal_ibert_urlp_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_urlp_3_0 || ORIG_REF_NAME==versal_ibert_urlp_3_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlcp_3_0/versal_ibert_xlcp_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlcp_3_0 || ORIG_REF_NAME==versal_ibert_xlcp_3_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_util_ds_buf_3_0/versal_ibert_util_ds_buf_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_util_ds_buf_3_0 || ORIG_REF_NAME==versal_ibert_util_ds_buf_3_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlconstant_0/versal_ibert_xlconstant_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlconstant_0 || ORIG_REF_NAME==versal_ibert_xlconstant_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bridge_refclkGTM_REFCLK_X0Y2_0/versal_ibert_bridge_refclkGTM_REFCLK_X0Y2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bridge_refclkGTM_REFCLK_X0Y2_0 || ORIG_REF_NAME==versal_ibert_bridge_refclkGTM_REFCLK_X0Y2_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_gt_quad_base_4_0/versal_ibert_gt_quad_base_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_gt_quad_base_4_0 || ORIG_REF_NAME==versal_ibert_gt_quad_base_4_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_8_0/versal_ibert_bufg_gt_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_8_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_8_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_9_0/versal_ibert_bufg_gt_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_9_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_9_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_urlp_4_0/versal_ibert_urlp_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_urlp_4_0 || ORIG_REF_NAME==versal_ibert_urlp_4_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlcp_4_0/versal_ibert_xlcp_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlcp_4_0 || ORIG_REF_NAME==versal_ibert_xlcp_4_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_util_ds_buf_4_0/versal_ibert_util_ds_buf_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_util_ds_buf_4_0 || ORIG_REF_NAME==versal_ibert_util_ds_buf_4_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlconstant_1_0/versal_ibert_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlconstant_1_0 || ORIG_REF_NAME==versal_ibert_xlconstant_1_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0/versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0 || ORIG_REF_NAME==versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_gt_quad_base_5_0/versal_ibert_gt_quad_base_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_gt_quad_base_5_0 || ORIG_REF_NAME==versal_ibert_gt_quad_base_5_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_10_0/versal_ibert_bufg_gt_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_10_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_10_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_11_0/versal_ibert_bufg_gt_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_11_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_11_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_urlp_5_0/versal_ibert_urlp_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_urlp_5_0 || ORIG_REF_NAME==versal_ibert_urlp_5_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlcp_5_0/versal_ibert_xlcp_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlcp_5_0 || ORIG_REF_NAME==versal_ibert_xlcp_5_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_util_ds_buf_5_0/versal_ibert_util_ds_buf_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_util_ds_buf_5_0 || ORIG_REF_NAME==versal_ibert_util_ds_buf_5_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlconstant_2_0/versal_ibert_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlconstant_2_0 || ORIG_REF_NAME==versal_ibert_xlconstant_2_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bridge_refclkGTM_REFCLK_X0Y6_0/versal_ibert_bridge_refclkGTM_REFCLK_X0Y6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bridge_refclkGTM_REFCLK_X0Y6_0 || ORIG_REF_NAME==versal_ibert_bridge_refclkGTM_REFCLK_X0Y6_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_gt_quad_base_6_0/versal_ibert_gt_quad_base_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_gt_quad_base_6_0 || ORIG_REF_NAME==versal_ibert_gt_quad_base_6_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_12_0/versal_ibert_bufg_gt_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_12_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_12_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_13_0/versal_ibert_bufg_gt_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_13_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_13_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_urlp_6_0/versal_ibert_urlp_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_urlp_6_0 || ORIG_REF_NAME==versal_ibert_urlp_6_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlcp_6_0/versal_ibert_xlcp_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlcp_6_0 || ORIG_REF_NAME==versal_ibert_xlcp_6_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_util_ds_buf_6_0/versal_ibert_util_ds_buf_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_util_ds_buf_6_0 || ORIG_REF_NAME==versal_ibert_util_ds_buf_6_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlconstant_3_0/versal_ibert_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlconstant_3_0 || ORIG_REF_NAME==versal_ibert_xlconstant_3_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bridge_refclkGTM_REFCLK_X0Y8_0/versal_ibert_bridge_refclkGTM_REFCLK_X0Y8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bridge_refclkGTM_REFCLK_X0Y8_0 || ORIG_REF_NAME==versal_ibert_bridge_refclkGTM_REFCLK_X0Y8_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_gt_quad_base_7_0/versal_ibert_gt_quad_base_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_gt_quad_base_7_0 || ORIG_REF_NAME==versal_ibert_gt_quad_base_7_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_14_0/versal_ibert_bufg_gt_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_14_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_14_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_bufg_gt_15_0/versal_ibert_bufg_gt_15_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_bufg_gt_15_0 || ORIG_REF_NAME==versal_ibert_bufg_gt_15_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_urlp_7_0/versal_ibert_urlp_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_urlp_7_0 || ORIG_REF_NAME==versal_ibert_urlp_7_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlcp_7_0/versal_ibert_xlcp_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlcp_7_0 || ORIG_REF_NAME==versal_ibert_xlcp_7_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_util_ds_buf_7_0/versal_ibert_util_ds_buf_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_util_ds_buf_7_0 || ORIG_REF_NAME==versal_ibert_util_ds_buf_7_0} -quiet] -quiet

# IP: bd/versal_ibert/ip/versal_ibert_xlconstant_4_0/versal_ibert_xlconstant_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_ibert_xlconstant_4_0 || ORIG_REF_NAME==versal_ibert_xlconstant_4_0} -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_versal_cips_0_0/bd_0/ip/ip_0/bd_dcee_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_dcee_pspmc_0_0 || ORIG_REF_NAME==bd_dcee_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_dcee_pspmc_0_0 || ORIG_REF_NAME==bd_dcee_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_versal_cips_0_0/bd_0/bd_dcee_ooc.xdc

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/versal_ibert_ooc.xdc
