# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Vulcan/Design_Tool/Board_Demo/ZCU208/usp_rf_data_converter_0_ex/imports/usp_rf_data_converter_0_example_design.xdc

# Block Designs: bd/rfdc_ex/rfdc_ex.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex || ORIG_REF_NAME==rfdc_ex} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_usp_rf_data_converter_0_0/rfdc_ex_usp_rf_data_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_usp_rf_data_converter_0_0 || ORIG_REF_NAME==rfdc_ex_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_adc_sink_i_0/rfdc_ex_adc_sink_i_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_adc_sink_i_0 || ORIG_REF_NAME==rfdc_ex_adc_sink_i_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_dac_source_i_0/rfdc_ex_dac_source_i_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_dac_source_i_0 || ORIG_REF_NAME==rfdc_ex_dac_source_i_0} -quiet] -quiet

# IP: bd/rfdc_ex/ip/rfdc_ex_smartconnect_0_0/rfdc_ex_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rfdc_ex_smartconnect_0_0 || ORIG_REF_NAME==rfdc_ex_smartconnect_0_0} -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/ZCU208/usp_rf_data_converter_0_ex/usp_rf_data_converter_0_ex.gen/sources_1/bd/rfdc_ex/rfdc_ex_ooc.xdc
