# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/vc707_pcie_x8_gen2_ex/vc707_pcie_x8_gen2_ex.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2.xci
# IP: The module: 'vc707_pcie_x8_gen2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/vc707_pcie_x8_gen2_ex/vc707_pcie_x8_gen2_ex.gen/sources_1/ip/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2-PCIE_X1Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/vc707_pcie_x8_gen2_ex/vc707_pcie_x8_gen2_ex.gen/sources_1/ip/vc707_pcie_x8_gen2/source/ip_xilinx_pcie_2_1_7x_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/vc707_pcie_x8_gen2_ex/vc707_pcie_x8_gen2_ex.gen/sources_1/ip/vc707_pcie_x8_gen2/synth/vc707_pcie_x8_gen2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Vulcan/Design_Tool/Board_Demo/VC707/vc707_pcie_x8_gen2_ex/vc707_pcie_x8_gen2_ex.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2.xci
# IP: The module: 'vc707_pcie_x8_gen2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/vc707_pcie_x8_gen2_ex/vc707_pcie_x8_gen2_ex.gen/sources_1/ip/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2-PCIE_X1Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/vc707_pcie_x8_gen2_ex/vc707_pcie_x8_gen2_ex.gen/sources_1/ip/vc707_pcie_x8_gen2/source/ip_xilinx_pcie_2_1_7x_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Design_Tool/Board_Demo/VC707/vc707_pcie_x8_gen2_ex/vc707_pcie_x8_gen2_ex.gen/sources_1/ip/vc707_pcie_x8_gen2/synth/vc707_pcie_x8_gen2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
