// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        height_val,
        width_val,
        patternId_val,
        ZplateHorContStart_val,
        ZplateHorContDelta_val,
        ZplateVerContStart_val,
        ZplateVerContDelta_val,
        dpDynamicRange_val,
        dpYUVCoef_val,
        motionSpeed_val,
        colorFormat_val,
        bckgndYUV_din,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        bckgndYUV_full_n,
        bckgndYUV_write,
        height_val4_c12_din,
        height_val4_c12_num_data_valid,
        height_val4_c12_fifo_cap,
        height_val4_c12_full_n,
        height_val4_c12_write,
        width_val7_c13_din,
        width_val7_c13_num_data_valid,
        width_val7_c13_fifo_cap,
        width_val7_c13_full_n,
        width_val7_c13_write,
        motionSpeed_val14_c_din,
        motionSpeed_val14_c_num_data_valid,
        motionSpeed_val14_c_fifo_cap,
        motionSpeed_val14_c_full_n,
        motionSpeed_val14_c_write,
        colorFormat_val17_c14_din,
        colorFormat_val17_c14_num_data_valid,
        colorFormat_val17_c14_fifo_cap,
        colorFormat_val17_c14_full_n,
        colorFormat_val17_c14_write,
        s
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] height_val;
input  [15:0] width_val;
input  [7:0] patternId_val;
input  [15:0] ZplateHorContStart_val;
input  [15:0] ZplateHorContDelta_val;
input  [15:0] ZplateVerContStart_val;
input  [15:0] ZplateVerContDelta_val;
input  [7:0] dpDynamicRange_val;
input  [7:0] dpYUVCoef_val;
input  [7:0] motionSpeed_val;
input  [7:0] colorFormat_val;
output  [35:0] bckgndYUV_din;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
output  [15:0] height_val4_c12_din;
input  [2:0] height_val4_c12_num_data_valid;
input  [2:0] height_val4_c12_fifo_cap;
input   height_val4_c12_full_n;
output   height_val4_c12_write;
output  [15:0] width_val7_c13_din;
input  [2:0] width_val7_c13_num_data_valid;
input  [2:0] width_val7_c13_fifo_cap;
input   width_val7_c13_full_n;
output   width_val7_c13_write;
output  [7:0] motionSpeed_val14_c_din;
input  [2:0] motionSpeed_val14_c_num_data_valid;
input  [2:0] motionSpeed_val14_c_fifo_cap;
input   motionSpeed_val14_c_full_n;
output   motionSpeed_val14_c_write;
output  [7:0] colorFormat_val17_c14_din;
input  [2:0] colorFormat_val17_c14_num_data_valid;
input  [2:0] colorFormat_val17_c14_fifo_cap;
input   colorFormat_val17_c14_full_n;
output   colorFormat_val17_c14_write;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg bckgndYUV_write;
reg height_val4_c12_write;
reg width_val7_c13_write;
reg motionSpeed_val14_c_write;
reg colorFormat_val17_c14_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [11:0] rampStart;
reg   [15:0] rampVal_1;
reg   [11:0] rampVal;
reg   [7:0] hBarSel_4_0;
reg   [15:0] zonePlateVAddr;
reg   [2:0] vBarSel;
reg   [2:0] hBarSel_0;
reg   [15:0] hdata;
reg   [7:0] vBarSel_2;
reg   [2:0] hBarSel_3_0;
reg   [15:0] rampVal_2;
reg   [0:0] vBarSel_1;
reg   [2:0] hBarSel_5_0;
reg    height_val4_c12_blk_n;
reg    width_val7_c13_blk_n;
reg    motionSpeed_val14_c_blk_n;
reg    colorFormat_val17_c14_blk_n;
reg    ap_block_state1;
wire   [0:0] cmp2_i236_fu_672_p2;
reg   [0:0] cmp2_i236_reg_1295;
wire   [11:0] conv2_i_i10_i241_fu_678_p3;
reg   [11:0] conv2_i_i10_i241_reg_1300;
wire   [4:0] conv2_i_i_i_cast_cast_fu_686_p3;
reg   [4:0] conv2_i_i_i_cast_cast_reg_1305;
wire   [11:0] conv2_i_i10_i246_fu_694_p3;
reg   [11:0] conv2_i_i10_i246_reg_1310;
wire   [8:0] conv2_i_i_i248_cast_cast_fu_702_p3;
reg   [8:0] conv2_i_i_i248_cast_cast_reg_1315;
wire   [6:0] conv2_i_i10_i264_cast_cast_cast_cast_fu_710_p3;
reg   [6:0] conv2_i_i10_i264_cast_cast_cast_cast_reg_1320;
wire   [11:0] conv2_i_i_i266_fu_718_p3;
reg   [11:0] conv2_i_i_i266_reg_1325;
wire   [11:0] pix_fu_726_p3;
reg   [11:0] pix_reg_1330;
wire   [11:0] pix_5_fu_734_p3;
reg   [11:0] pix_5_reg_1335;
reg   [10:0] barWidth_reg_1340;
wire   [9:0] barWidthMinSamples_fu_782_p2;
reg   [9:0] barWidthMinSamples_reg_1346;
wire   [0:0] icmp_fu_812_p2;
reg   [0:0] icmp_reg_1351;
wire   [10:0] sub_i_i_i_fu_832_p2;
reg   [10:0] sub_i_i_i_reg_1356;
wire   [16:0] sub35_i_fu_838_p2;
reg   [16:0] sub35_i_reg_1361;
wire   [16:0] sub10_i_fu_844_p2;
reg   [16:0] sub10_i_reg_1366;
reg   [11:0] rampStart_load_reg_1371;
reg   [15:0] y_3_reg_1377;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp_i370_fu_1010_p2;
reg   [0:0] cmp_i370_reg_1385;
reg   [0:0] tmp_33_reg_1390;
reg   [1:0] colorSel_reg_1395;
wire   [0:0] cmp12_i_fu_1037_p2;
reg   [0:0] cmp12_i_reg_1400;
wire   [0:0] cmp11_i_fu_1044_p2;
reg   [0:0] cmp11_i_reg_1405;
wire   [11:0] trunc_ln565_fu_1050_p1;
reg   [11:0] trunc_ln565_reg_1410;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_ready;
wire   [35:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_bckgndYUV_write;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_3_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0_loc_1_out_o_ap_vld;
wire   [11:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_2_0_0_0217_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_2_0_0_0217_out_o_ap_vld;
wire   [11:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_1_0_0_0215_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_1_0_0_0215_out_o_ap_vld;
wire   [11:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_0_0_0_0213_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_0_0_0_0213_out_o_ap_vld;
wire   [11:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_1_ap_vld;
wire   [0:0] ap_phi_mux_rampVal_3_flag_0_phi_fu_458_p4;
reg   [0:0] rampVal_3_flag_0_reg_454;
wire    ap_CS_fsm_state4;
wire   [0:0] ap_phi_mux_hdata_flag_0_phi_fu_470_p4;
reg   [0:0] hdata_flag_0_reg_466;
wire   [0:0] ap_phi_mux_rampVal_2_flag_0_phi_fu_482_p4;
reg   [0:0] rampVal_2_flag_0_reg_478;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_start_reg;
wire   [0:0] icmp_ln563_fu_995_p2;
wire    ap_CS_fsm_state3;
reg   [15:0] rampVal_3_new_0_fu_340;
reg   [15:0] rampVal_3_loc_0_fu_336;
reg   [15:0] rampVal_loc_0_fu_332;
reg   [7:0] hBarSel_4_0_loc_0_fu_328;
reg   [15:0] zonePlateVAddr_loc_0_fu_324;
reg   [7:0] vBarSel_loc_0_fu_320;
reg   [7:0] hBarSel_0_loc_0_fu_316;
reg   [15:0] hdata_new_0_fu_312;
reg   [15:0] hdata_loc_0_fu_308;
reg   [7:0] vBarSel_2_loc_0_fu_304;
reg   [7:0] hBarSel_3_0_loc_0_fu_300;
reg   [15:0] rampVal_2_new_0_fu_296;
reg   [15:0] rampVal_2_loc_0_fu_292;
reg   [7:0] vBarSel_3_loc_0_fu_288;
reg   [7:0] hBarSel_5_0_loc_0_fu_284;
reg   [11:0] p_0_2_0_0_0218_lcssa227_fu_276;
reg   [11:0] p_0_1_0_0_0216_lcssa224_fu_272;
reg   [11:0] p_0_0_0_0_0214_lcssa221_fu_268;
wire   [11:0] add_ln750_fu_1063_p2;
reg   [15:0] y_fu_280;
wire   [15:0] add_ln563_fu_1000_p2;
wire   [7:0] zext_ln563_fu_922_p1;
wire   [7:0] zext_ln1775_fu_914_p1;
wire   [7:0] zext_ln1687_fu_902_p1;
wire   [7:0] zext_ln1545_fu_886_p1;
wire   [7:0] zext_ln1412_fu_878_p1;
wire   [15:0] zext_ln1257_fu_862_p1;
wire   [13:0] empty_fu_746_p1;
wire   [13:0] add_i_fu_750_p2;
wire   [13:0] add2_i_fu_766_p2;
wire   [9:0] p_cast_fu_772_p4;
wire   [13:0] empty_98_fu_792_p1;
wire   [6:0] tmp_fu_802_p4;
wire   [13:0] add5_i_fu_796_p2;
wire   [9:0] tmp_8_fu_818_p4;
wire   [10:0] barHeight_cast_fu_828_p1;
wire   [16:0] width_val_cast14_fu_742_p1;
wire   [16:0] height_val_cast15_fu_788_p1;
wire   [16:0] zext_ln563_1_fu_1006_p1;
wire   [11:0] zext_ln750_fu_1060_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 rampStart = 12'd0;
#0 rampVal_1 = 16'd0;
#0 rampVal = 12'd0;
#0 hBarSel_4_0 = 8'd0;
#0 zonePlateVAddr = 16'd0;
#0 vBarSel = 3'd0;
#0 hBarSel_0 = 3'd0;
#0 hdata = 16'd0;
#0 vBarSel_2 = 8'd0;
#0 hBarSel_3_0 = 3'd0;
#0 rampVal_2 = 16'd0;
#0 vBarSel_1 = 1'd0;
#0 hBarSel_5_0 = 3'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_start_reg = 1'b0;
#0 rampVal_3_loc_0_fu_336 = 16'd0;
#0 rampVal_loc_0_fu_332 = 16'd0;
#0 hBarSel_4_0_loc_0_fu_328 = 8'd0;
#0 zonePlateVAddr_loc_0_fu_324 = 16'd0;
#0 vBarSel_loc_0_fu_320 = 8'd0;
#0 hBarSel_0_loc_0_fu_316 = 8'd0;
#0 hdata_loc_0_fu_308 = 16'd0;
#0 vBarSel_2_loc_0_fu_304 = 8'd0;
#0 hBarSel_3_0_loc_0_fu_300 = 8'd0;
#0 rampVal_2_loc_0_fu_292 = 16'd0;
#0 vBarSel_3_loc_0_fu_288 = 8'd0;
#0 hBarSel_5_0_loc_0_fu_284 = 8'd0;
#0 y_fu_280 = 16'd0;
end

design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_ready),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_bckgndYUV_din),
    .bckgndYUV_num_data_valid(5'd0),
    .bckgndYUV_fifo_cap(5'd0),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_bckgndYUV_write),
    .rampVal_3_flag_0(rampVal_3_flag_0_reg_454),
    .hdata_flag_0(hdata_flag_0_reg_466),
    .rampVal_2_flag_0(rampVal_2_flag_0_reg_478),
    .width_val(width_val),
    .pix_5(pix_5_reg_1335),
    .pix(pix_reg_1330),
    .conv2_i_i_i266(conv2_i_i_i266_reg_1325),
    .conv2_i_i_i248_cast_cast(conv2_i_i_i248_cast_cast_reg_1315),
    .conv2_i_i_i_cast_cast(conv2_i_i_i_cast_cast_reg_1305),
    .conv2_i_i10_i264_cast_cast_cast_cast(conv2_i_i10_i264_cast_cast_cast_cast_reg_1320),
    .conv2_i_i10_i246(conv2_i_i10_i246_reg_1310),
    .conv2_i_i10_i241(conv2_i_i10_i241_reg_1300),
    .rampStart_1(rampStart_load_reg_1371),
    .ZplateHorContStart_val(ZplateHorContStart_val),
    .patternId_val(patternId_val),
    .cmp2_i236(cmp2_i236_reg_1295),
    .zext_ln1084(rampStart_load_reg_1371),
    .y(y_3_reg_1377),
    .colorFormat_val(colorFormat_val),
    .barWidth_cast(barWidth_reg_1340),
    .barWidth(barWidth_reg_1340),
    .ZplateHorContDelta_val(ZplateHorContDelta_val),
    .ZplateVerContStart_val(ZplateVerContStart_val),
    .cmp12_i(cmp12_i_reg_1400),
    .ZplateVerContDelta_val(ZplateVerContDelta_val),
    .sub_i_i_i(sub_i_i_i_reg_1356),
    .barWidthMinSamples(barWidthMinSamples_reg_1346),
    .cmp11_i(cmp11_i_reg_1405),
    .cmp_i370(cmp_i370_reg_1385),
    .sub35_i(sub35_i_reg_1361),
    .empty_36(trunc_ln565_reg_1410),
    .icmp(icmp_reg_1351),
    .empty(tmp_33_reg_1390),
    .colorSel(colorSel_reg_1395),
    .dpDynamicRange_val(dpDynamicRange_val),
    .dpYUVCoef_val(dpYUVCoef_val),
    .rampVal_3_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_flag_1_out),
    .rampVal_3_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_flag_1_out_ap_vld),
    .rampVal_3_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_new_1_out),
    .rampVal_3_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_new_1_out_ap_vld),
    .rampVal_3_loc_1_out_i(rampVal_3_loc_0_fu_336),
    .rampVal_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_loc_1_out_o),
    .rampVal_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_loc_1_out_o_ap_vld),
    .rampVal_loc_1_out_i(rampVal_loc_0_fu_332),
    .rampVal_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_loc_1_out_o),
    .rampVal_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_loc_1_out_o_ap_vld),
    .hBarSel_4_0_loc_1_out_i(hBarSel_4_0_loc_0_fu_328),
    .hBarSel_4_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0_loc_1_out_o),
    .hBarSel_4_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0_loc_1_out_o_ap_vld),
    .zonePlateVAddr_loc_1_out_i(zonePlateVAddr_loc_0_fu_324),
    .zonePlateVAddr_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr_loc_1_out_o),
    .zonePlateVAddr_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr_loc_1_out_o_ap_vld),
    .vBarSel_loc_1_out_i(vBarSel_loc_0_fu_320),
    .vBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_loc_1_out_o),
    .vBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_loc_1_out_o_ap_vld),
    .hBarSel_0_loc_1_out_i(hBarSel_0_loc_0_fu_316),
    .hBarSel_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0_loc_1_out_o),
    .hBarSel_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0_loc_1_out_o_ap_vld),
    .hdata_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_flag_1_out),
    .hdata_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_flag_1_out_ap_vld),
    .hdata_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_new_1_out),
    .hdata_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_new_1_out_ap_vld),
    .hdata_loc_1_out_i(hdata_loc_0_fu_308),
    .hdata_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_loc_1_out_o),
    .hdata_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_loc_1_out_o_ap_vld),
    .vBarSel_2_loc_1_out_i(vBarSel_2_loc_0_fu_304),
    .vBarSel_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2_loc_1_out_o),
    .vBarSel_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2_loc_1_out_o_ap_vld),
    .hBarSel_3_0_loc_1_out_i(hBarSel_3_0_loc_0_fu_300),
    .hBarSel_3_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0_loc_1_out_o),
    .hBarSel_3_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0_loc_1_out_o_ap_vld),
    .rampVal_2_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_flag_1_out),
    .rampVal_2_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_flag_1_out_ap_vld),
    .rampVal_2_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_new_1_out),
    .rampVal_2_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_new_1_out_ap_vld),
    .rampVal_2_loc_1_out_i(rampVal_2_loc_0_fu_292),
    .rampVal_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_loc_1_out_o),
    .rampVal_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_loc_1_out_o_ap_vld),
    .vBarSel_3_loc_1_out_i(vBarSel_3_loc_0_fu_288),
    .vBarSel_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_3_loc_1_out_o),
    .vBarSel_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_3_loc_1_out_o_ap_vld),
    .hBarSel_5_0_loc_1_out_i(hBarSel_5_0_loc_0_fu_284),
    .hBarSel_5_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0_loc_1_out_o),
    .hBarSel_5_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0_loc_1_out_o_ap_vld),
    .p_0_2_0_0_0217_out_i(p_0_2_0_0_0218_lcssa227_fu_276),
    .p_0_2_0_0_0217_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_2_0_0_0217_out_o),
    .p_0_2_0_0_0217_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_2_0_0_0217_out_o_ap_vld),
    .p_0_1_0_0_0215_out_i(p_0_1_0_0_0216_lcssa224_fu_272),
    .p_0_1_0_0_0215_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_1_0_0_0215_out_o),
    .p_0_1_0_0_0215_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_1_0_0_0215_out_o_ap_vld),
    .p_0_0_0_0_0213_out_i(p_0_0_0_0_0214_lcssa221_fu_268),
    .p_0_0_0_0_0213_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_0_0_0_0213_out_o),
    .p_0_0_0_0_0213_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_0_0_0_0213_out_o_ap_vld),
    .rampVal(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal),
    .rampVal_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_ap_vld),
    .hBarSel_4_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0),
    .hBarSel_4_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0_ap_vld),
    .s(s),
    .zonePlateVAddr(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr),
    .zonePlateVAddr_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr_ap_vld),
    .hBarSel_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0),
    .hBarSel_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0_ap_vld),
    .vBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel),
    .vBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_ap_vld),
    .hBarSel_3_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0),
    .hBarSel_3_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0_ap_vld),
    .vBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2),
    .vBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2_ap_vld),
    .hBarSel_5_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0),
    .hBarSel_5_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0_ap_vld),
    .vBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_1),
    .vBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln563_fu_995_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln563_fu_995_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hBarSel_0_loc_0_fu_316 <= zext_ln1545_fu_886_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_0_loc_0_fu_316 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hBarSel_3_0_loc_0_fu_300 <= zext_ln1687_fu_902_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_3_0_loc_0_fu_300 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hBarSel_4_0_loc_0_fu_328 <= hBarSel_4_0;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_4_0_loc_0_fu_328 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hBarSel_5_0_loc_0_fu_284 <= zext_ln563_fu_922_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_5_0_loc_0_fu_284 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hdata_flag_0_reg_466 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_flag_1_out;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hdata_flag_0_reg_466 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hdata_loc_0_fu_308 <= hdata;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hdata_loc_0_fu_308 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rampVal_2_flag_0_reg_478 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_flag_1_out;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_2_flag_0_reg_478 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_2_loc_0_fu_292 <= rampVal_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_2_loc_0_fu_292 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rampVal_3_flag_0_reg_454 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_flag_1_out;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_3_flag_0_reg_454 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_3_loc_0_fu_336 <= rampVal_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_3_loc_0_fu_336 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        rampVal_loc_0_fu_332 <= zext_ln1257_fu_862_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_loc_0_fu_332 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_2_loc_0_fu_304 <= vBarSel_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_2_loc_0_fu_304 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_3_loc_0_fu_288 <= zext_ln1775_fu_914_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_3_loc_0_fu_288 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_loc_0_fu_320 <= zext_ln1412_fu_878_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_loc_0_fu_320 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        y_fu_280 <= 16'd0;
    end else if (((icmp_ln563_fu_995_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_280 <= add_ln563_fu_1000_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        zonePlateVAddr_loc_0_fu_324 <= zonePlateVAddr;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        zonePlateVAddr_loc_0_fu_324 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        barWidthMinSamples_reg_1346 <= barWidthMinSamples_fu_782_p2;
        barWidth_reg_1340 <= {{add_i_fu_750_p2[13:3]}};
        cmp2_i236_reg_1295 <= cmp2_i236_fu_672_p2;
        conv2_i_i10_i241_reg_1300[5 : 0] <= conv2_i_i10_i241_fu_678_p3[5 : 0];
conv2_i_i10_i241_reg_1300[9 : 8] <= conv2_i_i10_i241_fu_678_p3[9 : 8];
conv2_i_i10_i241_reg_1300[11] <= conv2_i_i10_i241_fu_678_p3[11];
        conv2_i_i10_i246_reg_1310[4] <= conv2_i_i10_i246_fu_694_p3[4];
conv2_i_i10_i246_reg_1310[6] <= conv2_i_i10_i246_fu_694_p3[6];
conv2_i_i10_i246_reg_1310[8] <= conv2_i_i10_i246_fu_694_p3[8];
conv2_i_i10_i246_reg_1310[11] <= conv2_i_i10_i246_fu_694_p3[11];
        conv2_i_i10_i264_cast_cast_cast_cast_reg_1320[4] <= conv2_i_i10_i264_cast_cast_cast_cast_fu_710_p3[4];
conv2_i_i10_i264_cast_cast_cast_cast_reg_1320[6] <= conv2_i_i10_i264_cast_cast_cast_cast_fu_710_p3[6];
        conv2_i_i_i248_cast_cast_reg_1315[4] <= conv2_i_i_i248_cast_cast_fu_702_p3[4];
conv2_i_i_i248_cast_cast_reg_1315[6] <= conv2_i_i_i248_cast_cast_fu_702_p3[6];
conv2_i_i_i248_cast_cast_reg_1315[8] <= conv2_i_i_i248_cast_cast_fu_702_p3[8];
        conv2_i_i_i266_reg_1325[3 : 0] <= conv2_i_i_i266_fu_718_p3[3 : 0];
conv2_i_i_i266_reg_1325[6] <= conv2_i_i_i266_fu_718_p3[6];
conv2_i_i_i266_reg_1325[8] <= conv2_i_i_i266_fu_718_p3[8];
conv2_i_i_i266_reg_1325[11] <= conv2_i_i_i266_fu_718_p3[11];
        conv2_i_i_i_cast_cast_reg_1305[4] <= conv2_i_i_i_cast_cast_fu_686_p3[4];
        icmp_reg_1351 <= icmp_fu_812_p2;
        pix_5_reg_1335[10 : 0] <= pix_5_fu_734_p3[10 : 0];
        pix_reg_1330[11] <= pix_fu_726_p3[11];
        rampStart_load_reg_1371 <= rampStart;
        sub10_i_reg_1366 <= sub10_i_fu_844_p2;
        sub35_i_reg_1361 <= sub35_i_fu_838_p2;
        sub_i_i_i_reg_1356 <= sub_i_i_i_fu_832_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp11_i_reg_1405 <= cmp11_i_fu_1044_p2;
        cmp12_i_reg_1400 <= cmp12_i_fu_1037_p2;
        cmp_i370_reg_1385 <= cmp_i370_fu_1010_p2;
        colorSel_reg_1395 <= {{y_fu_280[7:6]}};
        tmp_33_reg_1390 <= y_fu_280[32'd5];
        trunc_ln565_reg_1410 <= trunc_ln565_fu_1050_p1;
        y_3_reg_1377 <= y_fu_280;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_3_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_4_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_5_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hBarSel_5_0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_995_p2 == 1'd1) & (ap_phi_mux_hdata_flag_0_phi_fu_470_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        hdata <= hdata_new_0_fu_312;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hdata_new_0_fu_312 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_hdata_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_0_0_0_0213_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_0_0_0_0214_lcssa221_fu_268 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_0_0_0_0213_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_1_0_0_0215_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_1_0_0_0216_lcssa224_fu_272 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_1_0_0_0215_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_2_0_0_0217_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_2_0_0_0218_lcssa227_fu_276 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_p_0_2_0_0_0217_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_995_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampStart <= add_ln750_fu_1063_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_995_p2 == 1'd1) & (ap_phi_mux_rampVal_3_flag_0_phi_fu_458_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampVal_1 <= rampVal_3_new_0_fu_340;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_995_p2 == 1'd1) & (ap_phi_mux_rampVal_2_flag_0_phi_fu_482_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampVal_2 <= rampVal_2_new_0_fu_296;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_2_new_0_fu_296 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_2_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_3_new_0_fu_340 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_rampVal_3_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_vBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_zonePlateVAddr;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln563_fu_995_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln563_fu_995_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_bckgndYUV_write;
    end else begin
        bckgndYUV_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val17_c14_blk_n = colorFormat_val17_c14_full_n;
    end else begin
        colorFormat_val17_c14_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        colorFormat_val17_c14_write = 1'b1;
    end else begin
        colorFormat_val17_c14_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val4_c12_blk_n = height_val4_c12_full_n;
    end else begin
        height_val4_c12_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        height_val4_c12_write = 1'b1;
    end else begin
        height_val4_c12_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val14_c_blk_n = motionSpeed_val14_c_full_n;
    end else begin
        motionSpeed_val14_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        motionSpeed_val14_c_write = 1'b1;
    end else begin
        motionSpeed_val14_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val7_c13_blk_n = width_val7_c13_full_n;
    end else begin
        width_val7_c13_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        width_val7_c13_write = 1'b1;
    end else begin
        width_val7_c13_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln563_fu_995_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add2_i_fu_766_p2 = (empty_fu_746_p1 + 14'd15);

assign add5_i_fu_796_p2 = (empty_98_fu_792_p1 + 14'd15);

assign add_i_fu_750_p2 = (empty_fu_746_p1 + 14'd7);

assign add_ln563_fu_1000_p2 = (y_fu_280 + 16'd1);

assign add_ln750_fu_1063_p2 = (rampStart + zext_ln750_fu_1060_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (colorFormat_val17_c14_full_n == 1'b0) | (motionSpeed_val14_c_full_n == 1'b0) | (width_val7_c13_full_n == 1'b0) | (height_val4_c12_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_phi_mux_hdata_flag_0_phi_fu_470_p4 = hdata_flag_0_reg_466;

assign ap_phi_mux_rampVal_2_flag_0_phi_fu_482_p4 = rampVal_2_flag_0_reg_478;

assign ap_phi_mux_rampVal_3_flag_0_phi_fu_458_p4 = rampVal_3_flag_0_reg_454;

assign barHeight_cast_fu_828_p1 = tmp_8_fu_818_p4;

assign barWidthMinSamples_fu_782_p2 = ($signed(p_cast_fu_772_p4) + $signed(10'd1023));

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_bckgndYUV_din;

assign cmp11_i_fu_1044_p2 = ((sub10_i_reg_1366 == zext_ln563_1_fu_1006_p1) ? 1'b1 : 1'b0);

assign cmp12_i_fu_1037_p2 = ((y_fu_280 != 16'd0) ? 1'b1 : 1'b0);

assign cmp2_i236_fu_672_p2 = ((colorFormat_val == 8'd0) ? 1'b1 : 1'b0);

assign cmp_i370_fu_1010_p2 = ((y_fu_280 == 16'd0) ? 1'b1 : 1'b0);

assign colorFormat_val17_c14_din = colorFormat_val;

assign conv2_i_i10_i241_fu_678_p3 = ((cmp2_i236_fu_672_p2[0:0] == 1'b1) ? 12'd4095 : 12'd1216);

assign conv2_i_i10_i246_fu_694_p3 = ((cmp2_i236_fu_672_p2[0:0] == 1'b1) ? 12'd0 : 12'd2384);

assign conv2_i_i10_i264_cast_cast_cast_cast_fu_710_p3 = ((cmp2_i236_fu_672_p2[0:0] == 1'b1) ? 7'd0 : 7'd80);

assign conv2_i_i_i248_cast_cast_fu_702_p3 = ((cmp2_i236_fu_672_p2[0:0] == 1'b1) ? 9'd0 : 9'd336);

assign conv2_i_i_i266_fu_718_p3 = ((cmp2_i236_fu_672_p2[0:0] == 1'b1) ? 12'd4095 : 12'd1712);

assign conv2_i_i_i_cast_cast_fu_686_p3 = ((cmp2_i236_fu_672_p2[0:0] == 1'b1) ? 5'd0 : 5'd16);

assign empty_98_fu_792_p1 = height_val[13:0];

assign empty_fu_746_p1 = width_val[13:0];

assign grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_490_ap_start_reg;

assign height_val4_c12_din = height_val;

assign height_val_cast15_fu_788_p1 = height_val;

assign icmp_fu_812_p2 = ((tmp_fu_802_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln563_fu_995_p2 = ((y_fu_280 == height_val) ? 1'b1 : 1'b0);

assign motionSpeed_val14_c_din = motionSpeed_val;

assign p_cast_fu_772_p4 = {{add2_i_fu_766_p2[13:4]}};

assign pix_5_fu_734_p3 = ((cmp2_i236_fu_672_p2[0:0] == 1'b1) ? 12'd4095 : 12'd2048);

assign pix_fu_726_p3 = ((cmp2_i236_fu_672_p2[0:0] == 1'b1) ? 12'd0 : 12'd2048);

assign sub10_i_fu_844_p2 = ($signed(height_val_cast15_fu_788_p1) + $signed(17'd131071));

assign sub35_i_fu_838_p2 = ($signed(width_val_cast14_fu_742_p1) + $signed(17'd131071));

assign sub_i_i_i_fu_832_p2 = ($signed(barHeight_cast_fu_828_p1) + $signed(11'd2047));

assign tmp_8_fu_818_p4 = {{add5_i_fu_796_p2[13:4]}};

assign tmp_fu_802_p4 = {{colorFormat_val[7:1]}};

assign trunc_ln565_fu_1050_p1 = y_fu_280[11:0];

assign width_val7_c13_din = width_val;

assign width_val_cast14_fu_742_p1 = width_val;

assign zext_ln1257_fu_862_p1 = rampVal;

assign zext_ln1412_fu_878_p1 = vBarSel;

assign zext_ln1545_fu_886_p1 = hBarSel_0;

assign zext_ln1687_fu_902_p1 = hBarSel_3_0;

assign zext_ln1775_fu_914_p1 = vBarSel_1;

assign zext_ln563_1_fu_1006_p1 = y_fu_280;

assign zext_ln563_fu_922_p1 = hBarSel_5_0;

assign zext_ln750_fu_1060_p1 = motionSpeed_val;

always @ (posedge ap_clk) begin
    conv2_i_i10_i241_reg_1300[7:6] <= 2'b11;
    conv2_i_i10_i241_reg_1300[10] <= 1'b1;
    conv2_i_i_i_cast_cast_reg_1305[3:0] <= 4'b0000;
    conv2_i_i10_i246_reg_1310[3:0] <= 4'b0000;
    conv2_i_i10_i246_reg_1310[5:5] <= 1'b0;
    conv2_i_i10_i246_reg_1310[7:7] <= 1'b0;
    conv2_i_i10_i246_reg_1310[10:9] <= 2'b00;
    conv2_i_i_i248_cast_cast_reg_1315[3:0] <= 4'b0000;
    conv2_i_i_i248_cast_cast_reg_1315[5:5] <= 1'b0;
    conv2_i_i_i248_cast_cast_reg_1315[7] <= 1'b0;
    conv2_i_i10_i264_cast_cast_cast_cast_reg_1320[3:0] <= 4'b0000;
    conv2_i_i10_i264_cast_cast_cast_cast_reg_1320[5] <= 1'b0;
    conv2_i_i_i266_reg_1325[5:4] <= 2'b11;
    conv2_i_i_i266_reg_1325[7:7] <= 1'b1;
    conv2_i_i_i266_reg_1325[10:9] <= 2'b11;
    pix_reg_1330[10:0] <= 11'b00000000000;
    pix_5_reg_1335[11] <= 1'b1;
end

endmodule //design_1_v_tpg_0_0_tpgBackground
