-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2023.2 (win64) Build 4029153 Fri Oct 13 20:14:34 MDT 2023
-- Date        : Mon May  6 17:58:09 2024
-- Host        : Vulcan running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               c:/Vulcan/Design_Tool/Board_Demo/VC707/versal_ibert/versal_ibert.gen/sources_1/bd/versal_ibert/ip/versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0/versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0_stub.vhdl
-- Design      : versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcvp1202-vsva2785-2MHP-e-S
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0 is
  Port ( 
    gt_ilo_reset : out STD_LOGIC;
    gt_pll_reset : out STD_LOGIC;
    ch0_txdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ch0_txbufstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_txpmaresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txpostcursor : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txprecursor : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txprecursor2 : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txprecursor3 : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txheader : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txsequence : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_gttxreset : out STD_LOGIC;
    ch0_txprogdivreset : out STD_LOGIC;
    ch0_txuserrdy : out STD_LOGIC;
    ch0_txphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txcominit : out STD_LOGIC;
    ch0_txcomsas : out STD_LOGIC;
    ch0_txcomwake : out STD_LOGIC;
    ch0_txdapicodeovrden : out STD_LOGIC;
    ch0_txdapicodereset : out STD_LOGIC;
    ch0_txdetectrx : out STD_LOGIC;
    ch0_txdlyalignreq : out STD_LOGIC;
    ch0_txelecidle : out STD_LOGIC;
    ch0_txinhibit : out STD_LOGIC;
    ch0_txmldchaindone : out STD_LOGIC;
    ch0_txmldchainreq : out STD_LOGIC;
    ch0_txoneszeros : out STD_LOGIC;
    ch0_txpausedelayalign : out STD_LOGIC;
    ch0_txpcsresetmask : out STD_LOGIC;
    ch0_txphalignreq : out STD_LOGIC;
    ch0_txphdlypd : out STD_LOGIC;
    ch0_txphdlyreset : out STD_LOGIC;
    ch0_txphsetinitreq : out STD_LOGIC;
    ch0_txphshift180 : out STD_LOGIC;
    ch0_txpicodeovrden : out STD_LOGIC;
    ch0_txpicodereset : out STD_LOGIC;
    ch0_txpippmen : out STD_LOGIC;
    ch0_txpisopd : out STD_LOGIC;
    ch0_txpolarity : out STD_LOGIC;
    ch0_txprbsforceerr : out STD_LOGIC;
    ch0_txswing : out STD_LOGIC;
    ch0_txsyncallin : out STD_LOGIC;
    ch0_tx10gstat : in STD_LOGIC;
    ch0_txcomfinish : in STD_LOGIC;
    ch0_txdccdone : in STD_LOGIC;
    ch0_txdlyalignerr : in STD_LOGIC;
    ch0_txdlyalignprog : in STD_LOGIC;
    ch0_txphaligndone : in STD_LOGIC;
    ch0_txphalignerr : in STD_LOGIC;
    ch0_txphalignoutrsvd : in STD_LOGIC;
    ch0_txphdlyresetdone : in STD_LOGIC;
    ch0_txphsetinitdone : in STD_LOGIC;
    ch0_txphshift180done : in STD_LOGIC;
    ch0_txsyncdone : in STD_LOGIC;
    ch0_txctrl0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_txctrl1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_txdeemph : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txmstreset : out STD_LOGIC;
    ch0_txmstdatapathreset : out STD_LOGIC;
    ch0_txmstresetdone : in STD_LOGIC;
    ch0_txmargin : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_txprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_txdiffctrl : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txpippmstepsize : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txmaincursor : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_txctrl2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txdataextendrsvd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txprogdivresetdone : in STD_LOGIC;
    ch0_txpmaresetdone : in STD_LOGIC;
    ch0_txresetdone : in STD_LOGIC;
    ch1_txdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ch1_txbufstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_txpmaresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txpostcursor : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txprecursor : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txprecursor2 : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txprecursor3 : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txheader : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txsequence : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_gttxreset : out STD_LOGIC;
    ch1_txprogdivreset : out STD_LOGIC;
    ch1_txuserrdy : out STD_LOGIC;
    ch1_txphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txcominit : out STD_LOGIC;
    ch1_txcomsas : out STD_LOGIC;
    ch1_txcomwake : out STD_LOGIC;
    ch1_txdapicodeovrden : out STD_LOGIC;
    ch1_txdapicodereset : out STD_LOGIC;
    ch1_txdetectrx : out STD_LOGIC;
    ch1_txdlyalignreq : out STD_LOGIC;
    ch1_txelecidle : out STD_LOGIC;
    ch1_txinhibit : out STD_LOGIC;
    ch1_txmldchaindone : out STD_LOGIC;
    ch1_txmldchainreq : out STD_LOGIC;
    ch1_txoneszeros : out STD_LOGIC;
    ch1_txpausedelayalign : out STD_LOGIC;
    ch1_txpcsresetmask : out STD_LOGIC;
    ch1_txphalignreq : out STD_LOGIC;
    ch1_txphdlypd : out STD_LOGIC;
    ch1_txphdlyreset : out STD_LOGIC;
    ch1_txphsetinitreq : out STD_LOGIC;
    ch1_txphshift180 : out STD_LOGIC;
    ch1_txpicodeovrden : out STD_LOGIC;
    ch1_txpicodereset : out STD_LOGIC;
    ch1_txpippmen : out STD_LOGIC;
    ch1_txpisopd : out STD_LOGIC;
    ch1_txpolarity : out STD_LOGIC;
    ch1_txprbsforceerr : out STD_LOGIC;
    ch1_txswing : out STD_LOGIC;
    ch1_txsyncallin : out STD_LOGIC;
    ch1_tx10gstat : in STD_LOGIC;
    ch1_txcomfinish : in STD_LOGIC;
    ch1_txdccdone : in STD_LOGIC;
    ch1_txdlyalignerr : in STD_LOGIC;
    ch1_txdlyalignprog : in STD_LOGIC;
    ch1_txphaligndone : in STD_LOGIC;
    ch1_txphalignerr : in STD_LOGIC;
    ch1_txphalignoutrsvd : in STD_LOGIC;
    ch1_txphdlyresetdone : in STD_LOGIC;
    ch1_txphsetinitdone : in STD_LOGIC;
    ch1_txphshift180done : in STD_LOGIC;
    ch1_txsyncdone : in STD_LOGIC;
    ch1_txctrl0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_txctrl1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_txdeemph : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txmstreset : out STD_LOGIC;
    ch1_txmstdatapathreset : out STD_LOGIC;
    ch1_txmstresetdone : in STD_LOGIC;
    ch1_txmargin : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_txprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_txdiffctrl : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txpippmstepsize : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txmaincursor : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_txctrl2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txdataextendrsvd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txprogdivresetdone : in STD_LOGIC;
    ch1_txpmaresetdone : in STD_LOGIC;
    ch1_txresetdone : in STD_LOGIC;
    ch2_txdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ch2_txbufstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_txpmaresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txpostcursor : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_txprecursor : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_txprecursor2 : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_txprecursor3 : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_txheader : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_txsequence : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch2_gttxreset : out STD_LOGIC;
    ch2_txprogdivreset : out STD_LOGIC;
    ch2_txuserrdy : out STD_LOGIC;
    ch2_txphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txcominit : out STD_LOGIC;
    ch2_txcomsas : out STD_LOGIC;
    ch2_txcomwake : out STD_LOGIC;
    ch2_txdapicodeovrden : out STD_LOGIC;
    ch2_txdapicodereset : out STD_LOGIC;
    ch2_txdetectrx : out STD_LOGIC;
    ch2_txdlyalignreq : out STD_LOGIC;
    ch2_txelecidle : out STD_LOGIC;
    ch2_txinhibit : out STD_LOGIC;
    ch2_txmldchaindone : out STD_LOGIC;
    ch2_txmldchainreq : out STD_LOGIC;
    ch2_txoneszeros : out STD_LOGIC;
    ch2_txpausedelayalign : out STD_LOGIC;
    ch2_txpcsresetmask : out STD_LOGIC;
    ch2_txphalignreq : out STD_LOGIC;
    ch2_txphdlypd : out STD_LOGIC;
    ch2_txphdlyreset : out STD_LOGIC;
    ch2_txphsetinitreq : out STD_LOGIC;
    ch2_txphshift180 : out STD_LOGIC;
    ch2_txpicodeovrden : out STD_LOGIC;
    ch2_txpicodereset : out STD_LOGIC;
    ch2_txpippmen : out STD_LOGIC;
    ch2_txpisopd : out STD_LOGIC;
    ch2_txpolarity : out STD_LOGIC;
    ch2_txprbsforceerr : out STD_LOGIC;
    ch2_txswing : out STD_LOGIC;
    ch2_txsyncallin : out STD_LOGIC;
    ch2_tx10gstat : in STD_LOGIC;
    ch2_txcomfinish : in STD_LOGIC;
    ch2_txdccdone : in STD_LOGIC;
    ch2_txdlyalignerr : in STD_LOGIC;
    ch2_txdlyalignprog : in STD_LOGIC;
    ch2_txphaligndone : in STD_LOGIC;
    ch2_txphalignerr : in STD_LOGIC;
    ch2_txphalignoutrsvd : in STD_LOGIC;
    ch2_txphdlyresetdone : in STD_LOGIC;
    ch2_txphsetinitdone : in STD_LOGIC;
    ch2_txphshift180done : in STD_LOGIC;
    ch2_txsyncdone : in STD_LOGIC;
    ch2_txctrl0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_txctrl1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_txdeemph : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txmstreset : out STD_LOGIC;
    ch2_txmstdatapathreset : out STD_LOGIC;
    ch2_txmstresetdone : in STD_LOGIC;
    ch2_txmargin : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_txprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch2_txdiffctrl : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_txpippmstepsize : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_txmaincursor : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch2_txctrl2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_txdataextendrsvd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_txrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_txprogdivresetdone : in STD_LOGIC;
    ch2_txpmaresetdone : in STD_LOGIC;
    ch2_txresetdone : in STD_LOGIC;
    ch3_txdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ch3_txbufstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_txpmaresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txpostcursor : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_txprecursor : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_txprecursor2 : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_txprecursor3 : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_txheader : out STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_txsequence : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch3_gttxreset : out STD_LOGIC;
    ch3_txprogdivreset : out STD_LOGIC;
    ch3_txuserrdy : out STD_LOGIC;
    ch3_txphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txcominit : out STD_LOGIC;
    ch3_txcomsas : out STD_LOGIC;
    ch3_txcomwake : out STD_LOGIC;
    ch3_txdapicodeovrden : out STD_LOGIC;
    ch3_txdapicodereset : out STD_LOGIC;
    ch3_txdetectrx : out STD_LOGIC;
    ch3_txdlyalignreq : out STD_LOGIC;
    ch3_txelecidle : out STD_LOGIC;
    ch3_txinhibit : out STD_LOGIC;
    ch3_txmldchaindone : out STD_LOGIC;
    ch3_txmldchainreq : out STD_LOGIC;
    ch3_txoneszeros : out STD_LOGIC;
    ch3_txpausedelayalign : out STD_LOGIC;
    ch3_txpcsresetmask : out STD_LOGIC;
    ch3_txphalignreq : out STD_LOGIC;
    ch3_txphdlypd : out STD_LOGIC;
    ch3_txphdlyreset : out STD_LOGIC;
    ch3_txphsetinitreq : out STD_LOGIC;
    ch3_txphshift180 : out STD_LOGIC;
    ch3_txpicodeovrden : out STD_LOGIC;
    ch3_txpicodereset : out STD_LOGIC;
    ch3_txpippmen : out STD_LOGIC;
    ch3_txpisopd : out STD_LOGIC;
    ch3_txpolarity : out STD_LOGIC;
    ch3_txprbsforceerr : out STD_LOGIC;
    ch3_txswing : out STD_LOGIC;
    ch3_txsyncallin : out STD_LOGIC;
    ch3_tx10gstat : in STD_LOGIC;
    ch3_txcomfinish : in STD_LOGIC;
    ch3_txdccdone : in STD_LOGIC;
    ch3_txdlyalignerr : in STD_LOGIC;
    ch3_txdlyalignprog : in STD_LOGIC;
    ch3_txphaligndone : in STD_LOGIC;
    ch3_txphalignerr : in STD_LOGIC;
    ch3_txphalignoutrsvd : in STD_LOGIC;
    ch3_txphdlyresetdone : in STD_LOGIC;
    ch3_txphsetinitdone : in STD_LOGIC;
    ch3_txphshift180done : in STD_LOGIC;
    ch3_txsyncdone : in STD_LOGIC;
    ch3_txctrl0 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_txctrl1 : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_txdeemph : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txmstreset : out STD_LOGIC;
    ch3_txmstdatapathreset : out STD_LOGIC;
    ch3_txmstresetdone : in STD_LOGIC;
    ch3_txmargin : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_txprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch3_txdiffctrl : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_txpippmstepsize : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_txmaincursor : out STD_LOGIC_VECTOR ( 6 downto 0 );
    ch3_txctrl2 : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_txdataextendrsvd : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_txrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_txprogdivresetdone : in STD_LOGIC;
    ch3_txpmaresetdone : in STD_LOGIC;
    ch3_txresetdone : in STD_LOGIC;
    ch0_rxdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    ch0_rxpcsresetmask : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxpmaresetmask : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxdatavalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxheader : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_rxgearboxslip : out STD_LOGIC;
    ch0_gtrxreset : out STD_LOGIC;
    ch0_rxprogdivreset : out STD_LOGIC;
    ch0_rxuserrdy : out STD_LOGIC;
    ch0_rxprogdivresetdone : in STD_LOGIC;
    ch0_rxpmaresetdone : in STD_LOGIC;
    ch0_rxresetdone : in STD_LOGIC;
    ch0_rx10gstat : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxbufstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxbyteisaligned : in STD_LOGIC;
    ch0_rxbyterealign : in STD_LOGIC;
    ch0_rxcdrhold : out STD_LOGIC;
    ch0_rxcdrlock : in STD_LOGIC;
    ch0_rxcdrovrden : out STD_LOGIC;
    ch0_rxcdrphdone : in STD_LOGIC;
    ch0_rxcdrreset : out STD_LOGIC;
    ch0_rxchanbondseq : in STD_LOGIC;
    ch0_rxchanisaligned : in STD_LOGIC;
    ch0_rxchanrealign : in STD_LOGIC;
    ch0_rxchbondi : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxchbondo : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_rxclkcorcnt : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxcominitdet : in STD_LOGIC;
    ch0_rxcommadet : in STD_LOGIC;
    ch0_rxcomsasdet : in STD_LOGIC;
    ch0_rxcomwakedet : in STD_LOGIC;
    ch0_rxctrl0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_rxctrl1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_rxctrl2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxctrl3 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxdapicodeovrden : out STD_LOGIC;
    ch0_rxdapicodereset : out STD_LOGIC;
    ch0_rxdataextendrsvd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxdccdone : in STD_LOGIC;
    ch0_rxdlyalignerr : in STD_LOGIC;
    ch0_rxdlyalignprog : in STD_LOGIC;
    ch0_rxdlyalignreq : out STD_LOGIC;
    ch0_rxelecidle : in STD_LOGIC;
    ch0_rxeqtraining : out STD_LOGIC;
    ch0_rxfinealigndone : in STD_LOGIC;
    ch0_rxheadervalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxlpmen : out STD_LOGIC;
    ch0_rxmldchaindone : out STD_LOGIC;
    ch0_rxmldchainreq : out STD_LOGIC;
    ch0_rxmlfinealignreq : out STD_LOGIC;
    ch0_rxoobreset : out STD_LOGIC;
    ch0_rxosintdone : in STD_LOGIC;
    ch0_rxosintstarted : in STD_LOGIC;
    ch0_rxosintstrobedone : in STD_LOGIC;
    ch0_rxosintstrobestarted : in STD_LOGIC;
    ch0_rxpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxphaligndone : in STD_LOGIC;
    ch0_rxphalignerr : in STD_LOGIC;
    ch0_rxphalignreq : out STD_LOGIC;
    ch0_rxphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxphdlypd : out STD_LOGIC;
    ch0_rxphdlyreset : out STD_LOGIC;
    ch0_rxphdlyresetdone : in STD_LOGIC;
    ch0_rxphsetinitdone : in STD_LOGIC;
    ch0_rxphsetinitreq : out STD_LOGIC;
    ch0_rxphshift180 : out STD_LOGIC;
    ch0_rxphshift180done : in STD_LOGIC;
    ch0_rxpolarity : out STD_LOGIC;
    ch0_rxprbscntreset : out STD_LOGIC;
    ch0_rxprbserr : in STD_LOGIC;
    ch0_rxprbslocked : in STD_LOGIC;
    ch0_rxprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_rxrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxmstreset : out STD_LOGIC;
    ch0_rxmstdatapathreset : out STD_LOGIC;
    ch0_rxmstresetdone : in STD_LOGIC;
    ch0_rxslide : out STD_LOGIC;
    ch0_rxsliderdy : in STD_LOGIC;
    ch0_rxstartofseq : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxsyncallin : out STD_LOGIC;
    ch0_rxsyncdone : in STD_LOGIC;
    ch0_rxtermination : out STD_LOGIC;
    ch0_rxvalid : in STD_LOGIC;
    ch0_cdrbmcdrreq : out STD_LOGIC;
    ch0_cdrfreqos : out STD_LOGIC;
    ch0_cdrincpctrl : out STD_LOGIC;
    ch0_cdrstepdir : out STD_LOGIC;
    ch0_cdrstepsq : out STD_LOGIC;
    ch0_cdrstepsx : out STD_LOGIC;
    ch0_cfokovrdfinish : out STD_LOGIC;
    ch0_cfokovrdpulse : out STD_LOGIC;
    ch0_cfokovrdstart : out STD_LOGIC;
    ch0_eyescanreset : out STD_LOGIC;
    ch0_eyescantrigger : out STD_LOGIC;
    ch0_eyescandataerror : in STD_LOGIC;
    ch0_cfokovrdrdy0 : in STD_LOGIC;
    ch0_cfokovrdrdy1 : in STD_LOGIC;
    ch1_rxdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    ch1_rxpcsresetmask : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxpmaresetmask : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxdatavalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxheader : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_rxgearboxslip : out STD_LOGIC;
    ch1_gtrxreset : out STD_LOGIC;
    ch1_rxprogdivreset : out STD_LOGIC;
    ch1_rxuserrdy : out STD_LOGIC;
    ch1_rxprogdivresetdone : in STD_LOGIC;
    ch1_rxpmaresetdone : in STD_LOGIC;
    ch1_rxresetdone : in STD_LOGIC;
    ch1_rx10gstat : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxbufstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxbyteisaligned : in STD_LOGIC;
    ch1_rxbyterealign : in STD_LOGIC;
    ch1_rxcdrhold : out STD_LOGIC;
    ch1_rxcdrlock : in STD_LOGIC;
    ch1_rxcdrovrden : out STD_LOGIC;
    ch1_rxcdrphdone : in STD_LOGIC;
    ch1_rxcdrreset : out STD_LOGIC;
    ch1_rxchanbondseq : in STD_LOGIC;
    ch1_rxchanisaligned : in STD_LOGIC;
    ch1_rxchanrealign : in STD_LOGIC;
    ch1_rxchbondi : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxchbondo : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_rxclkcorcnt : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxcominitdet : in STD_LOGIC;
    ch1_rxcommadet : in STD_LOGIC;
    ch1_rxcomsasdet : in STD_LOGIC;
    ch1_rxcomwakedet : in STD_LOGIC;
    ch1_rxctrl0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_rxctrl1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_rxctrl2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxctrl3 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxdapicodeovrden : out STD_LOGIC;
    ch1_rxdapicodereset : out STD_LOGIC;
    ch1_rxdataextendrsvd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxdccdone : in STD_LOGIC;
    ch1_rxdlyalignerr : in STD_LOGIC;
    ch1_rxdlyalignprog : in STD_LOGIC;
    ch1_rxdlyalignreq : out STD_LOGIC;
    ch1_rxelecidle : in STD_LOGIC;
    ch1_rxeqtraining : out STD_LOGIC;
    ch1_rxfinealigndone : in STD_LOGIC;
    ch1_rxheadervalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxlpmen : out STD_LOGIC;
    ch1_rxmldchaindone : out STD_LOGIC;
    ch1_rxmldchainreq : out STD_LOGIC;
    ch1_rxmlfinealignreq : out STD_LOGIC;
    ch1_rxoobreset : out STD_LOGIC;
    ch1_rxosintdone : in STD_LOGIC;
    ch1_rxosintstarted : in STD_LOGIC;
    ch1_rxosintstrobedone : in STD_LOGIC;
    ch1_rxosintstrobestarted : in STD_LOGIC;
    ch1_rxpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxphaligndone : in STD_LOGIC;
    ch1_rxphalignerr : in STD_LOGIC;
    ch1_rxphalignreq : out STD_LOGIC;
    ch1_rxphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxphdlypd : out STD_LOGIC;
    ch1_rxphdlyreset : out STD_LOGIC;
    ch1_rxphdlyresetdone : in STD_LOGIC;
    ch1_rxphsetinitdone : in STD_LOGIC;
    ch1_rxphsetinitreq : out STD_LOGIC;
    ch1_rxphshift180 : out STD_LOGIC;
    ch1_rxphshift180done : in STD_LOGIC;
    ch1_rxpolarity : out STD_LOGIC;
    ch1_rxprbscntreset : out STD_LOGIC;
    ch1_rxprbserr : in STD_LOGIC;
    ch1_rxprbslocked : in STD_LOGIC;
    ch1_rxprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_rxrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxmstreset : out STD_LOGIC;
    ch1_rxmstdatapathreset : out STD_LOGIC;
    ch1_rxmstresetdone : in STD_LOGIC;
    ch1_rxslide : out STD_LOGIC;
    ch1_rxsliderdy : in STD_LOGIC;
    ch1_rxstartofseq : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxsyncallin : out STD_LOGIC;
    ch1_rxsyncdone : in STD_LOGIC;
    ch1_rxtermination : out STD_LOGIC;
    ch1_rxvalid : in STD_LOGIC;
    ch1_cdrbmcdrreq : out STD_LOGIC;
    ch1_cdrfreqos : out STD_LOGIC;
    ch1_cdrincpctrl : out STD_LOGIC;
    ch1_cdrstepdir : out STD_LOGIC;
    ch1_cdrstepsq : out STD_LOGIC;
    ch1_cdrstepsx : out STD_LOGIC;
    ch1_cfokovrdfinish : out STD_LOGIC;
    ch1_cfokovrdpulse : out STD_LOGIC;
    ch1_cfokovrdstart : out STD_LOGIC;
    ch1_eyescanreset : out STD_LOGIC;
    ch1_eyescantrigger : out STD_LOGIC;
    ch1_eyescandataerror : in STD_LOGIC;
    ch1_cfokovrdrdy0 : in STD_LOGIC;
    ch1_cfokovrdrdy1 : in STD_LOGIC;
    ch2_rxdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    ch2_rxpcsresetmask : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_rxpmaresetmask : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxdatavalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxheader : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_rxgearboxslip : out STD_LOGIC;
    ch2_gtrxreset : out STD_LOGIC;
    ch2_rxprogdivreset : out STD_LOGIC;
    ch2_rxuserrdy : out STD_LOGIC;
    ch2_rxprogdivresetdone : in STD_LOGIC;
    ch2_rxpmaresetdone : in STD_LOGIC;
    ch2_rxresetdone : in STD_LOGIC;
    ch2_rx10gstat : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxbufstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_rxbyteisaligned : in STD_LOGIC;
    ch2_rxbyterealign : in STD_LOGIC;
    ch2_rxcdrhold : out STD_LOGIC;
    ch2_rxcdrlock : in STD_LOGIC;
    ch2_rxcdrovrden : out STD_LOGIC;
    ch2_rxcdrphdone : in STD_LOGIC;
    ch2_rxcdrreset : out STD_LOGIC;
    ch2_rxchanbondseq : in STD_LOGIC;
    ch2_rxchanisaligned : in STD_LOGIC;
    ch2_rxchanrealign : in STD_LOGIC;
    ch2_rxchbondi : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_rxchbondo : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_rxclkcorcnt : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxcominitdet : in STD_LOGIC;
    ch2_rxcommadet : in STD_LOGIC;
    ch2_rxcomsasdet : in STD_LOGIC;
    ch2_rxcomwakedet : in STD_LOGIC;
    ch2_rxctrl0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_rxctrl1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_rxctrl2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxctrl3 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxdapicodeovrden : out STD_LOGIC;
    ch2_rxdapicodereset : out STD_LOGIC;
    ch2_rxdataextendrsvd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxdccdone : in STD_LOGIC;
    ch2_rxdlyalignerr : in STD_LOGIC;
    ch2_rxdlyalignprog : in STD_LOGIC;
    ch2_rxdlyalignreq : out STD_LOGIC;
    ch2_rxelecidle : in STD_LOGIC;
    ch2_rxeqtraining : out STD_LOGIC;
    ch2_rxfinealigndone : in STD_LOGIC;
    ch2_rxheadervalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxlpmen : out STD_LOGIC;
    ch2_rxmldchaindone : out STD_LOGIC;
    ch2_rxmldchainreq : out STD_LOGIC;
    ch2_rxmlfinealignreq : out STD_LOGIC;
    ch2_rxoobreset : out STD_LOGIC;
    ch2_rxosintdone : in STD_LOGIC;
    ch2_rxosintstarted : in STD_LOGIC;
    ch2_rxosintstrobedone : in STD_LOGIC;
    ch2_rxosintstrobestarted : in STD_LOGIC;
    ch2_rxpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxphaligndone : in STD_LOGIC;
    ch2_rxphalignerr : in STD_LOGIC;
    ch2_rxphalignreq : out STD_LOGIC;
    ch2_rxphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxphdlypd : out STD_LOGIC;
    ch2_rxphdlyreset : out STD_LOGIC;
    ch2_rxphdlyresetdone : in STD_LOGIC;
    ch2_rxphsetinitdone : in STD_LOGIC;
    ch2_rxphsetinitreq : out STD_LOGIC;
    ch2_rxphshift180 : out STD_LOGIC;
    ch2_rxphshift180done : in STD_LOGIC;
    ch2_rxpolarity : out STD_LOGIC;
    ch2_rxprbscntreset : out STD_LOGIC;
    ch2_rxprbserr : in STD_LOGIC;
    ch2_rxprbslocked : in STD_LOGIC;
    ch2_rxprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch2_rxrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxmstreset : out STD_LOGIC;
    ch2_rxmstdatapathreset : out STD_LOGIC;
    ch2_rxmstresetdone : in STD_LOGIC;
    ch2_rxslide : out STD_LOGIC;
    ch2_rxsliderdy : in STD_LOGIC;
    ch2_rxstartofseq : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_rxsyncallin : out STD_LOGIC;
    ch2_rxsyncdone : in STD_LOGIC;
    ch2_rxtermination : out STD_LOGIC;
    ch2_rxvalid : in STD_LOGIC;
    ch2_cdrbmcdrreq : out STD_LOGIC;
    ch2_cdrfreqos : out STD_LOGIC;
    ch2_cdrincpctrl : out STD_LOGIC;
    ch2_cdrstepdir : out STD_LOGIC;
    ch2_cdrstepsq : out STD_LOGIC;
    ch2_cdrstepsx : out STD_LOGIC;
    ch2_cfokovrdfinish : out STD_LOGIC;
    ch2_cfokovrdpulse : out STD_LOGIC;
    ch2_cfokovrdstart : out STD_LOGIC;
    ch2_eyescanreset : out STD_LOGIC;
    ch2_eyescantrigger : out STD_LOGIC;
    ch2_eyescandataerror : in STD_LOGIC;
    ch2_cfokovrdrdy0 : in STD_LOGIC;
    ch2_cfokovrdrdy1 : in STD_LOGIC;
    ch3_rxdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    ch3_rxpcsresetmask : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_rxpmaresetmask : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxdatavalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxheader : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_rxgearboxslip : out STD_LOGIC;
    ch3_gtrxreset : out STD_LOGIC;
    ch3_rxprogdivreset : out STD_LOGIC;
    ch3_rxuserrdy : out STD_LOGIC;
    ch3_rxprogdivresetdone : in STD_LOGIC;
    ch3_rxpmaresetdone : in STD_LOGIC;
    ch3_rxresetdone : in STD_LOGIC;
    ch3_rx10gstat : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxbufstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_rxbyteisaligned : in STD_LOGIC;
    ch3_rxbyterealign : in STD_LOGIC;
    ch3_rxcdrhold : out STD_LOGIC;
    ch3_rxcdrlock : in STD_LOGIC;
    ch3_rxcdrovrden : out STD_LOGIC;
    ch3_rxcdrphdone : in STD_LOGIC;
    ch3_rxcdrreset : out STD_LOGIC;
    ch3_rxchanbondseq : in STD_LOGIC;
    ch3_rxchanisaligned : in STD_LOGIC;
    ch3_rxchanrealign : in STD_LOGIC;
    ch3_rxchbondi : out STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_rxchbondo : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_rxclkcorcnt : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxcominitdet : in STD_LOGIC;
    ch3_rxcommadet : in STD_LOGIC;
    ch3_rxcomsasdet : in STD_LOGIC;
    ch3_rxcomwakedet : in STD_LOGIC;
    ch3_rxctrl0 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_rxctrl1 : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_rxctrl2 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxctrl3 : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxdapicodeovrden : out STD_LOGIC;
    ch3_rxdapicodereset : out STD_LOGIC;
    ch3_rxdataextendrsvd : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxdccdone : in STD_LOGIC;
    ch3_rxdlyalignerr : in STD_LOGIC;
    ch3_rxdlyalignprog : in STD_LOGIC;
    ch3_rxdlyalignreq : out STD_LOGIC;
    ch3_rxelecidle : in STD_LOGIC;
    ch3_rxeqtraining : out STD_LOGIC;
    ch3_rxfinealigndone : in STD_LOGIC;
    ch3_rxheadervalid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxlpmen : out STD_LOGIC;
    ch3_rxmldchaindone : out STD_LOGIC;
    ch3_rxmldchainreq : out STD_LOGIC;
    ch3_rxmlfinealignreq : out STD_LOGIC;
    ch3_rxoobreset : out STD_LOGIC;
    ch3_rxosintdone : in STD_LOGIC;
    ch3_rxosintstarted : in STD_LOGIC;
    ch3_rxosintstrobedone : in STD_LOGIC;
    ch3_rxosintstrobestarted : in STD_LOGIC;
    ch3_rxpd : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxphaligndone : in STD_LOGIC;
    ch3_rxphalignerr : in STD_LOGIC;
    ch3_rxphalignreq : out STD_LOGIC;
    ch3_rxphalignresetmask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxphdlypd : out STD_LOGIC;
    ch3_rxphdlyreset : out STD_LOGIC;
    ch3_rxphdlyresetdone : in STD_LOGIC;
    ch3_rxphsetinitdone : in STD_LOGIC;
    ch3_rxphsetinitreq : out STD_LOGIC;
    ch3_rxphshift180 : out STD_LOGIC;
    ch3_rxphshift180done : in STD_LOGIC;
    ch3_rxpolarity : out STD_LOGIC;
    ch3_rxprbscntreset : out STD_LOGIC;
    ch3_rxprbserr : in STD_LOGIC;
    ch3_rxprbslocked : in STD_LOGIC;
    ch3_rxprbssel : out STD_LOGIC_VECTOR ( 3 downto 0 );
    ch3_rxrate : out STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxresetmode : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxmstreset : out STD_LOGIC;
    ch3_rxmstdatapathreset : out STD_LOGIC;
    ch3_rxmstresetdone : in STD_LOGIC;
    ch3_rxslide : out STD_LOGIC;
    ch3_rxsliderdy : in STD_LOGIC;
    ch3_rxstartofseq : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxstatus : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_rxsyncallin : out STD_LOGIC;
    ch3_rxsyncdone : in STD_LOGIC;
    ch3_rxtermination : out STD_LOGIC;
    ch3_rxvalid : in STD_LOGIC;
    ch3_cdrbmcdrreq : out STD_LOGIC;
    ch3_cdrfreqos : out STD_LOGIC;
    ch3_cdrincpctrl : out STD_LOGIC;
    ch3_cdrstepdir : out STD_LOGIC;
    ch3_cdrstepsq : out STD_LOGIC;
    ch3_cdrstepsx : out STD_LOGIC;
    ch3_cfokovrdfinish : out STD_LOGIC;
    ch3_cfokovrdpulse : out STD_LOGIC;
    ch3_cfokovrdstart : out STD_LOGIC;
    ch3_eyescanreset : out STD_LOGIC;
    ch3_eyescantrigger : out STD_LOGIC;
    ch3_eyescandataerror : in STD_LOGIC;
    ch3_cfokovrdrdy0 : in STD_LOGIC;
    ch3_cfokovrdrdy1 : in STD_LOGIC;
    gt_txusrclk : in STD_LOGIC;
    gt_rxusrclk : in STD_LOGIC;
    apb3clk : in STD_LOGIC;
    gtpowergood : in STD_LOGIC;
    gt_lcpll_lock : in STD_LOGIC;
    gt_rpll_lock : in STD_LOGIC;
    ch_phystatus_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ilo_resetdone : in STD_LOGIC;
    tx_clr_out : out STD_LOGIC;
    tx_clrb_leaf_out : out STD_LOGIC;
    rx_clr_out : out STD_LOGIC;
    rx_clrb_leaf_out : out STD_LOGIC;
    rx_resetdone_out : out STD_LOGIC;
    tx_resetdone_out : out STD_LOGIC;
    txusrclk_out : out STD_LOGIC;
    rxusrclk_out : out STD_LOGIC;
    link_status_out : out STD_LOGIC;
    gpio_enable : in STD_LOGIC;
    rpll_lock_out : out STD_LOGIC;
    lcpll_lock_out : out STD_LOGIC;
    pcie_rstb : out STD_LOGIC;
    gpi_out : out STD_LOGIC;
    gpo_in : in STD_LOGIC;
    gtreset_in : in STD_LOGIC;
    rate_sel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    reset_mask : out STD_LOGIC_VECTOR ( 1 downto 0 );
    reset_tx_pll_and_datapath_in : in STD_LOGIC;
    reset_tx_datapath_in : in STD_LOGIC;
    reset_rx_pll_and_datapath_in : in STD_LOGIC;
    reset_rx_datapath_in : in STD_LOGIC
  );

end versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0;

architecture stub of versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "gt_ilo_reset,gt_pll_reset,ch0_txdata[255:0],ch0_txbufstatus[2:0],ch0_txpmaresetmask[1:0],ch0_txpostcursor[5:0],ch0_txprecursor[5:0],ch0_txprecursor2[5:0],ch0_txprecursor3[5:0],ch0_txheader[5:0],ch0_txsequence[6:0],ch0_gttxreset,ch0_txprogdivreset,ch0_txuserrdy,ch0_txphalignresetmask[1:0],ch0_txcominit,ch0_txcomsas,ch0_txcomwake,ch0_txdapicodeovrden,ch0_txdapicodereset,ch0_txdetectrx,ch0_txdlyalignreq,ch0_txelecidle,ch0_txinhibit,ch0_txmldchaindone,ch0_txmldchainreq,ch0_txoneszeros,ch0_txpausedelayalign,ch0_txpcsresetmask,ch0_txphalignreq,ch0_txphdlypd,ch0_txphdlyreset,ch0_txphsetinitreq,ch0_txphshift180,ch0_txpicodeovrden,ch0_txpicodereset,ch0_txpippmen,ch0_txpisopd,ch0_txpolarity,ch0_txprbsforceerr,ch0_txswing,ch0_txsyncallin,ch0_tx10gstat,ch0_txcomfinish,ch0_txdccdone,ch0_txdlyalignerr,ch0_txdlyalignprog,ch0_txphaligndone,ch0_txphalignerr,ch0_txphalignoutrsvd,ch0_txphdlyresetdone,ch0_txphsetinitdone,ch0_txphshift180done,ch0_txsyncdone,ch0_txctrl0[15:0],ch0_txctrl1[15:0],ch0_txdeemph[1:0],ch0_txpd[1:0],ch0_txresetmode[1:0],ch0_txmstreset,ch0_txmstdatapathreset,ch0_txmstresetdone,ch0_txmargin[2:0],ch0_txprbssel[3:0],ch0_txdiffctrl[4:0],ch0_txpippmstepsize[4:0],ch0_txmaincursor[6:0],ch0_txctrl2[7:0],ch0_txdataextendrsvd[7:0],ch0_txrate[7:0],ch0_txprogdivresetdone,ch0_txpmaresetdone,ch0_txresetdone,ch1_txdata[255:0],ch1_txbufstatus[2:0],ch1_txpmaresetmask[1:0],ch1_txpostcursor[5:0],ch1_txprecursor[5:0],ch1_txprecursor2[5:0],ch1_txprecursor3[5:0],ch1_txheader[5:0],ch1_txsequence[6:0],ch1_gttxreset,ch1_txprogdivreset,ch1_txuserrdy,ch1_txphalignresetmask[1:0],ch1_txcominit,ch1_txcomsas,ch1_txcomwake,ch1_txdapicodeovrden,ch1_txdapicodereset,ch1_txdetectrx,ch1_txdlyalignreq,ch1_txelecidle,ch1_txinhibit,ch1_txmldchaindone,ch1_txmldchainreq,ch1_txoneszeros,ch1_txpausedelayalign,ch1_txpcsresetmask,ch1_txphalignreq,ch1_txphdlypd,ch1_txphdlyreset,ch1_txphsetinitreq,ch1_txphshift180,ch1_txpicodeovrden,ch1_txpicodereset,ch1_txpippmen,ch1_txpisopd,ch1_txpolarity,ch1_txprbsforceerr,ch1_txswing,ch1_txsyncallin,ch1_tx10gstat,ch1_txcomfinish,ch1_txdccdone,ch1_txdlyalignerr,ch1_txdlyalignprog,ch1_txphaligndone,ch1_txphalignerr,ch1_txphalignoutrsvd,ch1_txphdlyresetdone,ch1_txphsetinitdone,ch1_txphshift180done,ch1_txsyncdone,ch1_txctrl0[15:0],ch1_txctrl1[15:0],ch1_txdeemph[1:0],ch1_txpd[1:0],ch1_txresetmode[1:0],ch1_txmstreset,ch1_txmstdatapathreset,ch1_txmstresetdone,ch1_txmargin[2:0],ch1_txprbssel[3:0],ch1_txdiffctrl[4:0],ch1_txpippmstepsize[4:0],ch1_txmaincursor[6:0],ch1_txctrl2[7:0],ch1_txdataextendrsvd[7:0],ch1_txrate[7:0],ch1_txprogdivresetdone,ch1_txpmaresetdone,ch1_txresetdone,ch2_txdata[255:0],ch2_txbufstatus[2:0],ch2_txpmaresetmask[1:0],ch2_txpostcursor[5:0],ch2_txprecursor[5:0],ch2_txprecursor2[5:0],ch2_txprecursor3[5:0],ch2_txheader[5:0],ch2_txsequence[6:0],ch2_gttxreset,ch2_txprogdivreset,ch2_txuserrdy,ch2_txphalignresetmask[1:0],ch2_txcominit,ch2_txcomsas,ch2_txcomwake,ch2_txdapicodeovrden,ch2_txdapicodereset,ch2_txdetectrx,ch2_txdlyalignreq,ch2_txelecidle,ch2_txinhibit,ch2_txmldchaindone,ch2_txmldchainreq,ch2_txoneszeros,ch2_txpausedelayalign,ch2_txpcsresetmask,ch2_txphalignreq,ch2_txphdlypd,ch2_txphdlyreset,ch2_txphsetinitreq,ch2_txphshift180,ch2_txpicodeovrden,ch2_txpicodereset,ch2_txpippmen,ch2_txpisopd,ch2_txpolarity,ch2_txprbsforceerr,ch2_txswing,ch2_txsyncallin,ch2_tx10gstat,ch2_txcomfinish,ch2_txdccdone,ch2_txdlyalignerr,ch2_txdlyalignprog,ch2_txphaligndone,ch2_txphalignerr,ch2_txphalignoutrsvd,ch2_txphdlyresetdone,ch2_txphsetinitdone,ch2_txphshift180done,ch2_txsyncdone,ch2_txctrl0[15:0],ch2_txctrl1[15:0],ch2_txdeemph[1:0],ch2_txpd[1:0],ch2_txresetmode[1:0],ch2_txmstreset,ch2_txmstdatapathreset,ch2_txmstresetdone,ch2_txmargin[2:0],ch2_txprbssel[3:0],ch2_txdiffctrl[4:0],ch2_txpippmstepsize[4:0],ch2_txmaincursor[6:0],ch2_txctrl2[7:0],ch2_txdataextendrsvd[7:0],ch2_txrate[7:0],ch2_txprogdivresetdone,ch2_txpmaresetdone,ch2_txresetdone,ch3_txdata[255:0],ch3_txbufstatus[2:0],ch3_txpmaresetmask[1:0],ch3_txpostcursor[5:0],ch3_txprecursor[5:0],ch3_txprecursor2[5:0],ch3_txprecursor3[5:0],ch3_txheader[5:0],ch3_txsequence[6:0],ch3_gttxreset,ch3_txprogdivreset,ch3_txuserrdy,ch3_txphalignresetmask[1:0],ch3_txcominit,ch3_txcomsas,ch3_txcomwake,ch3_txdapicodeovrden,ch3_txdapicodereset,ch3_txdetectrx,ch3_txdlyalignreq,ch3_txelecidle,ch3_txinhibit,ch3_txmldchaindone,ch3_txmldchainreq,ch3_txoneszeros,ch3_txpausedelayalign,ch3_txpcsresetmask,ch3_txphalignreq,ch3_txphdlypd,ch3_txphdlyreset,ch3_txphsetinitreq,ch3_txphshift180,ch3_txpicodeovrden,ch3_txpicodereset,ch3_txpippmen,ch3_txpisopd,ch3_txpolarity,ch3_txprbsforceerr,ch3_txswing,ch3_txsyncallin,ch3_tx10gstat,ch3_txcomfinish,ch3_txdccdone,ch3_txdlyalignerr,ch3_txdlyalignprog,ch3_txphaligndone,ch3_txphalignerr,ch3_txphalignoutrsvd,ch3_txphdlyresetdone,ch3_txphsetinitdone,ch3_txphshift180done,ch3_txsyncdone,ch3_txctrl0[15:0],ch3_txctrl1[15:0],ch3_txdeemph[1:0],ch3_txpd[1:0],ch3_txresetmode[1:0],ch3_txmstreset,ch3_txmstdatapathreset,ch3_txmstresetdone,ch3_txmargin[2:0],ch3_txprbssel[3:0],ch3_txdiffctrl[4:0],ch3_txpippmstepsize[4:0],ch3_txmaincursor[6:0],ch3_txctrl2[7:0],ch3_txdataextendrsvd[7:0],ch3_txrate[7:0],ch3_txprogdivresetdone,ch3_txpmaresetdone,ch3_txresetdone,ch0_rxdata[255:0],ch0_rxpcsresetmask[2:0],ch0_rxpmaresetmask[7:0],ch0_rxdatavalid[1:0],ch0_rxheader[5:0],ch0_rxgearboxslip,ch0_gtrxreset,ch0_rxprogdivreset,ch0_rxuserrdy,ch0_rxprogdivresetdone,ch0_rxpmaresetdone,ch0_rxresetdone,ch0_rx10gstat[7:0],ch0_rxbufstatus[2:0],ch0_rxbyteisaligned,ch0_rxbyterealign,ch0_rxcdrhold,ch0_rxcdrlock,ch0_rxcdrovrden,ch0_rxcdrphdone,ch0_rxcdrreset,ch0_rxchanbondseq,ch0_rxchanisaligned,ch0_rxchanrealign,ch0_rxchbondi[4:0],ch0_rxchbondo[4:0],ch0_rxclkcorcnt[1:0],ch0_rxcominitdet,ch0_rxcommadet,ch0_rxcomsasdet,ch0_rxcomwakedet,ch0_rxctrl0[15:0],ch0_rxctrl1[15:0],ch0_rxctrl2[7:0],ch0_rxctrl3[7:0],ch0_rxdapicodeovrden,ch0_rxdapicodereset,ch0_rxdataextendrsvd[7:0],ch0_rxdccdone,ch0_rxdlyalignerr,ch0_rxdlyalignprog,ch0_rxdlyalignreq,ch0_rxelecidle,ch0_rxeqtraining,ch0_rxfinealigndone,ch0_rxheadervalid[1:0],ch0_rxlpmen,ch0_rxmldchaindone,ch0_rxmldchainreq,ch0_rxmlfinealignreq,ch0_rxoobreset,ch0_rxosintdone,ch0_rxosintstarted,ch0_rxosintstrobedone,ch0_rxosintstrobestarted,ch0_rxpd[1:0],ch0_rxphaligndone,ch0_rxphalignerr,ch0_rxphalignreq,ch0_rxphalignresetmask[1:0],ch0_rxphdlypd,ch0_rxphdlyreset,ch0_rxphdlyresetdone,ch0_rxphsetinitdone,ch0_rxphsetinitreq,ch0_rxphshift180,ch0_rxphshift180done,ch0_rxpolarity,ch0_rxprbscntreset,ch0_rxprbserr,ch0_rxprbslocked,ch0_rxprbssel[3:0],ch0_rxrate[7:0],ch0_rxresetmode[1:0],ch0_rxmstreset,ch0_rxmstdatapathreset,ch0_rxmstresetdone,ch0_rxslide,ch0_rxsliderdy,ch0_rxstartofseq[1:0],ch0_rxstatus[2:0],ch0_rxsyncallin,ch0_rxsyncdone,ch0_rxtermination,ch0_rxvalid,ch0_cdrbmcdrreq,ch0_cdrfreqos,ch0_cdrincpctrl,ch0_cdrstepdir,ch0_cdrstepsq,ch0_cdrstepsx,ch0_cfokovrdfinish,ch0_cfokovrdpulse,ch0_cfokovrdstart,ch0_eyescanreset,ch0_eyescantrigger,ch0_eyescandataerror,ch0_cfokovrdrdy0,ch0_cfokovrdrdy1,ch1_rxdata[255:0],ch1_rxpcsresetmask[2:0],ch1_rxpmaresetmask[7:0],ch1_rxdatavalid[1:0],ch1_rxheader[5:0],ch1_rxgearboxslip,ch1_gtrxreset,ch1_rxprogdivreset,ch1_rxuserrdy,ch1_rxprogdivresetdone,ch1_rxpmaresetdone,ch1_rxresetdone,ch1_rx10gstat[7:0],ch1_rxbufstatus[2:0],ch1_rxbyteisaligned,ch1_rxbyterealign,ch1_rxcdrhold,ch1_rxcdrlock,ch1_rxcdrovrden,ch1_rxcdrphdone,ch1_rxcdrreset,ch1_rxchanbondseq,ch1_rxchanisaligned,ch1_rxchanrealign,ch1_rxchbondi[4:0],ch1_rxchbondo[4:0],ch1_rxclkcorcnt[1:0],ch1_rxcominitdet,ch1_rxcommadet,ch1_rxcomsasdet,ch1_rxcomwakedet,ch1_rxctrl0[15:0],ch1_rxctrl1[15:0],ch1_rxctrl2[7:0],ch1_rxctrl3[7:0],ch1_rxdapicodeovrden,ch1_rxdapicodereset,ch1_rxdataextendrsvd[7:0],ch1_rxdccdone,ch1_rxdlyalignerr,ch1_rxdlyalignprog,ch1_rxdlyalignreq,ch1_rxelecidle,ch1_rxeqtraining,ch1_rxfinealigndone,ch1_rxheadervalid[1:0],ch1_rxlpmen,ch1_rxmldchaindone,ch1_rxmldchainreq,ch1_rxmlfinealignreq,ch1_rxoobreset,ch1_rxosintdone,ch1_rxosintstarted,ch1_rxosintstrobedone,ch1_rxosintstrobestarted,ch1_rxpd[1:0],ch1_rxphaligndone,ch1_rxphalignerr,ch1_rxphalignreq,ch1_rxphalignresetmask[1:0],ch1_rxphdlypd,ch1_rxphdlyreset,ch1_rxphdlyresetdone,ch1_rxphsetinitdone,ch1_rxphsetinitreq,ch1_rxphshift180,ch1_rxphshift180done,ch1_rxpolarity,ch1_rxprbscntreset,ch1_rxprbserr,ch1_rxprbslocked,ch1_rxprbssel[3:0],ch1_rxrate[7:0],ch1_rxresetmode[1:0],ch1_rxmstreset,ch1_rxmstdatapathreset,ch1_rxmstresetdone,ch1_rxslide,ch1_rxsliderdy,ch1_rxstartofseq[1:0],ch1_rxstatus[2:0],ch1_rxsyncallin,ch1_rxsyncdone,ch1_rxtermination,ch1_rxvalid,ch1_cdrbmcdrreq,ch1_cdrfreqos,ch1_cdrincpctrl,ch1_cdrstepdir,ch1_cdrstepsq,ch1_cdrstepsx,ch1_cfokovrdfinish,ch1_cfokovrdpulse,ch1_cfokovrdstart,ch1_eyescanreset,ch1_eyescantrigger,ch1_eyescandataerror,ch1_cfokovrdrdy0,ch1_cfokovrdrdy1,ch2_rxdata[255:0],ch2_rxpcsresetmask[2:0],ch2_rxpmaresetmask[7:0],ch2_rxdatavalid[1:0],ch2_rxheader[5:0],ch2_rxgearboxslip,ch2_gtrxreset,ch2_rxprogdivreset,ch2_rxuserrdy,ch2_rxprogdivresetdone,ch2_rxpmaresetdone,ch2_rxresetdone,ch2_rx10gstat[7:0],ch2_rxbufstatus[2:0],ch2_rxbyteisaligned,ch2_rxbyterealign,ch2_rxcdrhold,ch2_rxcdrlock,ch2_rxcdrovrden,ch2_rxcdrphdone,ch2_rxcdrreset,ch2_rxchanbondseq,ch2_rxchanisaligned,ch2_rxchanrealign,ch2_rxchbondi[4:0],ch2_rxchbondo[4:0],ch2_rxclkcorcnt[1:0],ch2_rxcominitdet,ch2_rxcommadet,ch2_rxcomsasdet,ch2_rxcomwakedet,ch2_rxctrl0[15:0],ch2_rxctrl1[15:0],ch2_rxctrl2[7:0],ch2_rxctrl3[7:0],ch2_rxdapicodeovrden,ch2_rxdapicodereset,ch2_rxdataextendrsvd[7:0],ch2_rxdccdone,ch2_rxdlyalignerr,ch2_rxdlyalignprog,ch2_rxdlyalignreq,ch2_rxelecidle,ch2_rxeqtraining,ch2_rxfinealigndone,ch2_rxheadervalid[1:0],ch2_rxlpmen,ch2_rxmldchaindone,ch2_rxmldchainreq,ch2_rxmlfinealignreq,ch2_rxoobreset,ch2_rxosintdone,ch2_rxosintstarted,ch2_rxosintstrobedone,ch2_rxosintstrobestarted,ch2_rxpd[1:0],ch2_rxphaligndone,ch2_rxphalignerr,ch2_rxphalignreq,ch2_rxphalignresetmask[1:0],ch2_rxphdlypd,ch2_rxphdlyreset,ch2_rxphdlyresetdone,ch2_rxphsetinitdone,ch2_rxphsetinitreq,ch2_rxphshift180,ch2_rxphshift180done,ch2_rxpolarity,ch2_rxprbscntreset,ch2_rxprbserr,ch2_rxprbslocked,ch2_rxprbssel[3:0],ch2_rxrate[7:0],ch2_rxresetmode[1:0],ch2_rxmstreset,ch2_rxmstdatapathreset,ch2_rxmstresetdone,ch2_rxslide,ch2_rxsliderdy,ch2_rxstartofseq[1:0],ch2_rxstatus[2:0],ch2_rxsyncallin,ch2_rxsyncdone,ch2_rxtermination,ch2_rxvalid,ch2_cdrbmcdrreq,ch2_cdrfreqos,ch2_cdrincpctrl,ch2_cdrstepdir,ch2_cdrstepsq,ch2_cdrstepsx,ch2_cfokovrdfinish,ch2_cfokovrdpulse,ch2_cfokovrdstart,ch2_eyescanreset,ch2_eyescantrigger,ch2_eyescandataerror,ch2_cfokovrdrdy0,ch2_cfokovrdrdy1,ch3_rxdata[255:0],ch3_rxpcsresetmask[2:0],ch3_rxpmaresetmask[7:0],ch3_rxdatavalid[1:0],ch3_rxheader[5:0],ch3_rxgearboxslip,ch3_gtrxreset,ch3_rxprogdivreset,ch3_rxuserrdy,ch3_rxprogdivresetdone,ch3_rxpmaresetdone,ch3_rxresetdone,ch3_rx10gstat[7:0],ch3_rxbufstatus[2:0],ch3_rxbyteisaligned,ch3_rxbyterealign,ch3_rxcdrhold,ch3_rxcdrlock,ch3_rxcdrovrden,ch3_rxcdrphdone,ch3_rxcdrreset,ch3_rxchanbondseq,ch3_rxchanisaligned,ch3_rxchanrealign,ch3_rxchbondi[4:0],ch3_rxchbondo[4:0],ch3_rxclkcorcnt[1:0],ch3_rxcominitdet,ch3_rxcommadet,ch3_rxcomsasdet,ch3_rxcomwakedet,ch3_rxctrl0[15:0],ch3_rxctrl1[15:0],ch3_rxctrl2[7:0],ch3_rxctrl3[7:0],ch3_rxdapicodeovrden,ch3_rxdapicodereset,ch3_rxdataextendrsvd[7:0],ch3_rxdccdone,ch3_rxdlyalignerr,ch3_rxdlyalignprog,ch3_rxdlyalignreq,ch3_rxelecidle,ch3_rxeqtraining,ch3_rxfinealigndone,ch3_rxheadervalid[1:0],ch3_rxlpmen,ch3_rxmldchaindone,ch3_rxmldchainreq,ch3_rxmlfinealignreq,ch3_rxoobreset,ch3_rxosintdone,ch3_rxosintstarted,ch3_rxosintstrobedone,ch3_rxosintstrobestarted,ch3_rxpd[1:0],ch3_rxphaligndone,ch3_rxphalignerr,ch3_rxphalignreq,ch3_rxphalignresetmask[1:0],ch3_rxphdlypd,ch3_rxphdlyreset,ch3_rxphdlyresetdone,ch3_rxphsetinitdone,ch3_rxphsetinitreq,ch3_rxphshift180,ch3_rxphshift180done,ch3_rxpolarity,ch3_rxprbscntreset,ch3_rxprbserr,ch3_rxprbslocked,ch3_rxprbssel[3:0],ch3_rxrate[7:0],ch3_rxresetmode[1:0],ch3_rxmstreset,ch3_rxmstdatapathreset,ch3_rxmstresetdone,ch3_rxslide,ch3_rxsliderdy,ch3_rxstartofseq[1:0],ch3_rxstatus[2:0],ch3_rxsyncallin,ch3_rxsyncdone,ch3_rxtermination,ch3_rxvalid,ch3_cdrbmcdrreq,ch3_cdrfreqos,ch3_cdrincpctrl,ch3_cdrstepdir,ch3_cdrstepsq,ch3_cdrstepsx,ch3_cfokovrdfinish,ch3_cfokovrdpulse,ch3_cfokovrdstart,ch3_eyescanreset,ch3_eyescantrigger,ch3_eyescandataerror,ch3_cfokovrdrdy0,ch3_cfokovrdrdy1,gt_txusrclk,gt_rxusrclk,apb3clk,gtpowergood,gt_lcpll_lock,gt_rpll_lock,ch_phystatus_in[3:0],ilo_resetdone,tx_clr_out,tx_clrb_leaf_out,rx_clr_out,rx_clrb_leaf_out,rx_resetdone_out,tx_resetdone_out,txusrclk_out,rxusrclk_out,link_status_out,gpio_enable,rpll_lock_out,lcpll_lock_out,pcie_rstb,gpi_out,gpo_in,gtreset_in,rate_sel[3:0],reset_mask[1:0],reset_tx_pll_and_datapath_in,reset_tx_datapath_in,reset_rx_pll_and_datapath_in,reset_rx_datapath_in";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "versal_ibert_bridge_refclkGTM_REFCLK_X0Y4_0_inst,Vivado 2023.2";
begin
end;
