-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2023.2 (win64) Build 4029153 Fri Oct 13 20:14:34 MDT 2023
-- Date        : Mon May  6 17:57:33 2024
-- Host        : Vulcan running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ versal_ibert_gt_quad_base_7_0_stub.vhdl
-- Design      : versal_ibert_gt_quad_base_7_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcvp1202-vsva2785-2MHP-e-S
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    rxmarginclk : in STD_LOGIC;
    hsclk0_lcpllreset : in STD_LOGIC;
    hsclk0_rpllreset : in STD_LOGIC;
    hsclk1_lcpllreset : in STD_LOGIC;
    hsclk1_rpllreset : in STD_LOGIC;
    hsclk0_lcplllock : out STD_LOGIC;
    hsclk1_lcplllock : out STD_LOGIC;
    hsclk0_rplllock : out STD_LOGIC;
    hsclk1_rplllock : out STD_LOGIC;
    gtpowergood : out STD_LOGIC;
    ch0_pcierstb : in STD_LOGIC;
    ch1_pcierstb : in STD_LOGIC;
    ch2_pcierstb : in STD_LOGIC;
    ch3_pcierstb : in STD_LOGIC;
    pcielinkreachtarget : in STD_LOGIC;
    pcieltssm : in STD_LOGIC_VECTOR ( 5 downto 0 );
    rxmarginreqack : out STD_LOGIC;
    rxmarginrescmd : out STD_LOGIC_VECTOR ( 3 downto 0 );
    rxmarginreslanenum : out STD_LOGIC_VECTOR ( 1 downto 0 );
    rxmarginrespayld : out STD_LOGIC_VECTOR ( 7 downto 0 );
    rxmarginresreq : out STD_LOGIC;
    rxmarginreqcmd : in STD_LOGIC_VECTOR ( 3 downto 0 );
    rxmarginreqlanenum : in STD_LOGIC_VECTOR ( 1 downto 0 );
    rxmarginreqpayld : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rxmarginreqreq : in STD_LOGIC;
    rxmarginresack : in STD_LOGIC;
    ch0_iloreset : in STD_LOGIC;
    ch1_iloreset : in STD_LOGIC;
    ch2_iloreset : in STD_LOGIC;
    ch3_iloreset : in STD_LOGIC;
    ch0_iloresetdone : out STD_LOGIC;
    ch1_iloresetdone : out STD_LOGIC;
    ch2_iloresetdone : out STD_LOGIC;
    ch3_iloresetdone : out STD_LOGIC;
    ch0_phystatus : out STD_LOGIC;
    ch1_phystatus : out STD_LOGIC;
    ch2_phystatus : out STD_LOGIC;
    ch3_phystatus : out STD_LOGIC;
    hsclk0_lcpllfbclklost : out STD_LOGIC;
    hsclk0_lcpllrefclklost : out STD_LOGIC;
    hsclk0_lcpllrefclkmonitor : out STD_LOGIC;
    hsclk0_rpllfbclklost : out STD_LOGIC;
    hsclk0_rpllrefclklost : out STD_LOGIC;
    hsclk0_rpllrefclkmonitor : out STD_LOGIC;
    hsclk1_lcpllfbclklost : out STD_LOGIC;
    hsclk1_lcpllrefclklost : out STD_LOGIC;
    hsclk1_lcpllrefclkmonitor : out STD_LOGIC;
    hsclk1_rpllfbclklost : out STD_LOGIC;
    hsclk1_rpllrefclklost : out STD_LOGIC;
    hsclk1_rpllrefclkmonitor : out STD_LOGIC;
    hsclk0_lcpllpd : in STD_LOGIC;
    hsclk0_rpllpd : in STD_LOGIC;
    hsclk0_lcpllresetbypassmode : in STD_LOGIC;
    hsclk0_lcpllsdmtoggle : in STD_LOGIC;
    hsclk0_rpllresetbypassmode : in STD_LOGIC;
    hsclk0_rpllsdmtoggle : in STD_LOGIC;
    hsclk1_lcpllpd : in STD_LOGIC;
    hsclk1_lcpllresetbypassmode : in STD_LOGIC;
    hsclk1_lcpllsdmtoggle : in STD_LOGIC;
    hsclk1_rpllpd : in STD_LOGIC;
    hsclk1_rpllresetbypassmode : in STD_LOGIC;
    hsclk1_rpllsdmtoggle : in STD_LOGIC;
    refclk0_gtrefclkpd : in STD_LOGIC;
    refclk1_gtrefclkpd : in STD_LOGIC;
    hsclk0_lcpllrefclksel : in STD_LOGIC_VECTOR ( 2 downto 0 );
    hsclk1_lcpllrefclksel : in STD_LOGIC_VECTOR ( 2 downto 0 );
    hsclk0_rpllrefclksel : in STD_LOGIC_VECTOR ( 2 downto 0 );
    hsclk1_rpllrefclksel : in STD_LOGIC_VECTOR ( 2 downto 0 );
    hsclk0_lcpllfbdiv : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk0_rpllfbdiv : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk1_lcpllfbdiv : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk1_rpllfbdiv : in STD_LOGIC_VECTOR ( 7 downto 0 );
    hsclk0_rxrecclkout0 : out STD_LOGIC;
    hsclk0_rxrecclkout1 : out STD_LOGIC;
    hsclk1_rxrecclkout0 : out STD_LOGIC;
    hsclk1_rxrecclkout1 : out STD_LOGIC;
    hsclk0_lcpllsdmdata : in STD_LOGIC_VECTOR ( 25 downto 0 );
    hsclk1_lcpllsdmdata : in STD_LOGIC_VECTOR ( 25 downto 0 );
    hsclk0_rpllsdmdata : in STD_LOGIC_VECTOR ( 25 downto 0 );
    hsclk1_rpllsdmdata : in STD_LOGIC_VECTOR ( 25 downto 0 );
    hsclk0_lcpllresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    hsclk1_lcpllresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    hsclk0_rpllresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    hsclk1_rpllresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gpi : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gpo : out STD_LOGIC_VECTOR ( 31 downto 0 );
    hsclk0_rxrecclksel : out STD_LOGIC_VECTOR ( 1 downto 0 );
    hsclk1_rxrecclksel : out STD_LOGIC_VECTOR ( 1 downto 0 );
    correcterr : out STD_LOGIC;
    debugtracetvalid : out STD_LOGIC;
    debugtracetdata : out STD_LOGIC_VECTOR ( 15 downto 0 );
    refclk0_gtrefclkpdint : out STD_LOGIC;
    refclk0_clktestsigint : out STD_LOGIC;
    refclk1_gtrefclkpdint : out STD_LOGIC;
    refclk1_clktestsigint : out STD_LOGIC;
    trigackin0 : out STD_LOGIC;
    trigout0 : out STD_LOGIC;
    ubinterrupt : out STD_LOGIC;
    ubtxuart : out STD_LOGIC;
    uncorrecterr : out STD_LOGIC;
    ctrlrsvdout : out STD_LOGIC_VECTOR ( 7 downto 0 );
    bgbypassb : in STD_LOGIC;
    bgmonitorenb : in STD_LOGIC;
    bgpdb : in STD_LOGIC;
    bgrcalovrdenb : in STD_LOGIC;
    bgrcalovrd : in STD_LOGIC_VECTOR ( 4 downto 0 );
    debugtraceready : in STD_LOGIC;
    debugtraceclk : in STD_LOGIC;
    trigackout0 : in STD_LOGIC;
    trigin0 : in STD_LOGIC;
    ubenable : in STD_LOGIC;
    ubiolmbrst : in STD_LOGIC;
    ubmbrst : in STD_LOGIC;
    ubintr : in STD_LOGIC_VECTOR ( 11 downto 0 );
    ubrxuart : in STD_LOGIC;
    coestatusdebug : in STD_LOGIC;
    ctrlrsvdin : in STD_LOGIC_VECTOR ( 7 downto 0 );
    refclk0_clktestsig : in STD_LOGIC;
    refclk1_clktestsig : in STD_LOGIC;
    apb3clk : in STD_LOGIC;
    apb3paddr : in STD_LOGIC_VECTOR ( 15 downto 0 );
    apb3penable : in STD_LOGIC;
    apb3presetn : in STD_LOGIC;
    apb3prdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    apb3psel : in STD_LOGIC;
    apb3pslverr : out STD_LOGIC;
    apb3pready : out STD_LOGIC;
    apb3pwdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    apb3pwrite : in STD_LOGIC;
    resetdone_northin : in STD_LOGIC_VECTOR ( 1 downto 0 );
    resetdone_southin : in STD_LOGIC_VECTOR ( 1 downto 0 );
    resetdone_northout : out STD_LOGIC_VECTOR ( 1 downto 0 );
    resetdone_southout : out STD_LOGIC_VECTOR ( 1 downto 0 );
    GT_REFCLK0 : in STD_LOGIC;
    m0_axis_tready : in STD_LOGIC;
    m0_axis_tlast : out STD_LOGIC;
    m0_axis_tvalid : out STD_LOGIC;
    m0_axis_tdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s0_axis_tready : out STD_LOGIC;
    s0_axis_tlast : in STD_LOGIC;
    s0_axis_tvalid : in STD_LOGIC;
    s0_axis_tdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    ch0_pcsrsvdout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_pinrsvdas : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_refdebugout : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_dmonitorout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ch0_dmonitoroutclk : out STD_LOGIC;
    ch0_eyescandataerror : out STD_LOGIC;
    ch0_resetexception : out STD_LOGIC;
    ch0_gtrsvd : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch0_loopback : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_cdrfreqos : in STD_LOGIC;
    ch0_cdrincpctrl : in STD_LOGIC;
    ch0_cdrstepdir : in STD_LOGIC;
    ch0_cdrstepsq : in STD_LOGIC;
    ch0_cdrstepsx : in STD_LOGIC;
    ch0_clkrsvd0 : in STD_LOGIC;
    ch0_clkrsvd1 : in STD_LOGIC;
    ch0_dmonfiforeset : in STD_LOGIC;
    ch0_dmonitorclk : in STD_LOGIC;
    ch0_eyescanreset : in STD_LOGIC;
    ch0_eyescantrigger : in STD_LOGIC;
    ch0_gtrxreset : in STD_LOGIC;
    ch0_gttxreset : in STD_LOGIC;
    ch0_iloresetmask : in STD_LOGIC;
    m1_axis_tready : in STD_LOGIC;
    m1_axis_tlast : out STD_LOGIC;
    m1_axis_tvalid : out STD_LOGIC;
    m1_axis_tdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s1_axis_tready : out STD_LOGIC;
    s1_axis_tlast : in STD_LOGIC;
    s1_axis_tvalid : in STD_LOGIC;
    s1_axis_tdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    ch1_pcsrsvdout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_pinrsvdas : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_refdebugout : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_dmonitorout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ch1_dmonitoroutclk : out STD_LOGIC;
    ch1_eyescandataerror : out STD_LOGIC;
    ch1_resetexception : out STD_LOGIC;
    ch1_gtrsvd : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch1_loopback : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_cdrfreqos : in STD_LOGIC;
    ch1_cdrincpctrl : in STD_LOGIC;
    ch1_cdrstepdir : in STD_LOGIC;
    ch1_cdrstepsq : in STD_LOGIC;
    ch1_cdrstepsx : in STD_LOGIC;
    ch1_clkrsvd0 : in STD_LOGIC;
    ch1_clkrsvd1 : in STD_LOGIC;
    ch1_dmonfiforeset : in STD_LOGIC;
    ch1_dmonitorclk : in STD_LOGIC;
    ch1_eyescanreset : in STD_LOGIC;
    ch1_eyescantrigger : in STD_LOGIC;
    ch1_gtrxreset : in STD_LOGIC;
    ch1_gttxreset : in STD_LOGIC;
    ch1_iloresetmask : in STD_LOGIC;
    m2_axis_tready : in STD_LOGIC;
    m2_axis_tlast : out STD_LOGIC;
    m2_axis_tvalid : out STD_LOGIC;
    m2_axis_tdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s2_axis_tready : out STD_LOGIC;
    s2_axis_tlast : in STD_LOGIC;
    s2_axis_tvalid : in STD_LOGIC;
    s2_axis_tdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    ch2_pcsrsvdout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_pinrsvdas : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_refdebugout : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_dmonitorout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ch2_dmonitoroutclk : out STD_LOGIC;
    ch2_eyescandataerror : out STD_LOGIC;
    ch2_resetexception : out STD_LOGIC;
    ch2_gtrsvd : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch2_loopback : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_cdrfreqos : in STD_LOGIC;
    ch2_cdrincpctrl : in STD_LOGIC;
    ch2_cdrstepdir : in STD_LOGIC;
    ch2_cdrstepsq : in STD_LOGIC;
    ch2_cdrstepsx : in STD_LOGIC;
    ch2_clkrsvd0 : in STD_LOGIC;
    ch2_clkrsvd1 : in STD_LOGIC;
    ch2_dmonfiforeset : in STD_LOGIC;
    ch2_dmonitorclk : in STD_LOGIC;
    ch2_eyescanreset : in STD_LOGIC;
    ch2_eyescantrigger : in STD_LOGIC;
    ch2_gtrxreset : in STD_LOGIC;
    ch2_gttxreset : in STD_LOGIC;
    ch2_iloresetmask : in STD_LOGIC;
    m3_axis_tready : in STD_LOGIC;
    m3_axis_tlast : out STD_LOGIC;
    m3_axis_tvalid : out STD_LOGIC;
    m3_axis_tdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s3_axis_tready : out STD_LOGIC;
    s3_axis_tlast : in STD_LOGIC;
    s3_axis_tvalid : in STD_LOGIC;
    s3_axis_tdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    ch3_pcsrsvdout : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_pinrsvdas : out STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_refdebugout : out STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_dmonitorout : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ch3_dmonitoroutclk : out STD_LOGIC;
    ch3_eyescandataerror : out STD_LOGIC;
    ch3_resetexception : out STD_LOGIC;
    ch3_gtrsvd : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_pcsrsvdin : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ch3_loopback : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_cdrfreqos : in STD_LOGIC;
    ch3_cdrincpctrl : in STD_LOGIC;
    ch3_cdrstepdir : in STD_LOGIC;
    ch3_cdrstepsq : in STD_LOGIC;
    ch3_cdrstepsx : in STD_LOGIC;
    ch3_clkrsvd0 : in STD_LOGIC;
    ch3_clkrsvd1 : in STD_LOGIC;
    ch3_dmonfiforeset : in STD_LOGIC;
    ch3_dmonitorclk : in STD_LOGIC;
    ch3_eyescanreset : in STD_LOGIC;
    ch3_eyescantrigger : in STD_LOGIC;
    ch3_gtrxreset : in STD_LOGIC;
    ch3_gttxreset : in STD_LOGIC;
    ch3_iloresetmask : in STD_LOGIC;
    ch0_txbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_txdccdone : out STD_LOGIC;
    ch0_txdebugpcsout : out STD_LOGIC;
    ch0_txpmaresetdone : out STD_LOGIC;
    ch0_txprogdivresetdone : out STD_LOGIC;
    ch0_txresetdone : out STD_LOGIC;
    ch0_txdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    ch0_txpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txpmaresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_txrsv1 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_txrsv0 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch0_txpostcursor : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txprecursor : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txprecursor2 : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txprecursor3 : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch0_txmaincursor : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch0_txrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_txinhibit : in STD_LOGIC;
    ch0_txlatclk : in STD_LOGIC;
    ch0_txpcsresetmask : in STD_LOGIC;
    ch0_txperst : in STD_LOGIC;
    ch0_txpisopd : in STD_LOGIC;
    ch0_txpolarity : in STD_LOGIC;
    ch0_txprbsforceerr : in STD_LOGIC;
    ch0_txprogdivreset : in STD_LOGIC;
    ch0_txqprbsen : in STD_LOGIC;
    ch0_txuserrdy : in STD_LOGIC;
    ch0_txmstreset : in STD_LOGIC;
    ch0_txmstdatapathreset : in STD_LOGIC;
    ch0_txmstresetdone : out STD_LOGIC;
    ch1_txbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_txdccdone : out STD_LOGIC;
    ch1_txdebugpcsout : out STD_LOGIC;
    ch1_txpmaresetdone : out STD_LOGIC;
    ch1_txprogdivresetdone : out STD_LOGIC;
    ch1_txresetdone : out STD_LOGIC;
    ch1_txdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    ch1_txpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txpmaresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_txrsv1 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_txrsv0 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch1_txpostcursor : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txprecursor : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txprecursor2 : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txprecursor3 : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch1_txmaincursor : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch1_txrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_txinhibit : in STD_LOGIC;
    ch1_txlatclk : in STD_LOGIC;
    ch1_txpcsresetmask : in STD_LOGIC;
    ch1_txperst : in STD_LOGIC;
    ch1_txpisopd : in STD_LOGIC;
    ch1_txpolarity : in STD_LOGIC;
    ch1_txprbsforceerr : in STD_LOGIC;
    ch1_txprogdivreset : in STD_LOGIC;
    ch1_txqprbsen : in STD_LOGIC;
    ch1_txuserrdy : in STD_LOGIC;
    ch1_txmstreset : in STD_LOGIC;
    ch1_txmstdatapathreset : in STD_LOGIC;
    ch1_txmstresetdone : out STD_LOGIC;
    ch2_txbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_txdccdone : out STD_LOGIC;
    ch2_txdebugpcsout : out STD_LOGIC;
    ch2_txpmaresetdone : out STD_LOGIC;
    ch2_txprogdivresetdone : out STD_LOGIC;
    ch2_txresetdone : out STD_LOGIC;
    ch2_txdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    ch2_txpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txpmaresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch2_txrsv1 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch2_txrsv0 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch2_txpostcursor : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_txprecursor : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_txprecursor2 : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_txprecursor3 : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch2_txmaincursor : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch2_txrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_txinhibit : in STD_LOGIC;
    ch2_txlatclk : in STD_LOGIC;
    ch2_txpcsresetmask : in STD_LOGIC;
    ch2_txperst : in STD_LOGIC;
    ch2_txpisopd : in STD_LOGIC;
    ch2_txpolarity : in STD_LOGIC;
    ch2_txprbsforceerr : in STD_LOGIC;
    ch2_txprogdivreset : in STD_LOGIC;
    ch2_txqprbsen : in STD_LOGIC;
    ch2_txuserrdy : in STD_LOGIC;
    ch2_txmstreset : in STD_LOGIC;
    ch2_txmstdatapathreset : in STD_LOGIC;
    ch2_txmstresetdone : out STD_LOGIC;
    ch3_txbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_txdccdone : out STD_LOGIC;
    ch3_txdebugpcsout : out STD_LOGIC;
    ch3_txpmaresetdone : out STD_LOGIC;
    ch3_txprogdivresetdone : out STD_LOGIC;
    ch3_txresetdone : out STD_LOGIC;
    ch3_txdata : in STD_LOGIC_VECTOR ( 255 downto 0 );
    ch3_txpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txpmaresetmask : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_txprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch3_txrsv1 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch3_txrsv0 : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ch3_txpostcursor : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_txprecursor : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_txprecursor2 : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_txprecursor3 : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ch3_txmaincursor : in STD_LOGIC_VECTOR ( 6 downto 0 );
    ch3_txrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_txinhibit : in STD_LOGIC;
    ch3_txlatclk : in STD_LOGIC;
    ch3_txpcsresetmask : in STD_LOGIC;
    ch3_txperst : in STD_LOGIC;
    ch3_txpisopd : in STD_LOGIC;
    ch3_txpolarity : in STD_LOGIC;
    ch3_txprbsforceerr : in STD_LOGIC;
    ch3_txprogdivreset : in STD_LOGIC;
    ch3_txqprbsen : in STD_LOGIC;
    ch3_txuserrdy : in STD_LOGIC;
    ch3_txmstreset : in STD_LOGIC;
    ch3_txmstdatapathreset : in STD_LOGIC;
    ch3_txmstresetdone : out STD_LOGIC;
    ch0_rxdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ch0_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxcdrlock : out STD_LOGIC;
    ch0_rxcdrphdone : out STD_LOGIC;
    ch0_rxdebugpcsout : out STD_LOGIC;
    ch0_rxpmaresetdone : out STD_LOGIC;
    ch0_rxprbserr : out STD_LOGIC;
    ch0_rxprbslocked : out STD_LOGIC;
    ch0_rxprogdivresetdone : out STD_LOGIC;
    ch0_rxresetdone : out STD_LOGIC;
    ch0_rxpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch0_rxpcsresetmask : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch0_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch0_rxpmaresetmask : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch0_rxcdrhold : in STD_LOGIC;
    ch0_rxcdrovrden : in STD_LOGIC;
    ch0_rxcdrreset : in STD_LOGIC;
    ch0_rxlatclk : in STD_LOGIC;
    ch0_rxperst : in STD_LOGIC;
    ch0_rxpolarity : in STD_LOGIC;
    ch0_rxprbscntreset : in STD_LOGIC;
    ch0_rxprbscntstop : in STD_LOGIC;
    ch0_rxprogdivreset : in STD_LOGIC;
    ch0_rxqprbsen : in STD_LOGIC;
    ch0_rxrsv0 : in STD_LOGIC;
    ch0_rxrsv1 : in STD_LOGIC;
    ch0_rxrsv2 : in STD_LOGIC;
    ch0_rxuserrdy : in STD_LOGIC;
    ch0_rxmstreset : in STD_LOGIC;
    ch0_rxmstdatapathreset : in STD_LOGIC;
    ch0_rxmstresetdone : out STD_LOGIC;
    ch1_rxdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ch1_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxcdrlock : out STD_LOGIC;
    ch1_rxcdrphdone : out STD_LOGIC;
    ch1_rxdebugpcsout : out STD_LOGIC;
    ch1_rxpmaresetdone : out STD_LOGIC;
    ch1_rxprbserr : out STD_LOGIC;
    ch1_rxprbslocked : out STD_LOGIC;
    ch1_rxprogdivresetdone : out STD_LOGIC;
    ch1_rxresetdone : out STD_LOGIC;
    ch1_rxpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch1_rxpcsresetmask : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch1_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch1_rxpmaresetmask : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch1_rxcdrhold : in STD_LOGIC;
    ch1_rxcdrovrden : in STD_LOGIC;
    ch1_rxcdrreset : in STD_LOGIC;
    ch1_rxlatclk : in STD_LOGIC;
    ch1_rxperst : in STD_LOGIC;
    ch1_rxpolarity : in STD_LOGIC;
    ch1_rxprbscntreset : in STD_LOGIC;
    ch1_rxprbscntstop : in STD_LOGIC;
    ch1_rxprogdivreset : in STD_LOGIC;
    ch1_rxqprbsen : in STD_LOGIC;
    ch1_rxrsv0 : in STD_LOGIC;
    ch1_rxrsv1 : in STD_LOGIC;
    ch1_rxrsv2 : in STD_LOGIC;
    ch1_rxuserrdy : in STD_LOGIC;
    ch1_rxmstreset : in STD_LOGIC;
    ch1_rxmstdatapathreset : in STD_LOGIC;
    ch1_rxmstresetdone : out STD_LOGIC;
    ch2_rxdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ch2_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_rxcdrlock : out STD_LOGIC;
    ch2_rxcdrphdone : out STD_LOGIC;
    ch2_rxdebugpcsout : out STD_LOGIC;
    ch2_rxpmaresetdone : out STD_LOGIC;
    ch2_rxprbserr : out STD_LOGIC;
    ch2_rxprbslocked : out STD_LOGIC;
    ch2_rxprogdivresetdone : out STD_LOGIC;
    ch2_rxresetdone : out STD_LOGIC;
    ch2_rxpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch2_rxpcsresetmask : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch2_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch2_rxpmaresetmask : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch2_rxcdrhold : in STD_LOGIC;
    ch2_rxcdrovrden : in STD_LOGIC;
    ch2_rxcdrreset : in STD_LOGIC;
    ch2_rxlatclk : in STD_LOGIC;
    ch2_rxperst : in STD_LOGIC;
    ch2_rxpolarity : in STD_LOGIC;
    ch2_rxprbscntreset : in STD_LOGIC;
    ch2_rxprbscntstop : in STD_LOGIC;
    ch2_rxprogdivreset : in STD_LOGIC;
    ch2_rxqprbsen : in STD_LOGIC;
    ch2_rxrsv0 : in STD_LOGIC;
    ch2_rxrsv1 : in STD_LOGIC;
    ch2_rxrsv2 : in STD_LOGIC;
    ch2_rxuserrdy : in STD_LOGIC;
    ch2_rxmstreset : in STD_LOGIC;
    ch2_rxmstdatapathreset : in STD_LOGIC;
    ch2_rxmstresetdone : out STD_LOGIC;
    ch3_rxdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    ch3_rxbufstatus : out STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_rxcdrlock : out STD_LOGIC;
    ch3_rxcdrphdone : out STD_LOGIC;
    ch3_rxdebugpcsout : out STD_LOGIC;
    ch3_rxpmaresetdone : out STD_LOGIC;
    ch3_rxprbserr : out STD_LOGIC;
    ch3_rxprbslocked : out STD_LOGIC;
    ch3_rxprogdivresetdone : out STD_LOGIC;
    ch3_rxresetdone : out STD_LOGIC;
    ch3_rxpd : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxresetmode : in STD_LOGIC_VECTOR ( 1 downto 0 );
    ch3_rxpcsresetmask : in STD_LOGIC_VECTOR ( 2 downto 0 );
    ch3_rxprbssel : in STD_LOGIC_VECTOR ( 3 downto 0 );
    ch3_rxpmaresetmask : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxrate : in STD_LOGIC_VECTOR ( 7 downto 0 );
    ch3_rxcdrhold : in STD_LOGIC;
    ch3_rxcdrovrden : in STD_LOGIC;
    ch3_rxcdrreset : in STD_LOGIC;
    ch3_rxlatclk : in STD_LOGIC;
    ch3_rxperst : in STD_LOGIC;
    ch3_rxpolarity : in STD_LOGIC;
    ch3_rxprbscntreset : in STD_LOGIC;
    ch3_rxprbscntstop : in STD_LOGIC;
    ch3_rxprogdivreset : in STD_LOGIC;
    ch3_rxqprbsen : in STD_LOGIC;
    ch3_rxrsv0 : in STD_LOGIC;
    ch3_rxrsv1 : in STD_LOGIC;
    ch3_rxrsv2 : in STD_LOGIC;
    ch3_rxuserrdy : in STD_LOGIC;
    ch3_rxmstreset : in STD_LOGIC;
    ch3_rxmstdatapathreset : in STD_LOGIC;
    ch3_rxmstresetdone : out STD_LOGIC;
    ch0_txoutclk : out STD_LOGIC;
    ch0_txusrclk : in STD_LOGIC;
    ch1_txoutclk : out STD_LOGIC;
    ch1_txusrclk : in STD_LOGIC;
    ch2_txoutclk : out STD_LOGIC;
    ch2_txusrclk : in STD_LOGIC;
    ch3_txoutclk : out STD_LOGIC;
    ch3_txusrclk : in STD_LOGIC;
    ch0_rxoutclk : out STD_LOGIC;
    ch0_rxusrclk : in STD_LOGIC;
    ch1_rxoutclk : out STD_LOGIC;
    ch1_rxusrclk : in STD_LOGIC;
    ch2_rxoutclk : out STD_LOGIC;
    ch2_rxusrclk : in STD_LOGIC;
    ch3_rxoutclk : out STD_LOGIC;
    ch3_rxusrclk : in STD_LOGIC;
    rxp : in STD_LOGIC_VECTOR ( 3 downto 0 );
    rxn : in STD_LOGIC_VECTOR ( 3 downto 0 );
    txp : out STD_LOGIC_VECTOR ( 3 downto 0 );
    txn : out STD_LOGIC_VECTOR ( 3 downto 0 )
  );

end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "rxmarginclk,hsclk0_lcpllreset,hsclk0_rpllreset,hsclk1_lcpllreset,hsclk1_rpllreset,hsclk0_lcplllock,hsclk1_lcplllock,hsclk0_rplllock,hsclk1_rplllock,gtpowergood,ch0_pcierstb,ch1_pcierstb,ch2_pcierstb,ch3_pcierstb,pcielinkreachtarget,pcieltssm[5:0],rxmarginreqack,rxmarginrescmd[3:0],rxmarginreslanenum[1:0],rxmarginrespayld[7:0],rxmarginresreq,rxmarginreqcmd[3:0],rxmarginreqlanenum[1:0],rxmarginreqpayld[7:0],rxmarginreqreq,rxmarginresack,ch0_iloreset,ch1_iloreset,ch2_iloreset,ch3_iloreset,ch0_iloresetdone,ch1_iloresetdone,ch2_iloresetdone,ch3_iloresetdone,ch0_phystatus,ch1_phystatus,ch2_phystatus,ch3_phystatus,hsclk0_lcpllfbclklost,hsclk0_lcpllrefclklost,hsclk0_lcpllrefclkmonitor,hsclk0_rpllfbclklost,hsclk0_rpllrefclklost,hsclk0_rpllrefclkmonitor,hsclk1_lcpllfbclklost,hsclk1_lcpllrefclklost,hsclk1_lcpllrefclkmonitor,hsclk1_rpllfbclklost,hsclk1_rpllrefclklost,hsclk1_rpllrefclkmonitor,hsclk0_lcpllpd,hsclk0_rpllpd,hsclk0_lcpllresetbypassmode,hsclk0_lcpllsdmtoggle,hsclk0_rpllresetbypassmode,hsclk0_rpllsdmtoggle,hsclk1_lcpllpd,hsclk1_lcpllresetbypassmode,hsclk1_lcpllsdmtoggle,hsclk1_rpllpd,hsclk1_rpllresetbypassmode,hsclk1_rpllsdmtoggle,refclk0_gtrefclkpd,refclk1_gtrefclkpd,hsclk0_lcpllrefclksel[2:0],hsclk1_lcpllrefclksel[2:0],hsclk0_rpllrefclksel[2:0],hsclk1_rpllrefclksel[2:0],hsclk0_lcpllfbdiv[7:0],hsclk0_rpllfbdiv[7:0],hsclk1_lcpllfbdiv[7:0],hsclk1_rpllfbdiv[7:0],hsclk0_rxrecclkout0,hsclk0_rxrecclkout1,hsclk1_rxrecclkout0,hsclk1_rxrecclkout1,hsclk0_lcpllsdmdata[25:0],hsclk1_lcpllsdmdata[25:0],hsclk0_rpllsdmdata[25:0],hsclk1_rpllsdmdata[25:0],hsclk0_lcpllresetmask[1:0],hsclk1_lcpllresetmask[1:0],hsclk0_rpllresetmask[1:0],hsclk1_rpllresetmask[1:0],gpi[31:0],gpo[31:0],hsclk0_rxrecclksel[1:0],hsclk1_rxrecclksel[1:0],correcterr,debugtracetvalid,debugtracetdata[15:0],refclk0_gtrefclkpdint,refclk0_clktestsigint,refclk1_gtrefclkpdint,refclk1_clktestsigint,trigackin0,trigout0,ubinterrupt,ubtxuart,uncorrecterr,ctrlrsvdout[7:0],bgbypassb,bgmonitorenb,bgpdb,bgrcalovrdenb,bgrcalovrd[4:0],debugtraceready,debugtraceclk,trigackout0,trigin0,ubenable,ubiolmbrst,ubmbrst,ubintr[11:0],ubrxuart,coestatusdebug,ctrlrsvdin[7:0],refclk0_clktestsig,refclk1_clktestsig,apb3clk,apb3paddr[15:0],apb3penable,apb3presetn,apb3prdata[31:0],apb3psel,apb3pslverr,apb3pready,apb3pwdata[31:0],apb3pwrite,resetdone_northin[1:0],resetdone_southin[1:0],resetdone_northout[1:0],resetdone_southout[1:0],GT_REFCLK0,m0_axis_tready,m0_axis_tlast,m0_axis_tvalid,m0_axis_tdata[31:0],s0_axis_tready,s0_axis_tlast,s0_axis_tvalid,s0_axis_tdata[31:0],ch0_pcsrsvdout[15:0],ch0_pinrsvdas[15:0],ch0_refdebugout[1:0],ch0_dmonitorout[31:0],ch0_dmonitoroutclk,ch0_eyescandataerror,ch0_resetexception,ch0_gtrsvd[15:0],ch0_pcsrsvdin[15:0],ch0_loopback[2:0],ch0_cdrfreqos,ch0_cdrincpctrl,ch0_cdrstepdir,ch0_cdrstepsq,ch0_cdrstepsx,ch0_clkrsvd0,ch0_clkrsvd1,ch0_dmonfiforeset,ch0_dmonitorclk,ch0_eyescanreset,ch0_eyescantrigger,ch0_gtrxreset,ch0_gttxreset,ch0_iloresetmask,m1_axis_tready,m1_axis_tlast,m1_axis_tvalid,m1_axis_tdata[31:0],s1_axis_tready,s1_axis_tlast,s1_axis_tvalid,s1_axis_tdata[31:0],ch1_pcsrsvdout[15:0],ch1_pinrsvdas[15:0],ch1_refdebugout[1:0],ch1_dmonitorout[31:0],ch1_dmonitoroutclk,ch1_eyescandataerror,ch1_resetexception,ch1_gtrsvd[15:0],ch1_pcsrsvdin[15:0],ch1_loopback[2:0],ch1_cdrfreqos,ch1_cdrincpctrl,ch1_cdrstepdir,ch1_cdrstepsq,ch1_cdrstepsx,ch1_clkrsvd0,ch1_clkrsvd1,ch1_dmonfiforeset,ch1_dmonitorclk,ch1_eyescanreset,ch1_eyescantrigger,ch1_gtrxreset,ch1_gttxreset,ch1_iloresetmask,m2_axis_tready,m2_axis_tlast,m2_axis_tvalid,m2_axis_tdata[31:0],s2_axis_tready,s2_axis_tlast,s2_axis_tvalid,s2_axis_tdata[31:0],ch2_pcsrsvdout[15:0],ch2_pinrsvdas[15:0],ch2_refdebugout[1:0],ch2_dmonitorout[31:0],ch2_dmonitoroutclk,ch2_eyescandataerror,ch2_resetexception,ch2_gtrsvd[15:0],ch2_pcsrsvdin[15:0],ch2_loopback[2:0],ch2_cdrfreqos,ch2_cdrincpctrl,ch2_cdrstepdir,ch2_cdrstepsq,ch2_cdrstepsx,ch2_clkrsvd0,ch2_clkrsvd1,ch2_dmonfiforeset,ch2_dmonitorclk,ch2_eyescanreset,ch2_eyescantrigger,ch2_gtrxreset,ch2_gttxreset,ch2_iloresetmask,m3_axis_tready,m3_axis_tlast,m3_axis_tvalid,m3_axis_tdata[31:0],s3_axis_tready,s3_axis_tlast,s3_axis_tvalid,s3_axis_tdata[31:0],ch3_pcsrsvdout[15:0],ch3_pinrsvdas[15:0],ch3_refdebugout[1:0],ch3_dmonitorout[31:0],ch3_dmonitoroutclk,ch3_eyescandataerror,ch3_resetexception,ch3_gtrsvd[15:0],ch3_pcsrsvdin[15:0],ch3_loopback[2:0],ch3_cdrfreqos,ch3_cdrincpctrl,ch3_cdrstepdir,ch3_cdrstepsq,ch3_cdrstepsx,ch3_clkrsvd0,ch3_clkrsvd1,ch3_dmonfiforeset,ch3_dmonitorclk,ch3_eyescanreset,ch3_eyescantrigger,ch3_gtrxreset,ch3_gttxreset,ch3_iloresetmask,ch0_txbufstatus[2:0],ch0_txdccdone,ch0_txdebugpcsout,ch0_txpmaresetdone,ch0_txprogdivresetdone,ch0_txresetdone,ch0_txdata[255:0],ch0_txpd[1:0],ch0_txpmaresetmask[1:0],ch0_txresetmode[1:0],ch0_txprbssel[3:0],ch0_txrsv1[3:0],ch0_txrsv0[4:0],ch0_txpostcursor[5:0],ch0_txprecursor[5:0],ch0_txprecursor2[5:0],ch0_txprecursor3[5:0],ch0_txmaincursor[6:0],ch0_txrate[7:0],ch0_txinhibit,ch0_txlatclk,ch0_txpcsresetmask,ch0_txperst,ch0_txpisopd,ch0_txpolarity,ch0_txprbsforceerr,ch0_txprogdivreset,ch0_txqprbsen,ch0_txuserrdy,ch0_txmstreset,ch0_txmstdatapathreset,ch0_txmstresetdone,ch1_txbufstatus[2:0],ch1_txdccdone,ch1_txdebugpcsout,ch1_txpmaresetdone,ch1_txprogdivresetdone,ch1_txresetdone,ch1_txdata[255:0],ch1_txpd[1:0],ch1_txpmaresetmask[1:0],ch1_txresetmode[1:0],ch1_txprbssel[3:0],ch1_txrsv1[3:0],ch1_txrsv0[4:0],ch1_txpostcursor[5:0],ch1_txprecursor[5:0],ch1_txprecursor2[5:0],ch1_txprecursor3[5:0],ch1_txmaincursor[6:0],ch1_txrate[7:0],ch1_txinhibit,ch1_txlatclk,ch1_txpcsresetmask,ch1_txperst,ch1_txpisopd,ch1_txpolarity,ch1_txprbsforceerr,ch1_txprogdivreset,ch1_txqprbsen,ch1_txuserrdy,ch1_txmstreset,ch1_txmstdatapathreset,ch1_txmstresetdone,ch2_txbufstatus[2:0],ch2_txdccdone,ch2_txdebugpcsout,ch2_txpmaresetdone,ch2_txprogdivresetdone,ch2_txresetdone,ch2_txdata[255:0],ch2_txpd[1:0],ch2_txpmaresetmask[1:0],ch2_txresetmode[1:0],ch2_txprbssel[3:0],ch2_txrsv1[3:0],ch2_txrsv0[4:0],ch2_txpostcursor[5:0],ch2_txprecursor[5:0],ch2_txprecursor2[5:0],ch2_txprecursor3[5:0],ch2_txmaincursor[6:0],ch2_txrate[7:0],ch2_txinhibit,ch2_txlatclk,ch2_txpcsresetmask,ch2_txperst,ch2_txpisopd,ch2_txpolarity,ch2_txprbsforceerr,ch2_txprogdivreset,ch2_txqprbsen,ch2_txuserrdy,ch2_txmstreset,ch2_txmstdatapathreset,ch2_txmstresetdone,ch3_txbufstatus[2:0],ch3_txdccdone,ch3_txdebugpcsout,ch3_txpmaresetdone,ch3_txprogdivresetdone,ch3_txresetdone,ch3_txdata[255:0],ch3_txpd[1:0],ch3_txpmaresetmask[1:0],ch3_txresetmode[1:0],ch3_txprbssel[3:0],ch3_txrsv1[3:0],ch3_txrsv0[4:0],ch3_txpostcursor[5:0],ch3_txprecursor[5:0],ch3_txprecursor2[5:0],ch3_txprecursor3[5:0],ch3_txmaincursor[6:0],ch3_txrate[7:0],ch3_txinhibit,ch3_txlatclk,ch3_txpcsresetmask,ch3_txperst,ch3_txpisopd,ch3_txpolarity,ch3_txprbsforceerr,ch3_txprogdivreset,ch3_txqprbsen,ch3_txuserrdy,ch3_txmstreset,ch3_txmstdatapathreset,ch3_txmstresetdone,ch0_rxdata[255:0],ch0_rxbufstatus[2:0],ch0_rxcdrlock,ch0_rxcdrphdone,ch0_rxdebugpcsout,ch0_rxpmaresetdone,ch0_rxprbserr,ch0_rxprbslocked,ch0_rxprogdivresetdone,ch0_rxresetdone,ch0_rxpd[1:0],ch0_rxresetmode[1:0],ch0_rxpcsresetmask[2:0],ch0_rxprbssel[3:0],ch0_rxpmaresetmask[7:0],ch0_rxrate[7:0],ch0_rxcdrhold,ch0_rxcdrovrden,ch0_rxcdrreset,ch0_rxlatclk,ch0_rxperst,ch0_rxpolarity,ch0_rxprbscntreset,ch0_rxprbscntstop,ch0_rxprogdivreset,ch0_rxqprbsen,ch0_rxrsv0,ch0_rxrsv1,ch0_rxrsv2,ch0_rxuserrdy,ch0_rxmstreset,ch0_rxmstdatapathreset,ch0_rxmstresetdone,ch1_rxdata[255:0],ch1_rxbufstatus[2:0],ch1_rxcdrlock,ch1_rxcdrphdone,ch1_rxdebugpcsout,ch1_rxpmaresetdone,ch1_rxprbserr,ch1_rxprbslocked,ch1_rxprogdivresetdone,ch1_rxresetdone,ch1_rxpd[1:0],ch1_rxresetmode[1:0],ch1_rxpcsresetmask[2:0],ch1_rxprbssel[3:0],ch1_rxpmaresetmask[7:0],ch1_rxrate[7:0],ch1_rxcdrhold,ch1_rxcdrovrden,ch1_rxcdrreset,ch1_rxlatclk,ch1_rxperst,ch1_rxpolarity,ch1_rxprbscntreset,ch1_rxprbscntstop,ch1_rxprogdivreset,ch1_rxqprbsen,ch1_rxrsv0,ch1_rxrsv1,ch1_rxrsv2,ch1_rxuserrdy,ch1_rxmstreset,ch1_rxmstdatapathreset,ch1_rxmstresetdone,ch2_rxdata[255:0],ch2_rxbufstatus[2:0],ch2_rxcdrlock,ch2_rxcdrphdone,ch2_rxdebugpcsout,ch2_rxpmaresetdone,ch2_rxprbserr,ch2_rxprbslocked,ch2_rxprogdivresetdone,ch2_rxresetdone,ch2_rxpd[1:0],ch2_rxresetmode[1:0],ch2_rxpcsresetmask[2:0],ch2_rxprbssel[3:0],ch2_rxpmaresetmask[7:0],ch2_rxrate[7:0],ch2_rxcdrhold,ch2_rxcdrovrden,ch2_rxcdrreset,ch2_rxlatclk,ch2_rxperst,ch2_rxpolarity,ch2_rxprbscntreset,ch2_rxprbscntstop,ch2_rxprogdivreset,ch2_rxqprbsen,ch2_rxrsv0,ch2_rxrsv1,ch2_rxrsv2,ch2_rxuserrdy,ch2_rxmstreset,ch2_rxmstdatapathreset,ch2_rxmstresetdone,ch3_rxdata[255:0],ch3_rxbufstatus[2:0],ch3_rxcdrlock,ch3_rxcdrphdone,ch3_rxdebugpcsout,ch3_rxpmaresetdone,ch3_rxprbserr,ch3_rxprbslocked,ch3_rxprogdivresetdone,ch3_rxresetdone,ch3_rxpd[1:0],ch3_rxresetmode[1:0],ch3_rxpcsresetmask[2:0],ch3_rxprbssel[3:0],ch3_rxpmaresetmask[7:0],ch3_rxrate[7:0],ch3_rxcdrhold,ch3_rxcdrovrden,ch3_rxcdrreset,ch3_rxlatclk,ch3_rxperst,ch3_rxpolarity,ch3_rxprbscntreset,ch3_rxprbscntstop,ch3_rxprogdivreset,ch3_rxqprbsen,ch3_rxrsv0,ch3_rxrsv1,ch3_rxrsv2,ch3_rxuserrdy,ch3_rxmstreset,ch3_rxmstdatapathreset,ch3_rxmstresetdone,ch0_txoutclk,ch0_txusrclk,ch1_txoutclk,ch1_txusrclk,ch2_txoutclk,ch2_txusrclk,ch3_txoutclk,ch3_txusrclk,ch0_rxoutclk,ch0_rxusrclk,ch1_rxoutclk,ch1_rxusrclk,ch2_rxoutclk,ch2_rxusrclk,ch3_rxoutclk,ch3_rxusrclk,rxp[3:0],rxn[3:0],txp[3:0],txn[3:0]";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "versal_ibert_gt_quad_base_7_0_inst,Vivado 2023.2";
begin
end;
