# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vulcan/Design_Tool/Board_Demo/ZCU208/adda_loopback/adda_loopback.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0.xci
# IP: The module: 'design_1_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vulcan/Design_Tool/Board_Demo/ZCU208/adda_loopback/adda_loopback.gen/sources_1/bd/design_1/ip/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Vulcan/Design_Tool/Board_Demo/ZCU208/adda_loopback/adda_loopback.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0.xci
# IP: The module: 'design_1_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vulcan/Design_Tool/Board_Demo/ZCU208/adda_loopback/adda_loopback.gen/sources_1/bd/design_1/ip/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
