// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_d92b_csc_0_v_csc_core_Pipeline_VITIS_LOOP_136_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_dout,
        stream_in_num_data_valid,
        stream_in_fifo_cap,
        stream_in_empty_n,
        stream_in_read,
        stream_csc_din,
        stream_csc_num_data_valid,
        stream_csc_fifo_cap,
        stream_csc_full_n,
        stream_csc_write,
        add_ln134,
        ColStart_read,
        ColEnd_read,
        cmp20_not,
        cmp17_not,
        K11_read,
        K11_2_read,
        K12_read,
        K12_2_read,
        K13_read,
        K13_2_read,
        K21_read,
        K21_2_read,
        K22_read,
        K22_2_read,
        K23_read,
        K23_2_read,
        K31_read,
        K31_2_read,
        K32_read,
        K32_2_read,
        K33_read,
        K33_2_read,
        ClipMax_read,
        ClipMax_2_read,
        ClampMin_read,
        ClampMin_2_read,
        BOffset_read,
        BOffset_2_read,
        GOffset_read,
        GOffset_2_read,
        ROffset_read,
        ROffset_2_read
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [35:0] stream_in_dout;
input  [4:0] stream_in_num_data_valid;
input  [4:0] stream_in_fifo_cap;
input   stream_in_empty_n;
output   stream_in_read;
output  [35:0] stream_csc_din;
input  [4:0] stream_csc_num_data_valid;
input  [4:0] stream_csc_fifo_cap;
input   stream_csc_full_n;
output   stream_csc_write;
input  [12:0] add_ln134;
input  [15:0] ColStart_read;
input  [15:0] ColEnd_read;
input  [0:0] cmp20_not;
input  [0:0] cmp17_not;
input  [15:0] K11_read;
input  [15:0] K11_2_read;
input  [15:0] K12_read;
input  [15:0] K12_2_read;
input  [15:0] K13_read;
input  [15:0] K13_2_read;
input  [15:0] K21_read;
input  [15:0] K21_2_read;
input  [15:0] K22_read;
input  [15:0] K22_2_read;
input  [15:0] K23_read;
input  [15:0] K23_2_read;
input  [15:0] K31_read;
input  [15:0] K31_2_read;
input  [15:0] K32_read;
input  [15:0] K32_2_read;
input  [15:0] K33_read;
input  [15:0] K33_2_read;
input  [11:0] ClipMax_read;
input  [11:0] ClipMax_2_read;
input  [11:0] ClampMin_read;
input  [11:0] ClampMin_2_read;
input  [13:0] BOffset_read;
input  [13:0] BOffset_2_read;
input  [13:0] GOffset_read;
input  [13:0] GOffset_2_read;
input  [13:0] ROffset_read;
input  [13:0] ROffset_2_read;

reg ap_idle;
reg stream_in_read;
reg stream_csc_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln136_fu_359_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    stream_in_blk_n;
wire    ap_block_pp0_stage0;
reg    stream_csc_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] or_ln150_2_fu_429_p2;
reg   [0:0] or_ln150_2_reg_1128;
reg   [0:0] or_ln150_2_reg_1128_pp0_iter1_reg;
reg   [0:0] or_ln150_2_reg_1128_pp0_iter2_reg;
reg   [0:0] or_ln150_2_reg_1128_pp0_iter3_reg;
wire   [11:0] Rpix_fu_446_p1;
reg   [11:0] Rpix_reg_1146;
reg   [11:0] Rpix_reg_1146_pp0_iter2_reg;
reg   [11:0] Gpix_reg_1151;
reg   [11:0] Gpix_reg_1151_pp0_iter2_reg;
wire   [27:0] zext_ln106_2_fu_497_p1;
wire  signed [27:0] mul_ln192_fu_610_p2;
reg  signed [27:0] mul_ln192_reg_1183;
wire  signed [27:0] mul_ln192_1_fu_616_p2;
reg  signed [27:0] mul_ln192_1_reg_1189;
wire  signed [27:0] mul_ln194_fu_632_p2;
reg  signed [27:0] mul_ln194_reg_1200;
wire  signed [27:0] mul_ln194_1_fu_638_p2;
reg  signed [27:0] mul_ln194_1_reg_1206;
wire  signed [27:0] mul_ln196_fu_654_p2;
reg  signed [27:0] mul_ln196_reg_1217;
wire  signed [27:0] mul_ln196_1_fu_660_p2;
reg  signed [27:0] mul_ln196_1_reg_1223;
wire   [11:0] max_val_fu_666_p3;
reg   [11:0] max_val_reg_1229;
wire   [11:0] min_val_fu_671_p3;
reg   [11:0] min_val_reg_1236;
wire   [23:0] trunc_ln192_fu_700_p1;
reg   [23:0] trunc_ln192_reg_1243;
wire   [23:0] trunc_ln192_1_fu_708_p1;
reg   [23:0] trunc_ln192_1_reg_1248;
wire   [23:0] trunc_ln194_fu_746_p1;
reg   [23:0] trunc_ln194_reg_1253;
wire   [23:0] trunc_ln194_1_fu_754_p1;
reg   [23:0] trunc_ln194_1_reg_1258;
wire   [23:0] trunc_ln196_fu_792_p1;
reg   [23:0] trunc_ln196_reg_1263;
wire   [23:0] trunc_ln196_1_fu_800_p1;
reg   [23:0] trunc_ln196_1_reg_1268;
wire   [0:0] icmp_ln198_fu_822_p2;
reg   [0:0] icmp_ln198_reg_1273;
wire   [0:0] icmp_ln198_1_fu_828_p2;
reg   [0:0] icmp_ln198_1_reg_1278;
wire   [0:0] icmp_ln199_fu_834_p2;
reg   [0:0] icmp_ln199_reg_1283;
wire   [0:0] icmp_ln199_1_fu_840_p2;
reg   [0:0] icmp_ln199_1_reg_1288;
wire   [0:0] icmp_ln200_fu_846_p2;
reg   [0:0] icmp_ln200_reg_1293;
wire   [0:0] icmp_ln200_1_fu_852_p2;
reg   [0:0] icmp_ln200_1_reg_1298;
reg   [12:0] x_fu_136;
wire   [12:0] x_3_fu_435_p2;
wire    ap_loop_init;
reg   [12:0] ap_sig_allocacmp_x_2;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] zext_ln136_fu_365_p1;
wire   [0:0] icmp_ln148_fu_369_p2;
wire   [0:0] icmp_ln148_1_fu_375_p2;
wire   [0:0] icmp_ln149_1_fu_393_p2;
wire   [0:0] icmp_ln149_fu_387_p2;
wire   [0:0] and_ln149_fu_399_p2;
wire   [0:0] or_ln150_fu_405_p2;
wire   [0:0] or_ln148_fu_381_p2;
wire   [0:0] xor_ln150_fu_411_p2;
wire   [0:0] and_ln150_fu_417_p2;
wire   [0:0] or_ln150_1_fu_423_p2;
wire  signed [15:0] coef33_fu_470_p3;
wire  signed [15:0] coef23_fu_465_p3;
wire  signed [15:0] coef13_fu_460_p3;
wire   [11:0] tmp_fu_487_p4;
wire   [13:0] select_ln150_11_fu_531_p3;
wire   [13:0] select_ln150_12_fu_544_p3;
wire   [13:0] select_ln150_13_fu_557_p3;
wire  signed [15:0] coef32_fu_526_p3;
wire  signed [15:0] coef31_fu_521_p3;
wire  signed [15:0] coef22_fu_516_p3;
wire  signed [15:0] coef21_fu_511_p3;
wire  signed [15:0] coef12_fu_506_p3;
wire  signed [15:0] coef11_fu_501_p3;
wire   [25:0] offsetR_fu_562_p3;
wire  signed [25:0] or_ln192_fu_600_p2;
wire   [11:0] mul_ln192_fu_610_p1;
wire   [27:0] zext_ln106_fu_594_p1;
wire   [11:0] mul_ln192_1_fu_616_p0;
wire   [27:0] zext_ln106_1_fu_597_p1;
wire   [25:0] offsetG_fu_549_p3;
wire  signed [25:0] or_ln194_fu_622_p2;
wire   [11:0] mul_ln194_fu_632_p1;
wire   [11:0] mul_ln194_1_fu_638_p0;
wire   [25:0] offsetB_fu_536_p3;
wire  signed [25:0] or_ln196_fu_644_p2;
wire   [11:0] mul_ln196_fu_654_p1;
wire   [11:0] mul_ln196_1_fu_660_p0;
wire  signed [28:0] sext_ln192_2_fu_687_p1;
wire  signed [28:0] sext_ln192_1_fu_684_p1;
wire   [27:0] add_ln192_4_fu_690_p2;
wire   [28:0] add_ln192_fu_694_p2;
wire  signed [28:0] grp_fu_947_p3;
wire  signed [29:0] sext_ln192_5_fu_711_p1;
wire  signed [29:0] sext_ln192_4_fu_704_p1;
wire   [29:0] add_ln192_2_fu_714_p2;
wire  signed [28:0] sext_ln194_2_fu_733_p1;
wire  signed [28:0] sext_ln194_1_fu_730_p1;
wire   [27:0] add_ln194_4_fu_736_p2;
wire   [28:0] add_ln194_fu_740_p2;
wire  signed [28:0] grp_fu_957_p3;
wire  signed [29:0] sext_ln194_5_fu_757_p1;
wire  signed [29:0] sext_ln194_4_fu_750_p1;
wire   [29:0] add_ln194_2_fu_760_p2;
wire  signed [28:0] sext_ln196_2_fu_779_p1;
wire  signed [28:0] sext_ln196_1_fu_776_p1;
wire   [27:0] add_ln196_4_fu_782_p2;
wire   [28:0] add_ln196_fu_786_p2;
wire  signed [28:0] grp_fu_967_p3;
wire  signed [29:0] sext_ln196_5_fu_803_p1;
wire  signed [29:0] sext_ln196_4_fu_796_p1;
wire   [29:0] add_ln196_2_fu_806_p2;
wire   [17:0] Rres_fu_720_p4;
wire   [17:0] zext_ln110_fu_676_p1;
wire   [17:0] zext_ln110_1_fu_680_p1;
wire   [17:0] Gres_fu_766_p4;
wire   [17:0] Bres_fu_812_p4;
wire   [23:0] add_ln192_3_fu_858_p2;
wire   [11:0] trunc_ln_fu_870_p4;
wire   [11:0] select_ln198_fu_880_p3;
wire   [23:0] add_ln194_3_fu_862_p2;
wire   [23:0] add_ln196_3_fu_866_p2;
wire   [11:0] trunc_ln2_fu_902_p4;
wire   [11:0] select_ln200_fu_912_p3;
wire   [11:0] trunc_ln1_fu_892_p4;
wire   [11:0] select_ln199_fu_924_p3;
wire   [11:0] select_ln200_1_fu_918_p3;
wire   [11:0] select_ln199_1_fu_930_p3;
wire   [11:0] select_ln198_1_fu_886_p3;
wire   [11:0] grp_fu_947_p0;
wire   [11:0] grp_fu_957_p0;
wire   [11:0] grp_fu_967_p0;
reg    grp_fu_947_ce;
reg    grp_fu_957_ce;
reg    grp_fu_967_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 x_fu_136 = 13'd0;
#0 ap_done_reg = 1'b0;
end

bd_d92b_csc_0_mul_16s_12ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12ns_28_1_1_U92(
    .din0(coef11_fu_501_p3),
    .din1(mul_ln192_fu_610_p1),
    .dout(mul_ln192_fu_610_p2)
);

bd_d92b_csc_0_mul_12ns_16s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_12ns_16s_28_1_1_U93(
    .din0(mul_ln192_1_fu_616_p0),
    .din1(coef12_fu_506_p3),
    .dout(mul_ln192_1_fu_616_p2)
);

bd_d92b_csc_0_mul_16s_12ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12ns_28_1_1_U94(
    .din0(coef21_fu_511_p3),
    .din1(mul_ln194_fu_632_p1),
    .dout(mul_ln194_fu_632_p2)
);

bd_d92b_csc_0_mul_12ns_16s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_12ns_16s_28_1_1_U95(
    .din0(mul_ln194_1_fu_638_p0),
    .din1(coef22_fu_516_p3),
    .dout(mul_ln194_1_fu_638_p2)
);

bd_d92b_csc_0_mul_16s_12ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12ns_28_1_1_U96(
    .din0(coef31_fu_521_p3),
    .din1(mul_ln196_fu_654_p1),
    .dout(mul_ln196_fu_654_p2)
);

bd_d92b_csc_0_mul_12ns_16s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_12ns_16s_28_1_1_U97(
    .din0(mul_ln196_1_fu_660_p0),
    .din1(coef32_fu_526_p3),
    .dout(mul_ln196_1_fu_660_p2)
);

bd_d92b_csc_0_mac_muladd_12ns_16s_26s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 29 ))
mac_muladd_12ns_16s_26s_29_4_1_U98(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_947_p0),
    .din1(coef13_fu_460_p3),
    .din2(or_ln192_fu_600_p2),
    .ce(grp_fu_947_ce),
    .dout(grp_fu_947_p3)
);

bd_d92b_csc_0_mac_muladd_12ns_16s_26s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 29 ))
mac_muladd_12ns_16s_26s_29_4_1_U99(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_957_p0),
    .din1(coef23_fu_465_p3),
    .din2(or_ln194_fu_622_p2),
    .ce(grp_fu_957_ce),
    .dout(grp_fu_957_p3)
);

bd_d92b_csc_0_mac_muladd_12ns_16s_26s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 29 ))
mac_muladd_12ns_16s_26s_29_4_1_U100(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_967_p0),
    .din1(coef33_fu_470_p3),
    .din2(or_ln196_fu_644_p2),
    .ce(grp_fu_967_ce),
    .dout(grp_fu_967_p3)
);

bd_d92b_csc_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln136_fu_359_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_136 <= x_3_fu_435_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_136 <= 13'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Gpix_reg_1151 <= {{stream_in_dout[23:12]}};
        Rpix_reg_1146 <= Rpix_fu_446_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        or_ln150_2_reg_1128 <= or_ln150_2_fu_429_p2;
        or_ln150_2_reg_1128_pp0_iter1_reg <= or_ln150_2_reg_1128;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Gpix_reg_1151_pp0_iter2_reg <= Gpix_reg_1151;
        Rpix_reg_1146_pp0_iter2_reg <= Rpix_reg_1146;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln198_1_reg_1278 <= icmp_ln198_1_fu_828_p2;
        icmp_ln198_reg_1273 <= icmp_ln198_fu_822_p2;
        icmp_ln199_1_reg_1288 <= icmp_ln199_1_fu_840_p2;
        icmp_ln199_reg_1283 <= icmp_ln199_fu_834_p2;
        icmp_ln200_1_reg_1298 <= icmp_ln200_1_fu_852_p2;
        icmp_ln200_reg_1293 <= icmp_ln200_fu_846_p2;
        max_val_reg_1229 <= max_val_fu_666_p3;
        min_val_reg_1236 <= min_val_fu_671_p3;
        mul_ln192_1_reg_1189 <= mul_ln192_1_fu_616_p2;
        mul_ln192_reg_1183 <= mul_ln192_fu_610_p2;
        mul_ln194_1_reg_1206 <= mul_ln194_1_fu_638_p2;
        mul_ln194_reg_1200 <= mul_ln194_fu_632_p2;
        mul_ln196_1_reg_1223 <= mul_ln196_1_fu_660_p2;
        mul_ln196_reg_1217 <= mul_ln196_fu_654_p2;
        or_ln150_2_reg_1128_pp0_iter2_reg <= or_ln150_2_reg_1128_pp0_iter1_reg;
        or_ln150_2_reg_1128_pp0_iter3_reg <= or_ln150_2_reg_1128_pp0_iter2_reg;
        trunc_ln192_1_reg_1248 <= trunc_ln192_1_fu_708_p1;
        trunc_ln192_reg_1243 <= trunc_ln192_fu_700_p1;
        trunc_ln194_1_reg_1258 <= trunc_ln194_1_fu_754_p1;
        trunc_ln194_reg_1253 <= trunc_ln194_fu_746_p1;
        trunc_ln196_1_reg_1268 <= trunc_ln196_1_fu_800_p1;
        trunc_ln196_reg_1263 <= trunc_ln196_fu_792_p1;
    end
end

always @ (*) begin
    if (((icmp_ln136_fu_359_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_2 = 13'd1;
    end else begin
        ap_sig_allocacmp_x_2 = x_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_947_ce = 1'b1;
    end else begin
        grp_fu_947_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_957_ce = 1'b1;
    end else begin
        grp_fu_957_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_967_ce = 1'b1;
    end else begin
        grp_fu_967_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        stream_csc_blk_n = stream_csc_full_n;
    end else begin
        stream_csc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        stream_csc_write = 1'b1;
    end else begin
        stream_csc_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_blk_n = stream_in_empty_n;
    end else begin
        stream_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_read = 1'b1;
    end else begin
        stream_in_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Bres_fu_812_p4 = {{add_ln196_2_fu_806_p2[29:12]}};

assign Gres_fu_766_p4 = {{add_ln194_2_fu_760_p2[29:12]}};

assign Rpix_fu_446_p1 = stream_in_dout[11:0];

assign Rres_fu_720_p4 = {{add_ln192_2_fu_714_p2[29:12]}};

assign add_ln192_2_fu_714_p2 = ($signed(sext_ln192_5_fu_711_p1) + $signed(sext_ln192_4_fu_704_p1));

assign add_ln192_3_fu_858_p2 = (trunc_ln192_1_reg_1248 + trunc_ln192_reg_1243);

assign add_ln192_4_fu_690_p2 = ($signed(mul_ln192_1_reg_1189) + $signed(mul_ln192_reg_1183));

assign add_ln192_fu_694_p2 = ($signed(sext_ln192_2_fu_687_p1) + $signed(sext_ln192_1_fu_684_p1));

assign add_ln194_2_fu_760_p2 = ($signed(sext_ln194_5_fu_757_p1) + $signed(sext_ln194_4_fu_750_p1));

assign add_ln194_3_fu_862_p2 = (trunc_ln194_1_reg_1258 + trunc_ln194_reg_1253);

assign add_ln194_4_fu_736_p2 = ($signed(mul_ln194_1_reg_1206) + $signed(mul_ln194_reg_1200));

assign add_ln194_fu_740_p2 = ($signed(sext_ln194_2_fu_733_p1) + $signed(sext_ln194_1_fu_730_p1));

assign add_ln196_2_fu_806_p2 = ($signed(sext_ln196_5_fu_803_p1) + $signed(sext_ln196_4_fu_796_p1));

assign add_ln196_3_fu_866_p2 = (trunc_ln196_1_reg_1268 + trunc_ln196_reg_1263);

assign add_ln196_4_fu_782_p2 = ($signed(mul_ln196_1_reg_1223) + $signed(mul_ln196_reg_1217));

assign add_ln196_fu_786_p2 = ($signed(sext_ln196_2_fu_779_p1) + $signed(sext_ln196_1_fu_776_p1));

assign and_ln149_fu_399_p2 = (icmp_ln149_fu_387_p2 & icmp_ln149_1_fu_393_p2);

assign and_ln150_fu_417_p2 = (xor_ln150_fu_411_p2 & or_ln148_fu_381_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (stream_in_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = (stream_csc_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign coef11_fu_501_p3 = ((or_ln150_2_reg_1128_pp0_iter2_reg[0:0] == 1'b1) ? K11_read : K11_2_read);

assign coef12_fu_506_p3 = ((or_ln150_2_reg_1128_pp0_iter2_reg[0:0] == 1'b1) ? K12_read : K12_2_read);

assign coef13_fu_460_p3 = ((or_ln150_2_reg_1128[0:0] == 1'b1) ? K13_read : K13_2_read);

assign coef21_fu_511_p3 = ((or_ln150_2_reg_1128_pp0_iter2_reg[0:0] == 1'b1) ? K21_read : K21_2_read);

assign coef22_fu_516_p3 = ((or_ln150_2_reg_1128_pp0_iter2_reg[0:0] == 1'b1) ? K22_read : K22_2_read);

assign coef23_fu_465_p3 = ((or_ln150_2_reg_1128[0:0] == 1'b1) ? K23_read : K23_2_read);

assign coef31_fu_521_p3 = ((or_ln150_2_reg_1128_pp0_iter2_reg[0:0] == 1'b1) ? K31_read : K31_2_read);

assign coef32_fu_526_p3 = ((or_ln150_2_reg_1128_pp0_iter2_reg[0:0] == 1'b1) ? K32_read : K32_2_read);

assign coef33_fu_470_p3 = ((or_ln150_2_reg_1128[0:0] == 1'b1) ? K33_read : K33_2_read);

assign grp_fu_947_p0 = zext_ln106_2_fu_497_p1;

assign grp_fu_957_p0 = zext_ln106_2_fu_497_p1;

assign grp_fu_967_p0 = zext_ln106_2_fu_497_p1;

assign icmp_ln136_fu_359_p2 = ((ap_sig_allocacmp_x_2 == add_ln134) ? 1'b1 : 1'b0);

assign icmp_ln148_1_fu_375_p2 = ((zext_ln136_fu_365_p1 == ColEnd_read) ? 1'b1 : 1'b0);

assign icmp_ln148_fu_369_p2 = ((zext_ln136_fu_365_p1 != ColStart_read) ? 1'b1 : 1'b0);

assign icmp_ln149_1_fu_393_p2 = (($signed(zext_ln136_fu_365_p1) < $signed(ColEnd_read)) ? 1'b1 : 1'b0);

assign icmp_ln149_fu_387_p2 = (($signed(zext_ln136_fu_365_p1) > $signed(ColStart_read)) ? 1'b1 : 1'b0);

assign icmp_ln198_1_fu_828_p2 = (($signed(Rres_fu_720_p4) > $signed(zext_ln110_1_fu_680_p1)) ? 1'b1 : 1'b0);

assign icmp_ln198_fu_822_p2 = (($signed(Rres_fu_720_p4) < $signed(zext_ln110_fu_676_p1)) ? 1'b1 : 1'b0);

assign icmp_ln199_1_fu_840_p2 = (($signed(Gres_fu_766_p4) > $signed(zext_ln110_1_fu_680_p1)) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_834_p2 = (($signed(Gres_fu_766_p4) < $signed(zext_ln110_fu_676_p1)) ? 1'b1 : 1'b0);

assign icmp_ln200_1_fu_852_p2 = (($signed(Bres_fu_812_p4) > $signed(zext_ln110_1_fu_680_p1)) ? 1'b1 : 1'b0);

assign icmp_ln200_fu_846_p2 = (($signed(Bres_fu_812_p4) < $signed(zext_ln110_fu_676_p1)) ? 1'b1 : 1'b0);

assign max_val_fu_666_p3 = ((or_ln150_2_reg_1128_pp0_iter3_reg[0:0] == 1'b1) ? ClipMax_read : ClipMax_2_read);

assign min_val_fu_671_p3 = ((or_ln150_2_reg_1128_pp0_iter3_reg[0:0] == 1'b1) ? ClampMin_read : ClampMin_2_read);

assign mul_ln192_1_fu_616_p0 = zext_ln106_1_fu_597_p1;

assign mul_ln192_fu_610_p1 = zext_ln106_fu_594_p1;

assign mul_ln194_1_fu_638_p0 = zext_ln106_1_fu_597_p1;

assign mul_ln194_fu_632_p1 = zext_ln106_fu_594_p1;

assign mul_ln196_1_fu_660_p0 = zext_ln106_1_fu_597_p1;

assign mul_ln196_fu_654_p1 = zext_ln106_fu_594_p1;

assign offsetB_fu_536_p3 = {{select_ln150_11_fu_531_p3}, {12'd0}};

assign offsetG_fu_549_p3 = {{select_ln150_12_fu_544_p3}, {12'd0}};

assign offsetR_fu_562_p3 = {{select_ln150_13_fu_557_p3}, {12'd0}};

assign or_ln148_fu_381_p2 = (icmp_ln148_fu_369_p2 | icmp_ln148_1_fu_375_p2);

assign or_ln150_1_fu_423_p2 = (cmp20_not | and_ln150_fu_417_p2);

assign or_ln150_2_fu_429_p2 = (or_ln150_1_fu_423_p2 | cmp17_not);

assign or_ln150_fu_405_p2 = (icmp_ln148_1_fu_375_p2 | and_ln149_fu_399_p2);

assign or_ln192_fu_600_p2 = (offsetR_fu_562_p3 | 26'd2048);

assign or_ln194_fu_622_p2 = (offsetG_fu_549_p3 | 26'd2048);

assign or_ln196_fu_644_p2 = (offsetB_fu_536_p3 | 26'd2048);

assign select_ln150_11_fu_531_p3 = ((or_ln150_2_reg_1128_pp0_iter2_reg[0:0] == 1'b1) ? BOffset_read : BOffset_2_read);

assign select_ln150_12_fu_544_p3 = ((or_ln150_2_reg_1128_pp0_iter2_reg[0:0] == 1'b1) ? GOffset_read : GOffset_2_read);

assign select_ln150_13_fu_557_p3 = ((or_ln150_2_reg_1128_pp0_iter2_reg[0:0] == 1'b1) ? ROffset_read : ROffset_2_read);

assign select_ln198_1_fu_886_p3 = ((icmp_ln198_reg_1273[0:0] == 1'b1) ? min_val_reg_1236 : select_ln198_fu_880_p3);

assign select_ln198_fu_880_p3 = ((icmp_ln198_1_reg_1278[0:0] == 1'b1) ? max_val_reg_1229 : trunc_ln_fu_870_p4);

assign select_ln199_1_fu_930_p3 = ((icmp_ln199_reg_1283[0:0] == 1'b1) ? min_val_reg_1236 : select_ln199_fu_924_p3);

assign select_ln199_fu_924_p3 = ((icmp_ln199_1_reg_1288[0:0] == 1'b1) ? max_val_reg_1229 : trunc_ln1_fu_892_p4);

assign select_ln200_1_fu_918_p3 = ((icmp_ln200_reg_1293[0:0] == 1'b1) ? min_val_reg_1236 : select_ln200_fu_912_p3);

assign select_ln200_fu_912_p3 = ((icmp_ln200_1_reg_1298[0:0] == 1'b1) ? max_val_reg_1229 : trunc_ln2_fu_902_p4);

assign sext_ln192_1_fu_684_p1 = mul_ln192_reg_1183;

assign sext_ln192_2_fu_687_p1 = mul_ln192_1_reg_1189;

assign sext_ln192_4_fu_704_p1 = $signed(add_ln192_fu_694_p2);

assign sext_ln192_5_fu_711_p1 = grp_fu_947_p3;

assign sext_ln194_1_fu_730_p1 = mul_ln194_reg_1200;

assign sext_ln194_2_fu_733_p1 = mul_ln194_1_reg_1206;

assign sext_ln194_4_fu_750_p1 = $signed(add_ln194_fu_740_p2);

assign sext_ln194_5_fu_757_p1 = grp_fu_957_p3;

assign sext_ln196_1_fu_776_p1 = mul_ln196_reg_1217;

assign sext_ln196_2_fu_779_p1 = mul_ln196_1_reg_1223;

assign sext_ln196_4_fu_796_p1 = $signed(add_ln196_fu_786_p2);

assign sext_ln196_5_fu_803_p1 = grp_fu_967_p3;

assign stream_csc_din = {{{select_ln200_1_fu_918_p3}, {select_ln199_1_fu_930_p3}}, {select_ln198_1_fu_886_p3}};

assign tmp_fu_487_p4 = {{stream_in_dout[35:24]}};

assign trunc_ln192_1_fu_708_p1 = grp_fu_947_p3[23:0];

assign trunc_ln192_fu_700_p1 = add_ln192_4_fu_690_p2[23:0];

assign trunc_ln194_1_fu_754_p1 = grp_fu_957_p3[23:0];

assign trunc_ln194_fu_746_p1 = add_ln194_4_fu_736_p2[23:0];

assign trunc_ln196_1_fu_800_p1 = grp_fu_967_p3[23:0];

assign trunc_ln196_fu_792_p1 = add_ln196_4_fu_782_p2[23:0];

assign trunc_ln1_fu_892_p4 = {{add_ln194_3_fu_862_p2[23:12]}};

assign trunc_ln2_fu_902_p4 = {{add_ln196_3_fu_866_p2[23:12]}};

assign trunc_ln_fu_870_p4 = {{add_ln192_3_fu_858_p2[23:12]}};

assign x_3_fu_435_p2 = (ap_sig_allocacmp_x_2 + 13'd1);

assign xor_ln150_fu_411_p2 = (or_ln150_fu_405_p2 ^ 1'd1);

assign zext_ln106_1_fu_597_p1 = Gpix_reg_1151_pp0_iter2_reg;

assign zext_ln106_2_fu_497_p1 = tmp_fu_487_p4;

assign zext_ln106_fu_594_p1 = Rpix_reg_1146_pp0_iter2_reg;

assign zext_ln110_1_fu_680_p1 = max_val_fu_666_p3;

assign zext_ln110_fu_676_p1 = min_val_fu_671_p3;

assign zext_ln136_fu_365_p1 = ap_sig_allocacmp_x_2;

endmodule //bd_d92b_csc_0_v_csc_core_Pipeline_VITIS_LOOP_136_2
