-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bckgndYUV_dout : IN STD_LOGIC_VECTOR (35 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_empty_n : IN STD_LOGIC;
    bckgndYUV_read : OUT STD_LOGIC;
    ovrlayYUV_din : OUT STD_LOGIC_VECTOR (35 downto 0);
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_full_n : IN STD_LOGIC;
    ovrlayYUV_write : OUT STD_LOGIC;
    boxHCoord_loc_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorB : IN STD_LOGIC_VECTOR (11 downto 0);
    pixOut : IN STD_LOGIC_VECTOR (11 downto 0);
    boxColorR : IN STD_LOGIC_VECTOR (11 downto 0);
    and4_i : IN STD_LOGIC_VECTOR (0 downto 0);
    and26_i : IN STD_LOGIC_VECTOR (0 downto 0);
    tobool : IN STD_LOGIC_VECTOR (0 downto 0);
    and10_i : IN STD_LOGIC_VECTOR (0 downto 0);
    patternId_val_load : IN STD_LOGIC_VECTOR (7 downto 0);
    boxSize : IN STD_LOGIC_VECTOR (15 downto 0);
    y : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln1914 : IN STD_LOGIC_VECTOR (7 downto 0);
    vMax : IN STD_LOGIC_VECTOR (15 downto 0);
    hMax : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln1914_1 : IN STD_LOGIC_VECTOR (8 downto 0);
    icmp : IN STD_LOGIC_VECTOR (0 downto 0);
    boxColorG : IN STD_LOGIC_VECTOR (11 downto 0);
    crossHairX : IN STD_LOGIC_VECTOR (15 downto 0);
    cmp2_i : IN STD_LOGIC_VECTOR (0 downto 0);
    color : IN STD_LOGIC_VECTOR (7 downto 0);
    boxHCoord_loc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_loc_1_out_ap_vld : OUT STD_LOGIC;
    boxVCoord_loc_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_1_out_ap_vld : OUT STD_LOGIC;
    boxHCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_ap_vld : OUT STD_LOGIC;
    boxVCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_ap_vld : OUT STD_LOGIC );
end;


architecture behav of design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv12_F00 : STD_LOGIC_VECTOR (11 downto 0) := "111100000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln774_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln774_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal vDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal whiYuv_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal whiYuv_2_ce0 : STD_LOGIC;
    signal whiYuv_2_q0 : STD_LOGIC_VECTOR (11 downto 0);
    signal ovrlayYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal bckgndYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal color_read_reg_790 : STD_LOGIC_VECTOR (7 downto 0);
    signal patternId_val_load_read_reg_837 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1914_1_cast_fu_408_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1914_1_cast_reg_885 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1914_cast_fu_412_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1914_cast_reg_891 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_1_reg_899 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxVCoord_loc_1_load_reg_905 : STD_LOGIC_VECTOR (15 downto 0);
    signal boxHCoord_loc_1_load_reg_910 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln774_reg_915_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln774_fu_451_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln774_reg_919 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1884_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal hDir_load_load_fu_466_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1889_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1894_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal vDir_load_load_fu_492_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1901_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1906_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_reg_952 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_reg_952_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1975_fu_586_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal pixIn_fu_599_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal and_ln1942_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_7_fu_693_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_mux_empty_92_phi_fu_309_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_92_reg_306 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_91_phi_fu_326_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_91_reg_323 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_phi_ln1975_reg_340 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter1_phi_ln1975_reg_340 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter2_phi_ln1975_reg_340 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_mux_pix_4_phi_fu_354_p12 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_4_reg_351 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_4_reg_351 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_4_reg_351 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_4_reg_351 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_mux_pix_3_phi_fu_372_p12 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_3_reg_368 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_3_reg_368 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_3_reg_368 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_3_reg_368 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_mux_pix_phi_fu_392_p12 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_reg_388 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_reg_388 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_reg_388 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter3_pix_reg_388 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1975_fu_699_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln1911_fu_528_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln1915_fu_552_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_fu_136 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal x_2_fu_445_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal boxVCoord_loc_1_fu_140 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal boxHCoord_loc_1_fu_144 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal or_ln1884_fu_455_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1914_fu_518_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1912_fu_523_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln1918_fu_542_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1916_fu_547_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1963_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1932_fu_639_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxBottom_fu_634_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1937_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxRight_fu_629_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1937_1_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1937_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1932_fu_644_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1932_1_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1942_1_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1942_2_fu_671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1947_fu_689_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixOut_12_fu_711_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal pixOut_11_fu_704_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln1991_fu_732_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal pixOut_13_fu_718_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal empty_fu_739_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal pixOut_14_fu_725_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_350 : BOOLEAN;
    signal ap_condition_354 : BOOLEAN;
    signal ap_condition_227 : BOOLEAN;
    signal ap_condition_372 : BOOLEAN;
    signal ap_condition_677 : BOOLEAN;
    signal ap_condition_414 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2_whiYuv_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component design_1_v_tpg_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    whiYuv_2_U : component design_1_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_774_2_whiYuv_2_ROM_AUTO_1R
    generic map (
        DataWidth => 12,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => whiYuv_2_address0,
        ce0 => whiYuv_2_ce0,
        q0 => whiYuv_2_q0);

    flow_control_loop_pipe_sequential_init_U : component design_1_v_tpg_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_phi_ln1975_reg_340_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_227)) then
                if ((ap_const_boolean_1 = ap_condition_354)) then 
                    ap_phi_reg_pp0_iter2_phi_ln1975_reg_340 <= ap_const_lv2_1;
                elsif ((ap_const_boolean_1 = ap_condition_350)) then 
                    ap_phi_reg_pp0_iter2_phi_ln1975_reg_340 <= select_ln1975_fu_586_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_phi_ln1975_reg_340 <= ap_phi_reg_pp0_iter1_phi_ln1975_reg_340;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_3_reg_368_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_227)) then
                if ((ap_const_boolean_1 = ap_condition_372)) then 
                    ap_phi_reg_pp0_iter2_pix_3_reg_368 <= ap_const_lv12_F00;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_3_reg_368 <= ap_phi_reg_pp0_iter1_pix_3_reg_368;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_4_reg_351_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_227)) then
                if ((ap_const_boolean_1 = ap_condition_372)) then 
                    ap_phi_reg_pp0_iter2_pix_4_reg_351 <= pixOut;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_4_reg_351 <= ap_phi_reg_pp0_iter1_pix_4_reg_351;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_reg_388_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_227)) then
                if ((ap_const_boolean_1 = ap_condition_372)) then 
                    ap_phi_reg_pp0_iter2_pix_reg_388 <= ap_const_lv12_F00;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_pix_reg_388 <= ap_phi_reg_pp0_iter1_pix_reg_388;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_3_reg_368_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln1942_fu_683_p2) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter3_pix_3_reg_368 <= pixOut_7_fu_693_p3;
            elsif (((not((patternId_val_load_read_reg_837 = ap_const_lv8_2)) and not((patternId_val_load_read_reg_837 = ap_const_lv8_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (or_ln1963_reg_952 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln1942_fu_683_p2) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)))) then 
                ap_phi_reg_pp0_iter3_pix_3_reg_368 <= bckgndYUV_dout(23 downto 12);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_3_reg_368 <= ap_phi_reg_pp0_iter2_pix_3_reg_368;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_4_reg_351_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln1942_fu_683_p2) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter3_pix_4_reg_351 <= boxColorB;
            elsif (((not((patternId_val_load_read_reg_837 = ap_const_lv8_2)) and not((patternId_val_load_read_reg_837 = ap_const_lv8_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (or_ln1963_reg_952 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln1942_fu_683_p2) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)))) then 
                ap_phi_reg_pp0_iter3_pix_4_reg_351 <= bckgndYUV_dout(35 downto 24);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_4_reg_351 <= ap_phi_reg_pp0_iter2_pix_4_reg_351;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_pix_reg_388_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln1942_fu_683_p2) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter3_pix_reg_388 <= boxColorR;
            elsif (((not((patternId_val_load_read_reg_837 = ap_const_lv8_2)) and not((patternId_val_load_read_reg_837 = ap_const_lv8_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (or_ln1963_reg_952 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_0 = and_ln1942_fu_683_p2) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)))) then 
                ap_phi_reg_pp0_iter3_pix_reg_388 <= pixIn_fu_599_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                ap_phi_reg_pp0_iter3_pix_reg_388 <= ap_phi_reg_pp0_iter2_pix_reg_388;
            end if; 
        end if;
    end process;

    boxHCoord_loc_1_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    boxHCoord_loc_1_fu_144 <= boxHCoord_loc_0;
                elsif ((ap_const_boolean_1 = ap_condition_677)) then 
                    boxHCoord_loc_1_fu_144 <= select_ln1911_fu_528_p3;
                end if;
            end if; 
        end if;
    end process;

    boxVCoord_loc_1_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    boxVCoord_loc_1_fu_140 <= boxVCoord_loc_0;
                elsif ((ap_const_boolean_1 = ap_condition_677)) then 
                    boxVCoord_loc_1_fu_140 <= select_ln1915_fu_552_p3;
                end if;
            end if; 
        end if;
    end process;

    hDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_414)) then
                if (((icmp_ln1894_fu_481_p2 = ap_const_lv1_1) and (hDir_load_load_fu_466_p1 = ap_const_lv1_1))) then 
                    hDir <= ap_const_lv1_0;
                elsif (((icmp_ln1889_fu_470_p2 = ap_const_lv1_1) and (hDir_load_load_fu_466_p1 = ap_const_lv1_0))) then 
                    hDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    vDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_414)) then
                if (((icmp_ln1906_fu_507_p2 = ap_const_lv1_1) and (vDir_load_load_fu_492_p1 = ap_const_lv1_1))) then 
                    vDir <= ap_const_lv1_0;
                elsif (((icmp_ln1901_fu_496_p2 = ap_const_lv1_1) and (vDir_load_load_fu_492_p1 = ap_const_lv1_0))) then 
                    vDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    x_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_136 <= ap_const_lv16_0;
                elsif (((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    x_fu_136 <= x_2_fu_445_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln774_reg_915 <= icmp_ln774_fu_440_p2;
                or_ln1963_reg_952 <= or_ln1963_fu_581_p2;
                trunc_ln774_reg_919 <= trunc_ln774_fu_451_p1;
                x_1_reg_899 <= x_fu_136;
                    zext_ln1914_1_cast_reg_885(8 downto 0) <= zext_ln1914_1_cast_fu_408_p1(8 downto 0);
                    zext_ln1914_cast_reg_891(7 downto 0) <= zext_ln1914_cast_fu_412_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_phi_ln1975_reg_340 <= ap_phi_reg_pp0_iter0_phi_ln1975_reg_340;
                ap_phi_reg_pp0_iter1_pix_3_reg_368 <= ap_phi_reg_pp0_iter0_pix_3_reg_368;
                ap_phi_reg_pp0_iter1_pix_4_reg_351 <= ap_phi_reg_pp0_iter0_pix_4_reg_351;
                ap_phi_reg_pp0_iter1_pix_reg_388 <= ap_phi_reg_pp0_iter0_pix_reg_388;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                boxHCoord_loc_1_load_reg_910 <= boxHCoord_loc_1_fu_144;
                boxVCoord_loc_1_load_reg_905 <= boxVCoord_loc_1_fu_140;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln774_reg_915_pp0_iter2_reg <= icmp_ln774_reg_915;
                or_ln1963_reg_952_pp0_iter2_reg <= or_ln1963_reg_952;
            end if;
        end if;
    end process;
    zext_ln1914_1_cast_reg_885(15 downto 9) <= "0000000";
    zext_ln1914_cast_reg_891(15 downto 8) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1912_fu_523_p2 <= std_logic_vector(unsigned(boxHCoord_loc_1_fu_144) + unsigned(zext_ln1914_cast_reg_891));
    add_ln1916_fu_547_p2 <= std_logic_vector(unsigned(boxVCoord_loc_1_fu_140) + unsigned(zext_ln1914_cast_reg_891));
    and_ln1942_1_fu_677_p2 <= (xor_ln1932_fu_644_p2 and icmp_ln1932_1_fu_650_p2);
    and_ln1942_2_fu_671_p2 <= (xor_ln1937_fu_660_p2 and icmp_ln1937_1_fu_666_p2);
    and_ln1942_fu_683_p2 <= (and_ln1942_2_fu_671_p2 and and_ln1942_1_fu_677_p2);
    and_ln1947_fu_689_p2 <= (trunc_ln774_reg_919 and icmp);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state3_pp0_stage0_iter2, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state3_pp0_stage0_iter2, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_state3_pp0_stage0_iter2, ap_block_state4_pp0_stage0_iter3)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(bckgndYUV_empty_n, icmp_ln774_reg_915)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln774_reg_915 = ap_const_lv1_0) and (bckgndYUV_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(ovrlayYUV_full_n)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (ovrlayYUV_full_n = ap_const_logic_0);
    end process;


    ap_condition_227_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_227 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_350_assign_proc : process(icmp_ln774_fu_440_p2, color_read_reg_790, patternId_val_load_read_reg_837, or_ln1963_fu_581_p2)
    begin
                ap_condition_350 <= (not((color_read_reg_790 = ap_const_lv8_1)) and not((color_read_reg_790 = ap_const_lv8_0)) and (icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (or_ln1963_fu_581_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_2));
    end process;


    ap_condition_354_assign_proc : process(icmp_ln774_fu_440_p2, color_read_reg_790, patternId_val_load_read_reg_837, or_ln1963_fu_581_p2)
    begin
                ap_condition_354 <= ((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (or_ln1963_fu_581_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_2) and (color_read_reg_790 = ap_const_lv8_1));
    end process;


    ap_condition_372_assign_proc : process(icmp_ln774_fu_440_p2, color_read_reg_790, patternId_val_load_read_reg_837, or_ln1963_fu_581_p2)
    begin
                ap_condition_372 <= ((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (or_ln1963_fu_581_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_2) and (color_read_reg_790 = ap_const_lv8_0));
    end process;


    ap_condition_414_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln774_fu_440_p2, ap_block_pp0_stage0_11001, patternId_val_load_read_reg_837, icmp_ln1884_fu_460_p2)
    begin
                ap_condition_414 <= ((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_837 = ap_const_lv8_1));
    end process;


    ap_condition_677_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln774_fu_440_p2, patternId_val_load_read_reg_837, icmp_ln1884_fu_460_p2)
    begin
                ap_condition_677 <= ((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln774_fu_440_p2)
    begin
        if (((icmp_ln774_fu_440_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_empty_91_phi_fu_326_p8_assign_proc : process(icmp_ln774_fu_440_p2, patternId_val_load_read_reg_837, icmp_ln1884_fu_460_p2, vDir_load_load_fu_492_p1, icmp_ln1901_fu_496_p2, icmp_ln1906_fu_507_p2, ap_phi_reg_pp0_iter1_empty_91_reg_323)
    begin
        if ((((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (icmp_ln1906_fu_507_p2 = ap_const_lv1_0) and (vDir_load_load_fu_492_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)) or ((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (icmp_ln1901_fu_496_p2 = ap_const_lv1_1) and (vDir_load_load_fu_492_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_91_phi_fu_326_p8 <= ap_const_lv1_1;
        elsif ((((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (icmp_ln1901_fu_496_p2 = ap_const_lv1_0) and (vDir_load_load_fu_492_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)) or ((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (icmp_ln1906_fu_507_p2 = ap_const_lv1_1) and (vDir_load_load_fu_492_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_91_phi_fu_326_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_91_phi_fu_326_p8 <= ap_phi_reg_pp0_iter1_empty_91_reg_323;
        end if; 
    end process;


    ap_phi_mux_empty_92_phi_fu_309_p8_assign_proc : process(icmp_ln774_fu_440_p2, patternId_val_load_read_reg_837, icmp_ln1884_fu_460_p2, hDir_load_load_fu_466_p1, icmp_ln1889_fu_470_p2, icmp_ln1894_fu_481_p2, ap_phi_reg_pp0_iter1_empty_92_reg_306)
    begin
        if ((((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (icmp_ln1894_fu_481_p2 = ap_const_lv1_0) and (hDir_load_load_fu_466_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)) or ((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (icmp_ln1889_fu_470_p2 = ap_const_lv1_1) and (hDir_load_load_fu_466_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_92_phi_fu_309_p8 <= ap_const_lv1_1;
        elsif ((((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (icmp_ln1889_fu_470_p2 = ap_const_lv1_0) and (hDir_load_load_fu_466_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)) or ((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (icmp_ln1894_fu_481_p2 = ap_const_lv1_1) and (hDir_load_load_fu_466_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (patternId_val_load_read_reg_837 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_92_phi_fu_309_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_92_phi_fu_309_p8 <= ap_phi_reg_pp0_iter1_empty_92_reg_306;
        end if; 
    end process;


    ap_phi_mux_pix_3_phi_fu_372_p12_assign_proc : process(whiYuv_2_q0, color_read_reg_790, patternId_val_load_read_reg_837, icmp_ln774_reg_915_pp0_iter2_reg, or_ln1963_reg_952_pp0_iter2_reg, ap_phi_reg_pp0_iter3_pix_3_reg_368)
    begin
        if ((not((color_read_reg_790 = ap_const_lv8_0)) and (or_ln1963_reg_952_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln774_reg_915_pp0_iter2_reg = ap_const_lv1_0) and (patternId_val_load_read_reg_837 = ap_const_lv8_2))) then 
            ap_phi_mux_pix_3_phi_fu_372_p12 <= whiYuv_2_q0;
        else 
            ap_phi_mux_pix_3_phi_fu_372_p12 <= ap_phi_reg_pp0_iter3_pix_3_reg_368;
        end if; 
    end process;


    ap_phi_mux_pix_4_phi_fu_354_p12_assign_proc : process(pixOut, color_read_reg_790, patternId_val_load_read_reg_837, icmp_ln774_reg_915_pp0_iter2_reg, or_ln1963_reg_952_pp0_iter2_reg, ap_phi_reg_pp0_iter3_pix_4_reg_351)
    begin
        if ((not((color_read_reg_790 = ap_const_lv8_0)) and (or_ln1963_reg_952_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln774_reg_915_pp0_iter2_reg = ap_const_lv1_0) and (patternId_val_load_read_reg_837 = ap_const_lv8_2))) then 
            ap_phi_mux_pix_4_phi_fu_354_p12 <= pixOut;
        else 
            ap_phi_mux_pix_4_phi_fu_354_p12 <= ap_phi_reg_pp0_iter3_pix_4_reg_351;
        end if; 
    end process;


    ap_phi_mux_pix_phi_fu_392_p12_assign_proc : process(color_read_reg_790, patternId_val_load_read_reg_837, icmp_ln774_reg_915_pp0_iter2_reg, or_ln1963_reg_952_pp0_iter2_reg, ap_phi_reg_pp0_iter3_pix_reg_388)
    begin
        if ((not((color_read_reg_790 = ap_const_lv8_0)) and (or_ln1963_reg_952_pp0_iter2_reg = ap_const_lv1_1) and (icmp_ln774_reg_915_pp0_iter2_reg = ap_const_lv1_0) and (patternId_val_load_read_reg_837 = ap_const_lv8_2))) then 
            ap_phi_mux_pix_phi_fu_392_p12 <= ap_const_lv12_F00;
        else 
            ap_phi_mux_pix_phi_fu_392_p12 <= ap_phi_reg_pp0_iter3_pix_reg_388;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_phi_ln1975_reg_340 <= "XX";
    ap_phi_reg_pp0_iter0_pix_3_reg_368 <= "XXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_4_reg_351 <= "XXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_reg_388 <= "XXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_empty_91_reg_323 <= "X";
    ap_phi_reg_pp0_iter1_empty_92_reg_306 <= "X";

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    bckgndYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, bckgndYUV_empty_n, icmp_ln774_reg_915, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            bckgndYUV_blk_n <= bckgndYUV_empty_n;
        else 
            bckgndYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bckgndYUV_read_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln774_reg_915, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_915 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            bckgndYUV_read <= ap_const_logic_1;
        else 
            bckgndYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    boxBottom_fu_634_p2 <= std_logic_vector(unsigned(boxSize) + unsigned(boxVCoord_loc_1_fu_140));
    boxHCoord <= 
        sub_ln1914_fu_518_p2 when (ap_phi_mux_empty_92_phi_fu_309_p8(0) = '1') else 
        add_ln1912_fu_523_p2;

    boxHCoord_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln774_fu_440_p2, ap_block_pp0_stage0_11001, patternId_val_load_read_reg_837, icmp_ln1884_fu_460_p2)
    begin
        if (((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_837 = ap_const_lv8_1))) then 
            boxHCoord_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxHCoord_loc_1_out <= boxHCoord_loc_1_load_reg_910;

    boxHCoord_loc_1_out_ap_vld_assign_proc : process(icmp_ln774_reg_915, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_915 = ap_const_lv1_1))) then 
            boxHCoord_loc_1_out_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_loc_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxRight_fu_629_p2 <= std_logic_vector(unsigned(boxSize) + unsigned(boxHCoord_loc_1_fu_144));
    boxVCoord <= 
        sub_ln1918_fu_542_p2 when (ap_phi_mux_empty_91_phi_fu_326_p8(0) = '1') else 
        add_ln1916_fu_547_p2;

    boxVCoord_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln774_fu_440_p2, ap_block_pp0_stage0_11001, patternId_val_load_read_reg_837, icmp_ln1884_fu_460_p2)
    begin
        if (((icmp_ln774_fu_440_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1884_fu_460_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_837 = ap_const_lv8_1))) then 
            boxVCoord_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxVCoord_loc_1_out <= boxVCoord_loc_1_load_reg_905;

    boxVCoord_loc_1_out_ap_vld_assign_proc : process(icmp_ln774_reg_915, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_915 = ap_const_lv1_1))) then 
            boxVCoord_loc_1_out_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_loc_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    color_read_reg_790 <= color;
    empty_fu_739_p3 <= 
        ap_phi_mux_pix_3_phi_fu_372_p12 when (tobool(0) = '1') else 
        select_ln1991_fu_732_p3;
    hDir_load_load_fu_466_p1 <= hDir;
    icmp_ln1884_fu_460_p2 <= "1" when (or_ln1884_fu_455_p2 = ap_const_lv16_0) else "0";
    icmp_ln1889_fu_470_p2 <= "1" when (unsigned(boxHCoord_loc_1_fu_144) > unsigned(hMax)) else "0";
    icmp_ln1894_fu_481_p2 <= "1" when (unsigned(zext_ln1914_1_cast_reg_885) > unsigned(boxHCoord_loc_1_fu_144)) else "0";
    icmp_ln1901_fu_496_p2 <= "1" when (unsigned(boxVCoord_loc_1_fu_140) > unsigned(vMax)) else "0";
    icmp_ln1906_fu_507_p2 <= "1" when (unsigned(zext_ln1914_1_cast_reg_885) > unsigned(boxVCoord_loc_1_fu_140)) else "0";
    icmp_ln1932_1_fu_650_p2 <= "1" when (unsigned(y) < unsigned(boxBottom_fu_634_p2)) else "0";
    icmp_ln1932_fu_639_p2 <= "1" when (unsigned(y) < unsigned(boxVCoord_loc_1_fu_140)) else "0";
    icmp_ln1937_1_fu_666_p2 <= "1" when (unsigned(x_1_reg_899) < unsigned(boxRight_fu_629_p2)) else "0";
    icmp_ln1937_fu_655_p2 <= "1" when (unsigned(x_1_reg_899) < unsigned(boxHCoord_loc_1_fu_144)) else "0";
    icmp_ln1963_fu_576_p2 <= "1" when (x_fu_136 = crossHairX) else "0";
    icmp_ln774_fu_440_p2 <= "1" when (x_fu_136 = loopWidth) else "0";
    or_ln1884_fu_455_p2 <= (y or x_fu_136);
    or_ln1963_fu_581_p2 <= (icmp_ln1963_fu_576_p2 or cmp2_i);

    ovrlayYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, ovrlayYUV_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ovrlayYUV_blk_n <= ovrlayYUV_full_n;
        else 
            ovrlayYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ovrlayYUV_din <= ((pixOut_13_fu_718_p3 & empty_fu_739_p3) & pixOut_14_fu_725_p3);

    ovrlayYUV_write_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ovrlayYUV_write <= ap_const_logic_1;
        else 
            ovrlayYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    patternId_val_load_read_reg_837 <= patternId_val_load;
    pixIn_fu_599_p1 <= bckgndYUV_dout(12 - 1 downto 0);
    pixOut_11_fu_704_p3 <= 
        ap_const_lv12_0 when (and4_i(0) = '1') else 
        ap_phi_mux_pix_phi_fu_392_p12;
    pixOut_12_fu_711_p3 <= 
        ap_const_lv12_0 when (and26_i(0) = '1') else 
        ap_phi_mux_pix_4_phi_fu_354_p12;
    pixOut_13_fu_718_p3 <= 
        ap_phi_mux_pix_4_phi_fu_354_p12 when (tobool(0) = '1') else 
        pixOut_12_fu_711_p3;
    pixOut_14_fu_725_p3 <= 
        ap_phi_mux_pix_phi_fu_392_p12 when (tobool(0) = '1') else 
        pixOut_11_fu_704_p3;
    pixOut_7_fu_693_p3 <= 
        boxColorB when (and_ln1947_fu_689_p2(0) = '1') else 
        boxColorG;
    select_ln1911_fu_528_p3 <= 
        sub_ln1914_fu_518_p2 when (ap_phi_mux_empty_92_phi_fu_309_p8(0) = '1') else 
        add_ln1912_fu_523_p2;
    select_ln1915_fu_552_p3 <= 
        sub_ln1918_fu_542_p2 when (ap_phi_mux_empty_91_phi_fu_326_p8(0) = '1') else 
        add_ln1916_fu_547_p2;
    select_ln1975_fu_586_p3 <= 
        ap_const_lv2_2 when (trunc_ln774_fu_451_p1(0) = '1') else 
        ap_const_lv2_1;
    select_ln1991_fu_732_p3 <= 
        ap_const_lv12_0 when (and10_i(0) = '1') else 
        ap_phi_mux_pix_3_phi_fu_372_p12;
    sub_ln1914_fu_518_p2 <= std_logic_vector(unsigned(boxHCoord_loc_1_fu_144) - unsigned(zext_ln1914_cast_reg_891));
    sub_ln1918_fu_542_p2 <= std_logic_vector(unsigned(boxVCoord_loc_1_fu_140) - unsigned(zext_ln1914_cast_reg_891));
    trunc_ln774_fu_451_p1 <= x_fu_136(1 - 1 downto 0);
    vDir_load_load_fu_492_p1 <= vDir;
    whiYuv_2_address0 <= zext_ln1975_fu_699_p1(2 - 1 downto 0);

    whiYuv_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            whiYuv_2_ce0 <= ap_const_logic_1;
        else 
            whiYuv_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_2_fu_445_p2 <= std_logic_vector(unsigned(x_fu_136) + unsigned(ap_const_lv16_1));
    xor_ln1932_fu_644_p2 <= (icmp_ln1932_fu_639_p2 xor ap_const_lv1_1);
    xor_ln1937_fu_660_p2 <= (icmp_ln1937_fu_655_p2 xor ap_const_lv1_1);
    zext_ln1914_1_cast_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1914_1),16));
    zext_ln1914_cast_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1914),16));
    zext_ln1975_fu_699_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter2_phi_ln1975_reg_340),64));
end behav;
